namespace QimErp.Shared.DemoData.Industry.Profiles;

public sealed class ConstructionIndustryProfile : IIndustryProfile
{
    public string Code => "CONSTRUCTION";
    public string DisplayName => "Construction & Civil Works";

    public IReadOnlyList<string> SampleCompanyNames =>
    [
        "Consar Ltd", "M Barbisotti & Sons", "Micheletti & Co", "P.W. Ghana Ltd",
        "Justmoh Construction", "Berock Ventures", "First Sky Group",
        "Lordmav Construction", "Top International Engineering",
        "Ghana Highway Authority Contractors", "Cherubim Construction",
        "RKL Engineering", "B5 Plus Building Contractors", "JV Engineering Services",
        "China Railway Wuju (Ghana)", "Constructors Ghana Limited"
    ];

    public OrgHierarchySpec BuildOrgHierarchy(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        var (units, distribution) = tier switch
        {
            CompanyTier.Startup    => (StartupUnits,    StartupDistribution),
            CompanyTier.SME        => (SmeUnits,        SmeDistribution),
            CompanyTier.Corporate  => (CorporateUnits,  CorporateDistribution),
            CompanyTier.NonProfit  => (SmeUnits,        SmeDistribution),
            _                      => (SmeUnits,        SmeDistribution)
        };
        return OrgHierarchyBuilder.Build(units, distribution, targetEmployees, randomSeed);
    }

    public IReadOnlyList<JobTitleSpec> JobTitles => _jobTitles;

    public StationLayout BuildStations(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        // Corporate tier uses the curated 45-entry station catalogue verbatim — full
        // names, addresses, codes, descriptions, phones, emails, and station types
        // sourced from real Ghana construction project locations, plant yards, quarries,
        // and asphalt/batching plants. Other tiers fall back to the procedural builder.
        if (tier == CompanyTier.Corporate)
        {
            var hqRow = _constructionStations[0];
            var rest = _constructionStations.Skip(1).ToList();
            var branchTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Regional Office", "Project Site"
            };
            return new StationLayout(
                Headquarters: hqRow,
                Branches: rest.Where(s => branchTypes.Contains(s.StationType)).ToList(),
                Satellites: rest.Where(s => !branchTypes.Contains(s.StationType)).ToList());
        }

        var rng = new Random(randomSeed);
        var hq = new StationSpec(
            Code: "HQ",
            Name: "Headquarters",
            StationType: "Head Office",
            Region: "Greater Accra",
            City: "Accra",
            Address: "Spintex Road, Accra",
            CapacityMin: 50,
            CapacityMax: tier == CompanyTier.Corporate ? 400 : 100);

        var siteCount = tier switch
        {
            CompanyTier.Startup   => 1,
            CompanyTier.SME       => Math.Max(2, targetEmployees / 80),
            CompanyTier.Corporate => Math.Max(5, Math.Min(20, targetEmployees / 100)),
            _                     => 3
        };

        var projects = new List<StationSpec>(siteCount);
        for (var i = 0; i < siteCount; i++)
        {
            var region = GhanaGeography.Regions[rng.Next(GhanaGeography.Regions.Count)];
            var cities = GhanaGeography.CitiesByRegion[region];
            var city = cities[rng.Next(cities.Count)];
            projects.Add(new StationSpec(
                Code: $"PROJ{i + 1:D3}",
                Name: $"{city} Project Site",
                StationType: "Project Site",
                Region: region,
                City: city,
                Address: $"Site {i + 1}, {city}",
                CapacityMin: 30,
                CapacityMax: 350));
        }

        var yardCount = Math.Max(1, siteCount / 3);
        var yards = new List<StationSpec>(yardCount);
        for (var i = 0; i < yardCount; i++)
        {
            yards.Add(new StationSpec(
                Code: $"YARD{i + 1:D2}",
                Name: $"Equipment Yard {i + 1}",
                StationType: "Equipment Yard",
                Region: "Greater Accra",
                City: "Tema",
                Address: $"Industrial Area, Tema",
                CapacityMin: 5,
                CapacityMax: 25));
        }

        return new StationLayout(hq, projects, yards);
    }

    public EmployeeDistributionSpec EmployeeDistribution => new(
        ByRankLevel: new Dictionary<int, double>
        {
            [5] = 0.005,
            [4] = 0.030,
            [3] = 0.080,
            [2] = 0.485,
            [1] = 0.400
        },
        ByOrgUnitCode: null);

    public SalaryBandSpec SalaryBands => new(
        ByRankLevel: new Dictionary<int, (decimal Min, decimal Max)>
        {
            [5] = (18_000m, 40_000m),
            [4] = (8_000m,  17_000m),
            [3] = (4_500m,  10_000m),
            [2] = (1_800m,   4_500m),
            [1] = (1_200m,   2_200m)
        });

    private static readonly IReadOnlyList<string> ExecJobs = ["MD-001", "COO-001", "DOE-001", "DOO-001"];
    private static readonly IReadOnlyList<string> OpsJobs = ["PD-001", "SPM-001", "PM-001", "APM-001", "SM-001", "FM-GEN-001", "DOC-001"];
    private static readonly IReadOnlyList<string> EngJobs = ["DOE-001", "SCE-001", "CE-001", "STR-001", "GEO-001", "MECH-001", "ELEC-001", "MEP-001", "ARCH-001", "BIM-001", "LS-001", "SOE-001", "SE-001"];
    private static readonly IReadOnlyList<string> CommercialJobs = ["CM-001", "CTR-001", "SQS-001", "QS-001", "JQS-001", "EST-001", "CE-COST-001", "PLN-001", "SCH-001"];
    private static readonly IReadOnlyList<string> HseJobs = ["HSE-MGR-001", "HSE-OFF-001", "HSE-INS-001", "LAB-001"];
    private static readonly IReadOnlyList<string> PlantJobs = ["PE-EXC-001", "PE-LD-001", "PE-CR-001", "PE-RL-001", "FM-GEN-001"];
    private static readonly IReadOnlyList<string> ProcJobs = ["PROC-MGR-001", "BUY-001", "STR-OFF-001", "LOG-001"];
    private static readonly IReadOnlyList<string> FinJobs = ["ACC-001", "FIN-OFF-001"];
    private static readonly IReadOnlyList<string> HrJobs = ["HR-OFF-001", "CMP-001"];
    private static readonly IReadOnlyList<string> ItJobs = ["IT-001"];
    private static readonly IReadOnlyList<string> SiteJobs = ["FM-GEN-001", "FM-STL-001", "FM-CON-001", "FM-MAS-001", "FM-CAR-001", "FM-PLM-001", "MASON-001", "CARP-001", "STL-001", "PLM-001", "ELEC-T-001", "WLD-001", "PNT-001", "DRV-H-001", "DRV-L-001", "SEC-001", "CLN-001"];

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> StartupUnits =
    [
        new("FOUNDER", "Founder/MD",   null,      OrgUnitKind.Executive, ExecJobs),
        new("SITE",    "Site Ops",     "FOUNDER", OrgUnitKind.Function,  SiteJobs),
        new("ADMIN",   "Admin",        "FOUNDER", OrgUnitKind.Function,  FinJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> StartupDistribution = new Dictionary<string, double>
    {
        ["FOUNDER"] = 0.10,
        ["SITE"]    = 0.75,
        ["ADMIN"]   = 0.15
    };

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> SmeUnits =
    [
        new("EXEC",  "Executive",            null,   OrgUnitKind.Executive, ExecJobs),
        new("OPS",   "Site Operations",      "EXEC", OrgUnitKind.Function,  OpsJobs),
        new("ENG",   "Engineering",          "EXEC", OrgUnitKind.Function,  EngJobs),
        new("COMM",  "Commercial / QS",      "EXEC", OrgUnitKind.Function,  CommercialJobs),
        new("HSE",   "Health, Safety & Env", "EXEC", OrgUnitKind.Function,  HseJobs),
        new("ADMIN", "Finance & Admin",      "EXEC", OrgUnitKind.Function,  FinJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> SmeDistribution = new Dictionary<string, double>
    {
        ["EXEC"]  = 0.04,
        ["OPS"]   = 0.65,
        ["ENG"]   = 0.10,
        ["COMM"]  = 0.06,
        ["HSE"]   = 0.05,
        ["ADMIN"] = 0.10
    };

    // Corporate-tier baseline OrgUnits — 9 units carrying rich Description / Budget /
    // CostCenter / Purpose / Phone / Email-local-part. The {Company} placeholder gets
    // substituted with the actual tenant's company name at row-emit time. Phones /
    // budgets are representative of a tier-1 Ghana civil works contractor (think JV
    // Engineering, Justmoh, Consar) holding active road, bridge, and building works.
    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> CorporateUnits =
    [
        new("EXEC", "Executive", null, OrgUnitKind.Executive, ExecJobs,
            Description: "Office of the Managing Director and executive leadership of {Company}",
            BudgetMin: 1_500_000m, BudgetMax: 3_000_000m,
            CostCenter: "CC-EXEC-001",
            Purpose: "Set and execute {Company} strategy; lead the executive committee; manage Ministry of Roads, MoWH, and lender relationships",
            Phone: "+233 30 222 4100", Email: "executive"),
        new("OPERATIONS", "Site Operations", "EXEC", OrgUnitKind.Function, OpsJobs,
            Description: "Delivers {Company}'s active project portfolio across roads, bridges, buildings, and civil works on time, on budget, and to specification",
            BudgetMin: 5_000_000m, BudgetMax: 15_000_000m,
            CostCenter: "CC-OPS-001",
            Purpose: "Achieve on-time and on-budget delivery on every {Company} project; sustain HSE compliance and client satisfaction across all live sites",
            Phone: "+233 30 222 4200", Email: "operations"),
        new("ENGINEERING", "Engineering & Design", "EXEC", OrgUnitKind.Function, EngJobs,
            Description: "Civil, structural, geotechnical, MEP, and BIM engineering — {Company}'s technical backbone covering design, setting-out, and construction supervision",
            BudgetMin: 2_500_000m, BudgetMax: 6_000_000m,
            CostCenter: "CC-ENG-001",
            Purpose: "Deliver constructable, code-compliant designs and engineering oversight for every {Company} project; protect technical integrity and quality",
            Phone: "+233 30 222 4300", Email: "engineering"),
        new("COMMERCIAL", "Commercial, Estimating & Contracts", "EXEC", OrgUnitKind.Function, CommercialJobs,
            Description: "Tendering, estimation, quantity surveying, contracts, planning, and cost control for {Company}'s pipeline and live projects",
            BudgetMin: 1_200_000m, BudgetMax: 3_000_000m,
            CostCenter: "CC-COMM-001",
            Purpose: "Win profitable work; safeguard {Company}'s commercial position through robust pricing, contract administration, and earned value management",
            Phone: "+233 30 222 4400", Email: "commercial"),
        new("HSE", "Health, Safety, Environment & Quality", "EXEC", OrgUnitKind.Function, HseJobs,
            Description: "Site safety, occupational health, environmental compliance, and materials laboratory — {Company}'s second line of defence on every site",
            BudgetMin: 600_000m, BudgetMax: 1_500_000m,
            CostCenter: "CC-HSE-001",
            Purpose: "Drive zero-harm culture across {Company}; ensure EPA, FWSC, and Labour Department compliance; maintain ISO 45001 readiness",
            Phone: "+233 30 222 4500", Email: "hse"),
        new("PLANT", "Plant, Equipment & Workshop", "EXEC", OrgUnitKind.Function, PlantJobs,
            Description: "Heavy equipment fleet, plant operators, workshop, and asphalt/batching plant operations supporting all {Company} sites",
            BudgetMin: 2_000_000m, BudgetMax: 5_000_000m,
            CostCenter: "CC-PLT-001",
            Purpose: "Maximise plant availability, utilisation, and lifecycle value for {Company}; keep critical fleet on-site and running",
            Phone: "+233 30 222 4600", Email: "plant"),
        new("PROCUREMENT", "Procurement & Logistics", "EXEC", OrgUnitKind.Function, ProcJobs,
            Description: "Supplier sourcing, materials procurement, stores, and inbound logistics for cement, steel, aggregates, fuel, and project consumables",
            BudgetMin: 800_000m, BudgetMax: 2_000_000m,
            CostCenter: "CC-PROC-001",
            Purpose: "Procure right-quality materials at the right price and on time for {Company} sites; manage supplier risk and stores accuracy",
            Phone: "+233 30 222 4700", Email: "procurement"),
        new("FINANCE", "Finance & Accounts", "EXEC", OrgUnitKind.Function, FinJobs,
            Description: "Project accounting, IPC certification, payroll, tax, and management reporting for {Company}",
            BudgetMin: 500_000m, BudgetMax: 1_200_000m,
            CostCenter: "CC-FIN-001",
            Purpose: "Produce accurate {Company} project and corporate accounts; manage cash, IPC submissions, and statutory tax compliance",
            Phone: "+233 30 222 4800", Email: "finance"),
        new("HR", "HR, Admin & IT", "EXEC", OrgUnitKind.Function, HrJobs,
            Description: "Talent acquisition, site labour relations, training, IT support, and general administration for {Company}'s head office and sites",
            BudgetMin: 400_000m, BudgetMax: 1_000_000m,
            CostCenter: "CC-HR-001",
            Purpose: "Attract, develop, and retain skilled labour for {Company}; sustain industrial harmony with site unions and trade associations",
            Phone: "+233 30 222 4900", Email: "hr")
    ];
    private static readonly IReadOnlyDictionary<string, double> CorporateDistribution = new Dictionary<string, double>
    {
        ["EXEC"]        = 0.02,
        ["OPERATIONS"]  = 0.55,
        ["ENGINEERING"] = 0.10,
        ["COMMERCIAL"]  = 0.06,
        ["HSE"]         = 0.05,
        ["PLANT"]       = 0.10,
        ["PROCUREMENT"] = 0.04,
        ["FINANCE"]     = 0.04,
        ["HR"]          = 0.04
    };

    // ~55 enriched JobTitleSpec entries spanning executives, project management, civils,
    // structural/MEP design, QS / commercial, planning, HSE, plant operators, foremen,
    // skilled trades, and support. Salary bands per the Construction Profile guidance:
    // L1: 1,500-4,500 / L2: 4,000-10,000 / L3: 9,000-22,000 / L4: 20,000-45,000 /
    // L5: 42,000-95,000. Pay grades use CON-1..CON-10 for staff; T1..T6 for site / trades.
    // Annual leave: L5=30, L4=27, L3=24, L2=21, L1=21. {Company} placeholder substituted at row-emit.
    private static readonly IReadOnlyList<JobTitleSpec> _jobTitles =
    [
        // ── Executive (Level 5) ───────────────────────────────────────────────
        new("MD-001", "Managing Director / CEO", 5, 60_000m, 95_000m, "EXEC", null, true,
            "Master's Degree (Civil Eng. / MBA)", 20,
            "Executive Leadership, Construction Strategy, P&L Management, Government Relations, Stakeholder Management",
            "Chief executive accountable for {Company} overall strategy, profitability, and stakeholder relations",
            "CON-10",
            "Set and execute {Company} strategy; chair the executive committee; sponsor major bids; manage Ministry of Roads, MoWH, and key client relationships; drive sustainable growth",
            "Revenue Growth, EBITDA Margin, Order Book Value, Project Margin, HSE LTI Frequency Rate, Cashflow",
            30),
        new("COO-001", "Chief Operating Officer", 5, 50_000m, 85_000m, "EXEC", "MD-001", true,
            "Master's Degree (Civil Eng. / Construction Mgmt)", 18,
            "Operational Leadership, Multi-Project Delivery, Risk Management, Lean Construction, Change Management",
            "Executive owning end-to-end project delivery, operational performance, and on-site execution across {Company}",
            "CON-10",
            "Oversee project portfolio delivery; chair monthly project review boards; manage operational risk; lead delivery transformation initiatives; deputise for the MD",
            "On-Time Completion Rate, Cost Performance Index, Schedule Performance Index, Safety Incident Rate, Client NPS",
            30),
        new("DOO-001", "Director of Operations", 5, 45_000m, 75_000m, "OPERATIONS", "COO-001", true,
            "Master's Degree (Construction Management)", 15,
            "Project Portfolio Management, Resource Optimisation, P&L Ownership, Subcontractor Management",
            "Owns the operational P&L and resource utilisation across all {Company} live projects",
            "CON-9",
            "Deploy project managers and resources across portfolio; resolve cross-project conflicts; own monthly operations reporting; drive site productivity improvements",
            "Site Productivity Index, Resource Utilisation, Project Margin, Subcontractor Performance Rating",
            27),
        new("DOE-001", "Director of Engineering", 5, 42_000m, 72_000m, "ENGINEERING", "MD-001", true,
            "Master's Degree (Civil/Structural Eng.) + GhIE", 15,
            "Engineering Leadership, Design Management, Technical Governance, BIM Strategy, Code Compliance",
            "Sets technical standards and signs off engineering deliverables for every {Company} project",
            "CON-9",
            "Lead engineering function; chair design reviews; approve key technical submissions; manage GhIE professional development of engineers; safeguard technical integrity",
            "Design Compliance Score, Technical Query Closure Rate, Engineer Retention, Drawing First-Pass Quality",
            27),
        // ── Senior management (Level 4) ───────────────────────────────────────
        new("PD-001", "Project Director", 4, 32_000m, 45_000m, "OPERATIONS", "DOO-001", true,
            "Bachelor's Degree (Civil Eng.) + PMP / GhIE", 12,
            "Programme Management, Stakeholder Management, FIDIC Contracts, EPC Delivery",
            "Leads a major {Company} programme (e.g. road corridor, large building) covering all design, commercial, and site delivery",
            "CON-8",
            "Own programme P&L; lead client and consultant relationships; chair monthly progress meetings; resolve contractual issues; deliver programme milestones",
            "Programme Margin, Milestone Achievement Rate, Client Satisfaction Score, Variation Recovery, EOT Outcomes",
            27),
        new("SPM-001", "Senior Project Manager", 4, 26_000m, 38_000m, "OPERATIONS", "PD-001", true,
            "Bachelor's Degree (Civil Eng.) + PMP", 10,
            "Project Management, NEC/FIDIC, Earned Value, Risk Management, Subcontractor Management",
            "Manages a single complex {Company} project end-to-end including budget, schedule, quality, and safety",
            "CON-8",
            "Plan and execute project; manage CPM schedule and budget; chair weekly site meetings; control variations and claims; lead site team",
            "Cost & Schedule Variance, Quality Defects Rate, IPC Cycle Time, Safety Compliance, Resource Productivity",
            27),
        new("PM-001", "Project Manager", 4, 22_000m, 32_000m, "OPERATIONS", "SPM-001", true,
            "Bachelor's Degree (Civil Eng.) + PMP/Prince2", 7,
            "Project Planning, Site Management, Cost Control, Subcontractor Coordination",
            "Plans, mobilises, and delivers a {Company} project in line with contract, budget, and HSE standards",
            "CON-7",
            "Run day-to-day project delivery; manage labour, plant, materials, and subcontractors; submit progress and IPC reports; resolve site issues",
            "Project Margin, Schedule Adherence, IPC Realisation, Subcontractor Performance, Safety Compliance",
            24),
        new("APM-001", "Assistant Project Manager", 4, 20_000m, 28_000m, "OPERATIONS", "PM-001", false,
            "Bachelor's Degree (Civil Eng.)", 5,
            "Project Coordination, Document Control, Reporting, Subcontractor Liaison",
            "Supports the Project Manager in planning, reporting, and day-to-day site administration on a {Company} project",
            "CON-7",
            "Maintain project tracker and registers; coordinate subcontractor RFIs; prepare progress reports; assist with valuations; deputise for PM as needed",
            "Reporting Timeliness, RFI Closure Rate, Document Control Accuracy, PM Satisfaction Score",
            24),
        new("SM-001", "Site Manager", 4, 20_000m, 30_000m, "OPERATIONS", "PM-001", true,
            "Bachelor's Degree / HND (Construction)", 8,
            "Site Supervision, Method Statements, Productivity, Foreman Management",
            "Single-point owner of all activity on a {Company} construction site — labour, plant, quality, and safety",
            "CON-7",
            "Direct daily site activities; supervise foremen and subcontractors; sign off method statements; enforce HSE; record daily site diary",
            "Daily Productivity, HSE Compliance, Quality Snag Rate, Workforce Discipline",
            24),
        new("CM-001", "Commercial Manager", 4, 22_000m, 35_000m, "COMMERCIAL", "DOO-001", true,
            "Bachelor's Degree (QS / Construction Mgmt) + RICS", 10,
            "Commercial Management, NEC/FIDIC, Cost Control, Variation Management, Final Accounts",
            "Owns the commercial outcome of {Company} projects from tender through final account",
            "CON-8",
            "Manage commercial team; negotiate contracts and variations; chair monthly cost reviews; lead final account agreement; protect cash and margin",
            "Project Margin, Variation Recovery, Cash Conversion, Final Account Cycle Time",
            27),
        new("CTR-001", "Contracts Manager", 4, 20_000m, 32_000m, "COMMERCIAL", "CM-001", true,
            "Bachelor's Degree (Law / QS) + FIDIC training", 8,
            "Contract Drafting, Claims, Dispute Resolution, FIDIC, NEC, Procurement Law",
            "Manages contract administration, claims, and disputes for {Company} projects",
            "CON-7",
            "Draft and review contracts; administer correspondence per contract; manage notices, claims, and EOT submissions; advise PMs on contract risk",
            "Claim Recovery Rate, Notice Compliance, Dispute Resolution Time, Contract Risk Score",
            24),
        new("PROC-MGR-001", "Procurement Manager", 4, 18_000m, 28_000m, "PROCUREMENT", "DOO-001", true,
            "Bachelor's Degree (Supply Chain / QS)", 8,
            "Strategic Sourcing, Supplier Negotiation, Materials Markets, Public Procurement Act",
            "Owns sourcing strategy, supplier panel, and material procurement for {Company} projects",
            "CON-7",
            "Develop supplier panel; lead strategic tenders for cement, steel, fuel; negotiate framework agreements; manage procurement KPIs",
            "Procurement Cost Savings, Supplier OTIF, Stockout Frequency, Tender Cycle Time",
            24),
        new("HSE-MGR-001", "HSE Manager", 4, 20_000m, 30_000m, "HSE", "MD-001", true,
            "Bachelor's Degree (OHS / Eng.) + NEBOSH IGC", 8,
            "Occupational Health & Safety, NEBOSH, ISO 45001, EPA Compliance, Incident Investigation",
            "Leads HSE strategy and implementation across all {Company} sites and head office",
            "CON-7",
            "Set HSE policy; conduct site audits; lead incident investigations; train workforce; report to Board on safety performance",
            "LTI Frequency Rate, Near-Miss Reporting Rate, Audit Score, Training Coverage, EPA Compliance",
            24),
        // ── Engineering & Specialists (Level 3-4) ─────────────────────────────
        new("SCE-001", "Senior Civil Engineer", 4, 20_000m, 30_000m, "ENGINEERING", "DOE-001", true,
            "Bachelor's Degree (Civil Eng.) + GhIE", 8,
            "Civil Design, Pavement Design, Drainage, Setting-Out, Site Engineering",
            "Senior technical lead on civils packages — highways, drainage, earthworks for {Company} projects",
            "CON-7",
            "Lead civils design and supervision; review subordinate engineers' work; sign off setting-out and quality records; mentor junior engineers",
            "Design First-Pass Quality, RFI Response Time, Defect Rate, Mentoring Hours",
            24),
        new("CE-001", "Civil Engineer", 3, 12_000m, 20_000m, "ENGINEERING", "SCE-001", false,
            "Bachelor's Degree (Civil Eng.)", 4,
            "Civil Engineering, AutoCAD, Civil 3D, Setting-Out, Quality Control",
            "Civils engineer supporting design, setting-out, and on-site quality on {Company} projects",
            "CON-6",
            "Produce civil drawings and calculations; supervise setting-out; conduct quality inspections; raise RFIs; support method statements",
            "Drawing Output, Inspection Closure Rate, Quality Hold Points Met, RFI Quality",
            24),
        new("STR-001", "Structural Engineer", 4, 20_000m, 30_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Civil/Structural Eng.) + GhIE", 6,
            "Structural Analysis, Eurocode, BS 8110, ETABS, STAAD, Reinforced Concrete Design",
            "Designs and reviews structural elements (RC, steel, foundations) for {Company} buildings and bridges",
            "CON-7",
            "Design RC and steel structures; produce structural drawings; review subcontractor design; advise on-site on structural queries",
            "Design Output, Code Compliance Score, Site Query Closure, Drawing Revisions",
            24),
        new("GEO-001", "Geotechnical Engineer", 4, 20_000m, 28_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Civil / Geotechnical Eng.)", 6,
            "Geotechnical Investigation, Foundation Design, Slope Stability, Soil Mechanics, Plaxis",
            "Provides geotechnical input on foundations, earthworks, and ground risk for {Company} projects",
            "CON-7",
            "Plan and interpret SI; design shallow and deep foundations; advise on slope stability and dewatering; sign off ground risk registers",
            "Foundation Design Quality, Ground-Risk Issues Closure, SI Cost Efficiency",
            24),
        new("MECH-001", "Mechanical Engineer", 3, 12_000m, 20_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Mechanical Eng.)", 5,
            "Mechanical Design, HVAC, Plumbing, Plant Maintenance, BS Standards",
            "Mechanical engineering lead on building services and plant for {Company} projects",
            "CON-6",
            "Design HVAC and plumbing; review M&E subcontractor proposals; supervise mechanical installations; commission plant",
            "Design Quality, Installation Defect Rate, Commissioning On-Time, Plant Availability",
            24),
        new("ELEC-001", "Electrical Engineer", 3, 12_000m, 20_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Electrical Eng.)", 5,
            "Electrical Design, ECG/Power Distribution, Lighting, IEE Wiring Regs, Generator Sizing",
            "Electrical engineering lead on building electrical and ECG interfacing for {Company} projects",
            "CON-6",
            "Design LV electrical systems; coordinate ECG and EMR interfaces; supervise installation; oversee testing and commissioning",
            "Design Quality, ECG Connection Time, Test Pass Rate, Installation Defect Rate",
            24),
        new("MEP-001", "MEP Coordinator", 4, 18_000m, 26_000m, "ENGINEERING", "DOE-001", true,
            "Bachelor's Degree (M&E Eng.)", 6,
            "MEP Coordination, BIM Clash Detection, Services Integration, Commissioning",
            "Coordinates mechanical, electrical, plumbing, and fire services across {Company} building projects",
            "CON-7",
            "Lead MEP coordination meetings; resolve BIM clashes; manage MEP subcontractors; oversee testing and commissioning",
            "Clash Closure Rate, MEP Subcontractor Performance, Commissioning Milestones",
            24),
        new("ARCH-001", "Architect", 3, 12_000m, 20_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Architecture) + GIA", 5,
            "Architectural Design, Revit, AutoCAD, Building Code, Sustainable Design",
            "Produces architectural design and supervises {Company} building projects to ensure design intent",
            "CON-6",
            "Develop architectural drawings; coordinate with structural and MEP; supervise finishing; manage design changes",
            "Drawing Output, Design Change Frequency, Client Design Approval Cycle",
            24),
        new("BIM-001", "BIM Coordinator", 3, 12_000m, 20_000m, "ENGINEERING", "DOE-001", false,
            "Bachelor's Degree (Eng./Architecture) + Revit certification", 4,
            "BIM, Revit, Navisworks, ISO 19650, Federated Modelling, Clash Detection",
            "Manages the federated BIM model and coordination workflow for {Company} projects",
            "CON-6",
            "Maintain federated model; run clash detection; train design team on BIM workflow; produce 4D/5D outputs",
            "Model Quality Score, Clash Reduction Rate, BIM Adoption Index",
            24),
        new("LS-001", "Land Surveyor", 3, 11_000m, 18_000m, "ENGINEERING", "SCE-001", false,
            "BSc / HND (Land Surveying) + LSAG", 4,
            "Topographic Survey, Total Station, GPS/RTK, GIS, Cadastral Survey",
            "Performs topographic, control, and as-built surveys for {Company} project sites",
            "CON-6",
            "Establish site control; conduct topo and as-built surveys; deliver setting-out reference points; produce survey drawings",
            "Survey Accuracy, Setting-Out Cycle Time, As-Built Quality",
            24),
        new("SOE-001", "Setting-Out Engineer", 3, 10_000m, 16_000m, "ENGINEERING", "SCE-001", false,
            "BSc / HND (Civil / Survey Eng.)", 3,
            "Setting-Out, Total Station, AutoCAD, Geometric Control, Site Engineering",
            "Translates design drawings into physical setting-out on {Company} sites",
            "CON-6",
            "Set out structures, roads, and services; verify dimensional control; record as-builts; raise dimensional RFIs",
            "Setting-Out Accuracy, Rework due to Setting-Out, RFI Quality",
            24),
        new("SE-001", "Site Engineer", 3, 9_000m, 15_000m, "ENGINEERING", "SCE-001", false,
            "Bachelor's Degree / HND (Civil Eng.)", 2,
            "Site Engineering, Setting-Out, Quality Control, Inspections, ITPs",
            "Day-to-day site engineering presence on a {Company} construction site",
            "CON-5",
            "Run site inspections; verify setting-out; sign off ITP hold points; raise NCRs; mentor trainee engineers",
            "Inspection Closure, NCR Recurrence Rate, Quality Hold Points Met",
            24),
        // ── Commercial / QS (Level 2-4) ───────────────────────────────────────
        new("SQS-001", "Senior Quantity Surveyor", 4, 20_000m, 30_000m, "COMMERCIAL", "CM-001", true,
            "Bachelor's Degree (QS) + RICS / GhIS", 8,
            "Cost Management, BoQ, Variations, Final Accounts, NEC/FIDIC",
            "Senior commercial lead on {Company} projects, owning monthly valuations and final accounts",
            "CON-7",
            "Lead project QS team; price variations; agree IPCs with consultant QS; settle final accounts; mentor junior QS",
            "IPC Realisation, Variation Recovery, Final Account Cycle, Cash Conversion",
            24),
        new("QS-001", "Quantity Surveyor", 3, 12_000m, 20_000m, "COMMERCIAL", "SQS-001", false,
            "Bachelor's Degree (QS) + GhIS", 4,
            "BoQ, Cost Estimation, Valuations, Subcontract Procurement, Cost Reporting",
            "Manages cost on {Company} projects from procurement through monthly valuations",
            "CON-6",
            "Prepare BoQ and valuations; procure and administer subcontracts; produce monthly cost reports; price variations",
            "Cost Report Accuracy, Subcontract Cycle Time, Variation Pricing Quality",
            24),
        new("JQS-001", "Junior Quantity Surveyor", 2, 6_000m, 9_500m, "COMMERCIAL", "QS-001", false,
            "HND / Bachelor's Degree (QS)", 1,
            "Take-Off, Costing, Excel, Cost Reports, Subcontract Administration",
            "Supports senior QS team with measurement, take-off, and basic cost administration",
            "CON-4",
            "Take off quantities; price small variations; assist with monthly valuations; maintain cost trackers",
            "Take-Off Accuracy, Tracker Completeness, Senior QS Satisfaction",
            21),
        new("EST-001", "Estimator", 3, 12_000m, 18_000m, "COMMERCIAL", "CM-001", false,
            "Bachelor's Degree (QS / Civil Eng.)", 4,
            "Tender Estimating, Pricing, Subcontractor Buyout, Risk Pricing, CESMM",
            "Prices new tenders for {Company} during the bid phase",
            "CON-6",
            "Produce tender estimates; obtain subcontractor and supplier quotes; price risk; coordinate bid team; submit tenders",
            "Tender Win Rate, Bid Margin Accuracy, Tender Submission On-Time",
            24),
        new("CE-COST-001", "Cost Engineer", 3, 11_000m, 18_000m, "COMMERCIAL", "CM-001", false,
            "Bachelor's Degree (Eng. / QS)", 4,
            "Earned Value Management, Cost Control, P6 Cost Loading, Forecasting",
            "Owns project cost control, EVM, and forecasting for large {Company} projects",
            "CON-6",
            "Set up cost baselines; track CPI/SPI; produce cost forecasts; flag cost overruns early; reconcile actuals to budget",
            "CPI/SPI Variance, Forecast Accuracy, Overrun Early-Warning Rate",
            24),
        new("PLN-001", "Project Planner", 3, 11_000m, 18_000m, "COMMERCIAL", "CM-001", false,
            "Bachelor's Degree (Eng.) + Primavera P6", 4,
            "Primavera P6, MS Project, CPM, Resource Loading, Look-Ahead Planning",
            "Maintains the project programme and look-aheads for {Company} sites",
            "CON-6",
            "Build and maintain CPM programme; produce 4-week look-aheads; analyse delay events; support EOT submissions",
            "Schedule Adherence, Look-Ahead Discipline, EOT Recovery Days",
            24),
        new("SCH-001", "Scheduler", 2, 6_000m, 9_500m, "COMMERCIAL", "PLN-001", false,
            "HND / Bachelor's Degree", 2,
            "Primavera P6, MS Project, Schedule Updates, Progress Reporting",
            "Updates project schedules and tracks progress for {Company} planning team",
            "CON-4",
            "Update schedules from site progress; produce weekly progress reports; flag schedule slippage; maintain schedule baselines",
            "Update Cycle Time, Reporting Quality, Schedule Data Integrity",
            21),
        // ── Foremen (Level 2-3) ──────────────────────────────────────────────
        new("FM-GEN-001", "General Foreman", 3, 9_500m, 15_000m, "OPERATIONS", "SM-001", true,
            "HND / Trade Master Certificate", 8,
            "Crew Leadership, Trades Coordination, Site Productivity, Safety Briefings",
            "Senior foreman coordinating multiple trades crews on a {Company} site",
            "T6",
            "Plan daily crew deployment; coordinate trades; conduct toolbox talks; report progress and incidents to Site Manager",
            "Daily Output vs Target, Crew Discipline, Toolbox Talk Coverage, Incident Rate",
            24),
        new("FM-STL-001", "Steel Fixing Foreman", 2, 7_500m, 11_000m, "OPERATIONS", "FM-GEN-001", true,
            "Trade Master Certificate", 6,
            "Steel Fixing, Bar Bending Schedule, Crew Leadership",
            "Leads the steel-fixing crew on {Company} sites for RC structures",
            "T5",
            "Read BBS; deploy and supervise steel fixers; check rebar before pour sign-off; report quality issues",
            "Daily Tonnes Fixed, Snag Rate, Crew Safety",
            21),
        new("FM-CON-001", "Concrete Foreman", 2, 7_500m, 11_000m, "OPERATIONS", "FM-GEN-001", true,
            "Trade Master Certificate", 6,
            "Concrete Operations, Pour Planning, Curing, Crew Leadership",
            "Leads concrete pour and curing operations on {Company} sites",
            "T5",
            "Plan and supervise concrete pours; coordinate with batching plant; supervise curing; record cube tests",
            "Pour Completion Rate, Cube Pass Rate, Pour Safety Incidents",
            21),
        new("FM-MAS-001", "Masonry Foreman", 2, 7_000m, 10_500m, "OPERATIONS", "FM-GEN-001", true,
            "Trade Master Certificate", 6,
            "Masonry, Block-Laying, Plastering, Crew Leadership",
            "Leads masonry crew on {Company} building projects",
            "T5",
            "Deploy masons; supervise block-laying and plastering; check verticality and finish; report progress",
            "Daily Sqm Laid, Quality Snag Rate, Crew Productivity",
            21),
        new("FM-CAR-001", "Carpentry Foreman", 2, 7_000m, 10_500m, "OPERATIONS", "FM-GEN-001", true,
            "Trade Master Certificate", 6,
            "Formwork, Joinery, Shuttering, Crew Leadership",
            "Leads carpentry and formwork crew on {Company} sites",
            "T5",
            "Plan formwork erection and striking; supervise joinery; check formwork stability before pour; coordinate with steel fixing",
            "Formwork Cycle Time, Reuse Rate, Pour Defects from Formwork",
            21),
        new("FM-PLM-001", "Plumbing Foreman", 2, 7_000m, 10_500m, "OPERATIONS", "FM-GEN-001", true,
            "Trade Master Certificate", 6,
            "Plumbing, Pipework, Drainage, Crew Leadership",
            "Leads plumbing crew installing drainage, water, and waste services on {Company} sites",
            "T5",
            "Deploy plumbers; supervise pipework installation; conduct pressure tests; coordinate with builders' work",
            "Installation Output, Test Pass Rate, Crew Safety",
            21),
        // ── Skilled Trades (Level 1-2) ───────────────────────────────────────
        new("MASON-001", "Mason", 2, 4_500m, 7_500m, "OPERATIONS", "FM-MAS-001", false,
            "Trade Certificate (NVTI Grade I/II)", 3,
            "Block-Laying, Plastering, Concrete Finishing",
            "Skilled mason laying blocks, plastering, and finishing concrete on {Company} sites",
            "T3",
            "Lay blocks per drawings; plaster walls; finish concrete; clean tools; comply with HSE rules",
            "Daily Output, Quality Score, Wastage Rate",
            21),
        new("CARP-001", "Carpenter", 2, 4_500m, 7_500m, "OPERATIONS", "FM-CAR-001", false,
            "Trade Certificate (NVTI Grade I/II)", 3,
            "Formwork, Joinery, Roof Carpentry",
            "Skilled carpenter erecting formwork and joinery on {Company} sites",
            "T3",
            "Erect and strike formwork; install joinery; cut and assemble timber; comply with HSE rules",
            "Daily Output, Formwork Defect Rate, Tool Care",
            21),
        new("STL-001", "Steel Fixer", 2, 4_500m, 7_500m, "OPERATIONS", "FM-STL-001", false,
            "Trade Certificate (NVTI Grade I/II)", 3,
            "Bar Bending, Rebar Tying, Reading BBS",
            "Skilled steel fixer cutting, bending, and tying rebar on {Company} sites",
            "T3",
            "Cut and bend rebar per BBS; tie rebar to drawings; place spacers; comply with HSE rules",
            "Daily Tonnes Fixed, Tying Quality, Wastage Rate",
            21),
        new("PLM-001", "Plumber", 2, 4_500m, 7_500m, "OPERATIONS", "FM-PLM-001", false,
            "Trade Certificate (NVTI Grade I/II)", 3,
            "Pipework, Drainage, Sanitary Fixtures",
            "Skilled plumber installing water, waste, and sanitary services on {Company} sites",
            "T3",
            "Install pipework and fixtures; conduct pressure tests; isolate leaks; comply with HSE rules",
            "Installation Output, Leak Rate, Test Pass Rate",
            21),
        new("ELEC-T-001", "Site Electrician", 2, 4_800m, 8_000m, "OPERATIONS", "FM-GEN-001", false,
            "Trade Certificate (NVTI Grade I/II) + ECG Permit", 3,
            "LV Wiring, Conduit, Termination, IEE Regs",
            "Skilled electrician installing LV wiring and fittings on {Company} sites",
            "T3",
            "Install conduits and wiring; terminate accessories; assist with testing; comply with electrical safety rules",
            "Installation Output, Test Pass Rate, Electrical Incident Rate",
            21),
        new("WLD-001", "Welder / Fabricator", 2, 4_800m, 8_000m, "OPERATIONS", "FM-GEN-001", false,
            "Trade Certificate (NVTI Grade I/II) + Welding Cert.", 3,
            "MIG/TIG/Arc Welding, Steel Fabrication, Cutting",
            "Skilled welder fabricating and welding steel on {Company} sites and yards",
            "T3",
            "Fabricate and weld steel members; cut to drawings; conduct visual checks; comply with hot-work permits",
            "Weld Pass Rate, Output, Hot-Work Permit Compliance",
            21),
        new("PNT-001", "Painter / Decorator", 1, 3_500m, 5_500m, "OPERATIONS", "FM-MAS-001", false,
            "Trade Certificate (NVTI Grade II/III)", 2,
            "Painting, Wallpaper, Surface Preparation",
            "Skilled painter applying paint and finishes on {Company} building projects",
            "T2",
            "Prepare surfaces; apply paint per spec; clean tools; comply with HSE rules",
            "Daily Output, Finish Quality, Paint Wastage",
            21),
        // ── Plant operators (Level 2) ─────────────────────────────────────────
        new("PE-EXC-001", "Excavator Operator", 2, 5_500m, 9_000m, "PLANT", "FM-GEN-001", false,
            "Heavy Plant Operator Licence + DVLA Class F", 4,
            "Excavator Operation, Earthworks, Plant Safety, Daily Checks",
            "Operates 20-50t excavators on {Company} earthworks and bulk excavation projects",
            "T4",
            "Operate excavator safely; conduct daily pre-start checks; record fuel and hours; flag mechanical issues",
            "Plant Availability, Output (m3/day), Safety Incidents, Fuel Efficiency",
            21),
        new("PE-LD-001", "Loader / Backhoe Operator", 2, 5_000m, 8_500m, "PLANT", "FM-GEN-001", false,
            "Heavy Plant Operator Licence", 3,
            "Loader Operation, Backhoe, Material Handling, Plant Safety",
            "Operates wheeled loaders and backhoes on {Company} sites and yards",
            "T4",
            "Load trucks; move materials; conduct daily checks; record fuel and hours; flag issues",
            "Plant Availability, Loading Cycles/Day, Safety Incidents",
            21),
        new("PE-CR-001", "Crane Operator", 2, 6_000m, 10_000m, "PLANT", "FM-GEN-001", false,
            "Mobile/Tower Crane Licence + Lift Plan training", 5,
            "Crane Operation, Lifting Plans, Slinging Awareness, Plant Safety",
            "Operates mobile and tower cranes for {Company} lifting operations",
            "T4",
            "Conduct lifts per lift plan; daily crane checks; coordinate with banksman/slingers; halt unsafe lifts",
            "Lift Completion, Lifting Incidents, Crane Availability",
            21),
        new("PE-RL-001", "Roller / Compactor Operator", 2, 4_800m, 8_000m, "PLANT", "FM-GEN-001", false,
            "Heavy Plant Operator Licence", 2,
            "Roller Operation, Compaction, Plant Safety",
            "Operates rollers and compactors on {Company} road and earthworks projects",
            "T3",
            "Compact materials per spec; daily plant checks; record passes and density readings; flag issues",
            "Compaction Density Pass Rate, Plant Availability, Output (m2/day)",
            21),
        // ── HSE & Quality (Level 1-3) ─────────────────────────────────────────
        new("HSE-OFF-001", "Safety Officer", 3, 9_000m, 14_000m, "HSE", "HSE-MGR-001", false,
            "OHS Diploma + NEBOSH IGC", 4,
            "Site Safety, Hazard Identification, Toolbox Talks, Incident Reporting",
            "Day-to-day safety presence on a {Company} site",
            "CON-5",
            "Conduct daily site walks; deliver toolbox talks; investigate near-misses; maintain HSE registers",
            "Site Audit Score, Near-Miss Reporting Rate, Incident Investigation Quality",
            24),
        new("HSE-INS-001", "Safety Inspector", 2, 6_000m, 9_500m, "HSE", "HSE-OFF-001", false,
            "OHS Certificate + IOSH Working Safely", 2,
            "Safety Inspections, PPE Compliance, Permit-to-Work, Reporting",
            "Performs routine safety inspections and PPE checks on {Company} sites",
            "CON-3",
            "Inspect work areas; verify PPE compliance; check permits; report unsafe acts to Safety Officer",
            "Inspection Closure Rate, Unsafe Act Reporting, PPE Compliance Score",
            21),
        new("LAB-001", "Materials Lab Technician", 2, 5_500m, 9_000m, "HSE", "HSE-MGR-001", false,
            "HND (Civil Eng./Lab Tech)", 2,
            "Concrete Cube Testing, Soil Testing, Aggregate Testing, ASTM/BS Methods",
            "Runs the on-site materials lab for {Company} projects, testing concrete, soils, and aggregates",
            "CON-3",
            "Conduct cube, slump, and soil tests; record results; calibrate equipment; flag failing materials",
            "Test Throughput, Test Result Accuracy, Calibration Compliance",
            21),
        // ── Procurement & Stores (Level 1-3) ──────────────────────────────────
        new("BUY-001", "Buyer", 3, 9_000m, 14_000m, "PROCUREMENT", "PROC-MGR-001", false,
            "Bachelor's Degree (Supply Chain / Business)", 3,
            "Purchasing, Supplier Negotiation, Public Procurement Act, ERP",
            "Day-to-day purchasing buyer for {Company} sites and head office",
            "CON-5",
            "Raise POs; chase deliveries; expedite materials; resolve invoice queries; maintain supplier records",
            "PO Cycle Time, OTIF, Invoice Match Rate, Supplier Score",
            24),
        new("STR-OFF-001", "Stores Officer", 2, 4_500m, 7_500m, "PROCUREMENT", "PROC-MGR-001", false,
            "HND (Stores / Logistics) + Inventory training", 2,
            "Inventory Control, GRN, Bin Cards, Material Issue, ERP",
            "Manages site stores receipt, issue, and stock control for {Company} sites",
            "CON-3",
            "Receive and inspect deliveries; raise GRNs; issue materials against requisitions; cycle-count stock; flag discrepancies",
            "Stock Accuracy, GRN Cycle Time, Stockout Frequency",
            21),
        new("LOG-001", "Logistics Officer", 2, 5_000m, 8_500m, "PROCUREMENT", "PROC-MGR-001", false,
            "HND / Bachelor's (Logistics)", 2,
            "Fleet Coordination, Customs Clearance, Inbound Logistics, GPS Tracking",
            "Coordinates inbound deliveries, customs clearance, and fleet movements for {Company}",
            "CON-3",
            "Plan inbound deliveries; clear customs on imports; track fleet; resolve transit issues",
            "On-Time Delivery, Customs Cycle Time, Fleet Utilisation",
            21),
        // ── Drivers & Site Support (Level 1-2) ────────────────────────────────
        new("DRV-H-001", "Heavy Truck Driver", 2, 4_500m, 7_500m, "PLANT", "FM-GEN-001", false,
            "DVLA Class E/F Licence", 3,
            "Heavy Vehicle Operation, Defensive Driving, Pre-Start Checks",
            "Drives tipper, lowbed, and heavy trucks for {Company} sites and yards",
            "T3",
            "Drive vehicle safely; conduct pre-start checks; deliver loads on time; record trips and fuel",
            "On-Time Delivery, Driving Incidents, Vehicle Availability",
            21),
        new("DRV-L-001", "Light Vehicle Driver", 1, 3_500m, 5_500m, "OPERATIONS", "FM-GEN-001", false,
            "DVLA Class B Licence", 1,
            "Light Vehicle Operation, Customer Service, Defensive Driving",
            "Drives company pickups and saloon cars for {Company} staff and material runs",
            "T2",
            "Drive staff and materials safely; maintain vehicle cleanliness; record trips and fuel; report defects",
            "Trip Compliance, Driving Incidents, Vehicle Care",
            21),
        new("SEC-001", "Security Guard", 1, 2_200m, 3_800m, "OPERATIONS", "FM-GEN-001", false,
            "Ministry of Interior Security Guard Permit", 1,
            "Site Security, Access Control, Patrols, Incident Reporting",
            "Provides perimeter security and access control at {Company} sites and yards",
            "T1",
            "Patrol perimeter; control access; log visitors and vehicles; report incidents; respond to alarms",
            "Patrol Compliance, Incident Response Time, Access Log Accuracy",
            21),
        new("CMP-001", "Camp Manager", 3, 9_000m, 14_000m, "HR", "HR-OFF-001", true,
            "HND / Bachelor's (Hospitality / Admin)", 4,
            "Camp Management, Catering Oversight, Welfare, Logistics",
            "Runs the residential workers' camp for {Company} remote project sites",
            "CON-5",
            "Oversee camp accommodation, catering, and welfare; manage camp staff; ensure hygiene and safety; resolve worker grievances",
            "Camp Satisfaction Score, Hygiene Audit Score, Welfare Incidents",
            24),
        new("DOC-001", "Document Controller", 2, 6_000m, 9_500m, "OPERATIONS", "PM-001", false,
            "HND / Bachelor's + EDMS training (Aconex/Asite)", 2,
            "EDMS, Drawing Register, RFI Tracking, Aconex, ISO 19650 Information Management",
            "Manages project document control on {Company} projects",
            "CON-3",
            "Maintain drawing and document registers; control revisions; manage incoming and outgoing transmittals; produce DC reports",
            "Register Accuracy, Transmittal Cycle Time, Revision Control",
            21),
        // ── Support functions (Level 1-3) ─────────────────────────────────────
        new("ACC-001", "Accountant", 3, 9_500m, 16_000m, "FINANCE", "MD-001", false,
            "Bachelor's Degree + ACCA / ICAG Part-Qualified", 4,
            "Project Accounting, IFRS, Sage / SAP, Cashflow, Tax, IPC Reconciliation",
            "Owns project and head-office accounting for {Company}",
            "CON-6",
            "Run monthly close; reconcile project ledgers; submit statutory tax; manage payroll; produce cashflow forecasts",
            "Close Cycle Time, Reconciliation Accuracy, Tax Compliance, Audit Findings",
            24),
        new("FIN-OFF-001", "Finance / Payroll Officer", 2, 5_500m, 9_000m, "FINANCE", "ACC-001", false,
            "HND / Bachelor's (Accounting)", 2,
            "Payroll, AP/AR, Excel, ERP, Tier 1 SSNIT, PAYE",
            "Runs payroll, AP, and AR for {Company}",
            "CON-3",
            "Process monthly payroll; pay suppliers; chase debtors; reconcile bank; submit SSNIT and PAYE returns",
            "Payroll Accuracy, Supplier Payment Cycle, Bank Reconciliation Cycle",
            21),
        new("HR-OFF-001", "HR Officer", 3, 9_000m, 14_000m, "HR", "MD-001", false,
            "Bachelor's Degree (HR / Business)", 3,
            "Recruitment, Industrial Relations, Labour Law, Payroll, Site Welfare",
            "Manages recruitment, IR, and welfare for {Company} head office and sites",
            "CON-5",
            "Recruit site and HQ staff; manage CBA/union relations; handle disciplinary cases; oversee training and welfare",
            "Time-to-Hire, Industrial Disputes, Training Coverage, Staff Turnover",
            24),
        new("IT-001", "IT Support Officer", 2, 5_500m, 9_000m, "HR", "HR-OFF-001", false,
            "HND / Bachelor's (IT / Computer Science)", 2,
            "Helpdesk Support, Networking, Microsoft 365, Site Connectivity, ERP Support",
            "Provides IT support for {Company} head office and remote project sites",
            "CON-3",
            "Resolve helpdesk tickets; support site connectivity; maintain laptops and printers; assist ERP users",
            "Ticket Resolution Time, Uptime, User Satisfaction",
            21),
        new("CLN-001", "Cleaner / Office Assistant", 1, 1_800m, 2_800m, "HR", "HR-OFF-001", false,
            "BECE / WASSCE", 0,
            "Cleaning, Janitorial, Office Support, Hospitality",
            "Maintains cleanliness and provides hospitality support at {Company} offices and camps",
            "T1",
            "Clean offices and camps; refill consumables; assist with hospitality; report maintenance issues",
            "Cleanliness Score, Reliability, Hospitality Feedback",
            21)
    ];

    // ~45 curated stations covering 1 HQ, 2 regional offices, 25 active project sites
    // (Eastern Corridor, Tema Motorway, Sekondi Naval Base, Pokuase Interchange etc.),
    // 10 plant / equipment yards, and ~7 quarries / asphalt / batching plants. Phones
    // and addresses are realistic for a tier-1 Ghana civils contractor; emails store
    // ONLY the local part — the row factory appends the actual company TLD at runtime.
    private static readonly StationSpec[] _constructionStations =
    [
        new("HO-001", "Head Office - Accra (Spintex)", "Head Office", "Greater Accra", "Accra", "Plot 17, Spintex Road, Baatsona", 80, 250,
            "{Company} corporate headquarters housing executive, engineering, commercial, finance, and HR functions",
            "+233 30 222 4100", "headoffice"),
        // ── Regional offices ─────────────────────────────────────────────────
        new("RO-ASH-001", "Ashanti Regional Office - Kumasi", "Regional Office", "Ashanti", "Kumasi", "Harper Road, Adum, Kumasi", 30, 80,
            "{Company} Ashanti regional office coordinating road and building projects across Ashanti, Bono, and Ahafo",
            "+233 32 202 4100", "ashanti.region"),
        new("RO-WES-001", "Western Regional Office - Takoradi", "Regional Office", "Western", "Takoradi", "Harbour Road, Market Circle, Takoradi", 25, 70,
            "{Company} Western regional office overseeing port, oil & gas, and Western Region civil works",
            "+233 31 202 4100", "western.region"),
        // ── Active project sites — Roads, bridges, interchanges ──────────────
        new("PRJ-ECR-001", "Eastern Corridor Road Project Site - Asikuma", "Project Site", "Volta", "Asikuma", "Asikuma-Have Section, Eastern Corridor Road", 80, 280,
            "{Company} site office for the Eastern Corridor Road bituminous reconstruction (Asikuma-Have lot)",
            "+233 30 222 4201", "easterncorridor"),
        new("PRJ-ECR-002", "Eastern Corridor Road Project Site - Nkwanta", "Project Site", "Oti", "Nkwanta", "Dambai-Nkwanta Section, Eastern Corridor Road", 70, 240,
            "{Company} site office for the Dambai-Nkwanta segment of the Eastern Corridor reconstruction programme",
            "+233 30 222 4202", "easterncorridor.nkwanta"),
        new("PRJ-TMR-001", "Tema Motorway Roundabout Upgrade Site", "Project Site", "Greater Accra", "Tema", "Tema Motorway Roundabout, Tema", 90, 260,
            "{Company} site office for the Tema Motorway Roundabout interchange and flyover upgrade",
            "+233 30 322 4201", "temamotorway"),
        new("PRJ-PKI-001", "Pokuase Interchange Site Office", "Project Site", "Greater Accra", "Pokuase", "Pokuase ACP Junction, Pokuase", 80, 220,
            "{Company} site office for the Pokuase 4-tier interchange and access road project",
            "+233 30 222 4203", "pokuase"),
        new("PRJ-OBT-001", "Obetsebi-Lamptey Interchange Site Office", "Project Site", "Greater Accra", "Accra", "Obetsebi-Lamptey Circle, Accra", 70, 200,
            "{Company} site office for the Obetsebi-Lamptey Circle interchange phase 2 works",
            "+233 30 222 4204", "obetsebi"),
        new("PRJ-KLR-001", "Kumasi Lake Road Rehabilitation Site", "Project Site", "Ashanti", "Kumasi", "Lake Road, Asawasi-Anloga, Kumasi", 60, 180,
            "{Company} site office for the Kumasi Lake Road dualisation and bridge rehabilitation project",
            "+233 32 202 4201", "kumasilakeroad"),
        new("PRJ-AKR-001", "Accra-Kumasi Road Phase II Site - Nkawkaw", "Project Site", "Eastern", "Nkawkaw", "Accra-Kumasi Highway, Nkawkaw", 70, 220,
            "{Company} site office for the Accra-Kumasi N6 dualisation phase II between Nkawkaw and Konongo",
            "+233 34 202 4201", "akr.nkawkaw"),
        new("PRJ-CCH-001", "Cape Coast-Takoradi Road Rehabilitation Site", "Project Site", "Central", "Cape Coast", "N1 Highway, Cape Coast-Mankessim", 60, 200,
            "{Company} site office for the Cape Coast-Takoradi N1 highway rehabilitation works",
            "+233 33 202 4201", "ccr.capecoast"),
        new("PRJ-TKR-001", "Tamale Outer Ring Road Site Office", "Project Site", "Northern", "Tamale", "Tamale Outer Ring Road, Lamashegu", 60, 180,
            "{Company} site office for the Tamale Outer Ring Road dualisation project",
            "+233 37 202 4201", "tamale.ringroad"),
        new("PRJ-VLB-001", "Volta Lake Bridge Project Site - Kete-Krachi", "Project Site", "Oti", "Kete-Krachi", "Kete-Krachi to Bumbila Crossing, Volta Lake", 70, 200,
            "{Company} site office for the Volta Lake Bridge project at Kete-Krachi",
            "+233 30 222 4205", "vlb.ketekrachi"),
        new("PRJ-AYI-001", "Ayisa River Bridge Site Office", "Project Site", "Central", "Winneba", "Ayisa River Crossing, Winneba", 35, 90,
            "{Company} site office for the Ayisa River bridge replacement on the Winneba-Mankessim road",
            "+233 33 202 4202", "ayisa"),
        // ── Active project sites — Buildings, civil works ────────────────────
        new("PRJ-SNB-001", "Sekondi Naval Base Project Site", "Project Site", "Western", "Sekondi", "Naval Base Road, Sekondi", 80, 260,
            "{Company} site office for the Sekondi Naval Base infrastructure expansion (jetty, barracks, support buildings)",
            "+233 31 202 4201", "sekondi.naval"),
        new("PRJ-AIA-001", "Kotoka Airport Terminal 3 Site Office", "Project Site", "Greater Accra", "Accra", "Kotoka International Airport, Airport City", 80, 240,
            "{Company} site office for the Kotoka International Airport Terminal 3 finishings and apron extension",
            "+233 30 222 4206", "kia.t3"),
        new("PRJ-UCC-001", "University of Ghana Medical Centre Phase II Site", "Project Site", "Greater Accra", "Accra", "Legon Boundary Road, Legon, Accra", 60, 180,
            "{Company} site office for the UGMC Phase II teaching hospital construction at Legon",
            "+233 30 222 4207", "ugmc"),
        new("PRJ-KAT-001", "Komfo Anokye Teaching Hospital Site", "Project Site", "Ashanti", "Kumasi", "Bantama High Street, Kumasi", 50, 150,
            "{Company} site office for the Komfo Anokye Teaching Hospital maternity block extension",
            "+233 32 202 4202", "kath"),
        new("PRJ-NBO-001", "National Bank of Ghana Towers Site - Accra", "Project Site", "Greater Accra", "Accra", "Independence Avenue, Ridge", 50, 140,
            "{Company} site office for the new commercial tower fit-out and superstructure on Independence Avenue",
            "+233 30 222 4208", "ngtowers"),
        new("PRJ-MIA-001", "Ministries Block Refurbishment Site - Accra", "Project Site", "Greater Accra", "Accra", "Ministries Enclave, Accra", 40, 110,
            "{Company} site office for the Ministries enclave refurbishment and structural upgrade",
            "+233 30 222 4209", "ministries"),
        new("PRJ-TMP-001", "Tema Port Container Terminal 3 Site", "Project Site", "Greater Accra", "Tema", "MPS Terminal 3, Tema Port", 80, 240,
            "{Company} site office for the Tema Port MPS Terminal 3 civil works expansion",
            "+233 30 322 4202", "tema.port"),
        new("PRJ-TKP-001", "Takoradi Port Expansion Site", "Project Site", "Western", "Takoradi", "Takoradi Port Berth Extension Area", 70, 220,
            "{Company} site office for the Takoradi Port berth dredging and quay civil works",
            "+233 31 202 4202", "takoradi.port"),
        new("PRJ-TGD-001", "Tarkwa Goldfields Camp Project Site", "Project Site", "Western", "Tarkwa", "Goldfields Concession, Tarkwa", 60, 180,
            "{Company} site office for the Tarkwa Goldfields process plant extension and camp civils",
            "+233 31 202 4203", "tarkwa.gold"),
        new("PRJ-OBM-001", "Obuasi Mine Civils Site Office", "Project Site", "Ashanti", "Obuasi", "AngloGold Ashanti Mine, Obuasi", 50, 150,
            "{Company} site office for AngloGold Ashanti Obuasi underground access civils and surface support",
            "+233 32 209 4201", "obuasi.mine"),
        new("PRJ-KSI-001", "Kumasi International Airport Expansion Site", "Project Site", "Ashanti", "Kumasi", "Kumasi International Airport, Boadi", 60, 180,
            "{Company} site office for the Kumasi International Airport runway and terminal expansion",
            "+233 32 202 4203", "ksi.airport"),
        new("PRJ-WAA-001", "Wa Affordable Housing Project Site", "Project Site", "Upper West", "Wa", "Kpaguri Sector, Wa", 35, 100,
            "{Company} site office for the Wa Government Affordable Housing project (350 units)",
            "+233 39 202 4201", "wa.housing"),
        new("PRJ-SUH-001", "Sunyani Affordable Housing Project Site", "Project Site", "Bono", "Sunyani", "Penkwase Sector, Sunyani", 30, 90,
            "{Company} site office for the Sunyani Government Affordable Housing project (250 units)",
            "+233 35 202 4201", "sunyani.housing"),
        new("PRJ-KNW-001", "Koforidua New Town Civil Works Site", "Project Site", "Eastern", "Koforidua", "Asokore Sector, Koforidua", 40, 110,
            "{Company} site office for Koforidua New Town drainage and access road civil works",
            "+233 34 202 4202", "koforidua.newtown"),
        // ── Plant yards / equipment yards (10) ───────────────────────────────
        new("YRD-TEM-001", "Tema Industrial Plant Yard", "Plant Yard", "Greater Accra", "Tema", "Heavy Industrial Area, Tema Community 1", 25, 80,
            "{Company} central plant yard housing the heavy fleet, workshop, and fuel bay for Greater Accra projects",
            "+233 30 322 4301", "tema.yard"),
        new("YRD-ACC-001", "Accra Spintex Yard", "Plant Yard", "Greater Accra", "Accra", "Spintex Industrial Estate, Accra", 20, 60,
            "{Company} secondary equipment yard supporting Accra metro projects with light plant and consumables",
            "+233 30 222 4301", "spintex.yard"),
        new("YRD-KSI-001", "Kumasi Plant Yard", "Plant Yard", "Ashanti", "Kumasi", "Suame Industrial Area, Kumasi", 20, 60,
            "{Company} Kumasi plant yard with workshop and stores serving Ashanti and northern projects",
            "+233 32 202 4301", "kumasi.yard"),
        new("YRD-TKD-001", "Takoradi Plant Yard", "Equipment Yard", "Western", "Takoradi", "Industrial Estate, Takoradi", 15, 45,
            "{Company} Takoradi yard supporting Western Region road, mining, and oil & gas projects",
            "+233 31 202 4301", "takoradi.yard"),
        new("YRD-TML-001", "Tamale Plant Yard", "Equipment Yard", "Northern", "Tamale", "Industrial Layout, Lamashegu, Tamale", 15, 40,
            "{Company} Tamale plant yard supporting Northern, North East, and Savannah projects",
            "+233 37 202 4301", "tamale.yard"),
        new("YRD-TKR-001", "Tarkwa Plant Yard", "Equipment Yard", "Western", "Tarkwa", "Tarkwa Industrial Area", 12, 35,
            "{Company} Tarkwa yard supporting mining-area civil works and goldfields projects",
            "+233 31 202 4302", "tarkwa.yard"),
        new("YRD-HO-001", "Ho Equipment Yard", "Equipment Yard", "Volta", "Ho", "Industrial Estate, Ho", 10, 30,
            "{Company} Ho equipment yard supporting Volta and Oti regional road and bridge projects",
            "+233 36 202 4301", "ho.yard"),
        new("YRD-CCH-001", "Cape Coast Equipment Yard", "Equipment Yard", "Central", "Cape Coast", "Industrial Estate, Cape Coast", 10, 30,
            "{Company} Cape Coast yard supporting Central Region civils and N1 highway works",
            "+233 33 202 4301", "capecoast.yard"),
        new("YRD-WA-001", "Wa Equipment Yard", "Equipment Yard", "Upper West", "Wa", "Industrial Layout, Wa", 8, 25,
            "{Company} Wa equipment yard supporting Upper West and Upper East projects",
            "+233 39 202 4301", "wa.yard"),
        new("YRD-SUN-001", "Sunyani Equipment Yard", "Equipment Yard", "Bono", "Sunyani", "Industrial Layout, Sunyani", 10, 28,
            "{Company} Sunyani equipment yard supporting Bono, Bono East, and Ahafo road and housing projects",
            "+233 35 202 4301", "sunyani.yard"),
        // ── Quarries, asphalt plants, batching plants (~7) ───────────────────
        new("QRY-SHA-001", "Shai Hills Quarry", "Quarry", "Greater Accra", "Doryumu", "Shai Hills Range, Doryumu", 25, 70,
            "{Company} aggregate quarry producing crushed stone for Greater Accra and Eastern Corridor projects",
            "+233 30 222 4401", "shai.quarry"),
        new("QRY-NSU-001", "Nsuta Quarry", "Quarry", "Western", "Nsuta", "Nsuta-Tarkwa Road, Nsuta", 20, 55,
            "{Company} Nsuta quarry feeding Western Region road and port projects with limestone aggregate",
            "+233 31 202 4401", "nsuta.quarry"),
        new("QRY-EJI-001", "Ejisu Quarry", "Quarry", "Ashanti", "Ejisu", "Ejisu-Juaben Road, Ejisu", 18, 50,
            "{Company} Ejisu granite quarry serving Kumasi metro and Ashanti regional projects",
            "+233 32 202 4401", "ejisu.quarry"),
        new("APL-TEM-001", "Tema Asphalt Plant", "Asphalt Plant", "Greater Accra", "Tema", "Heavy Industrial Area, Tema Community 1", 20, 50,
            "{Company} Tema asphalt mixing plant producing hot-mix bitumen for Greater Accra and Tema Motorway works",
            "+233 30 322 4401", "tema.asphalt"),
        new("APL-KSI-001", "Kumasi Asphalt Plant", "Asphalt Plant", "Ashanti", "Kumasi", "Asokwa Industrial Area, Kumasi", 18, 45,
            "{Company} Kumasi asphalt plant feeding Ashanti, Bono, and Eastern Corridor road projects",
            "+233 32 202 4402", "kumasi.asphalt"),
        new("BTP-ACC-001", "Accra Concrete Batching Plant - Spintex", "Batching Plant", "Greater Accra", "Accra", "Spintex Industrial Estate, Accra", 15, 40,
            "{Company} ready-mix concrete batching plant supplying Accra metro building and civil projects",
            "+233 30 222 4402", "accra.batching"),
        new("BTP-TKD-001", "Takoradi Concrete Batching Plant", "Batching Plant", "Western", "Takoradi", "Industrial Estate, Takoradi", 12, 35,
            "{Company} Takoradi ready-mix batching plant supplying Western Region port, mine, and road projects",
            "+233 31 202 4402", "takoradi.batching")
    ];
}
