using QimErp.Shared.DemoData.Ghana;

namespace QimErp.Shared.DemoData.Industry.Profiles;

public sealed class EducationIndustryProfile : IIndustryProfile
{
    public string Code => "EDUCATION";
    public string DisplayName => "Education & Training";

    public IReadOnlyList<string> SampleCompanyNames =>
    [
        "University of Ghana", "KNUST", "University of Cape Coast", "GIMPA",
        "Ashesi University", "Lancaster University Ghana", "Central University",
        "Webster University Ghana", "University of Professional Studies",
        "Ghana Institute of Languages", "African University College of Communications",
        "Wisconsin International University"
    ];

    public OrgHierarchySpec BuildOrgHierarchy(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        var (units, distribution) = tier switch
        {
            CompanyTier.Startup    => (StartupUnits,    StartupDistribution),
            CompanyTier.SME        => (SmeUnits,        SmeDistribution),
            CompanyTier.Corporate  => (CorporateUnits,  CorporateDistribution),
            CompanyTier.NonProfit  => (NonProfitUnits,  NonProfitDistribution),
            _                      => (SmeUnits,        SmeDistribution)
        };
        return OrgHierarchyBuilder.Build(units, distribution, targetEmployees, randomSeed);
    }

    public IReadOnlyList<JobTitleSpec> JobTitles => _jobTitles;

    public StationLayout BuildStations(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        // Corporate tier uses the curated 35-station university campus catalogue —
        // main campus + faculty buildings + halls of residence + library + sports
        // complex + satellite campuses + distance-learning centres + affiliated
        // schools. Other tiers fall back to the procedural city-pool builder.
        if (tier == CompanyTier.Corporate)
        {
            var hqRow = _educationStations[0];
            var rest = _educationStations.Skip(1).ToList();
            var branchTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Faculty Building", "Satellite Campus"
            };
            return new StationLayout(
                Headquarters: hqRow,
                Branches: rest.Where(s => branchTypes.Contains(s.StationType)).ToList(),
                Satellites: rest.Where(s => !branchTypes.Contains(s.StationType)).ToList());
        }

        var rng = new Random(randomSeed);
        var hq = new StationSpec(
            Code: "HQ",
            Name: "Main Campus",
            StationType: "Campus",
            Region: "Greater Accra",
            City: "Accra",
            Address: "Legon, Accra",
            CapacityMin: 60,
            CapacityMax: tier == CompanyTier.Corporate ? 1200 : 350);

        var campusCount = tier switch
        {
            CompanyTier.Startup   => 0,
            CompanyTier.SME       => Math.Max(1, targetEmployees / 250),
            CompanyTier.Corporate => Math.Max(2, Math.Min(8, targetEmployees / 200)),
            CompanyTier.NonProfit => 1,
            _                     => 2
        };

        var campuses = new List<StationSpec>(campusCount);
        for (var i = 0; i < campusCount; i++)
        {
            var region = GhanaGeography.Regions[rng.Next(GhanaGeography.Regions.Count)];
            var cities = GhanaGeography.CitiesByRegion[region];
            var city = cities[rng.Next(cities.Count)];
            campuses.Add(new StationSpec(
                Code: $"CAMP{i + 1:D2}",
                Name: $"{city} Campus",
                StationType: "Campus",
                Region: region,
                City: city,
                Address: $"University Road, {city}",
                CapacityMin: 25,
                CapacityMax: 250));
        }

        var centreCount = campusCount * 2;
        var centres = new List<StationSpec>(centreCount);
        for (var i = 0; i < centreCount; i++)
        {
            var region = GhanaGeography.Regions[rng.Next(GhanaGeography.Regions.Count)];
            var cities = GhanaGeography.CitiesByRegion[region];
            var city = cities[rng.Next(cities.Count)];
            centres.Add(new StationSpec(
                Code: $"LC{i + 1:D3}",
                Name: $"{city} Learning Centre",
                StationType: "Learning Centre",
                Region: region,
                City: city,
                Address: $"{GhanaGeography.Streets[rng.Next(GhanaGeography.Streets.Count)]}, {city}",
                CapacityMin: 3,
                CapacityMax: 20));
        }

        return new StationLayout(hq, campuses, centres);
    }

    public EmployeeDistributionSpec EmployeeDistribution => new(
        ByRankLevel: new Dictionary<int, double>
        {
            [5] = 0.010,
            [4] = 0.060,
            [3] = 0.350,
            [2] = 0.430,
            [1] = 0.150
        },
        ByOrgUnitCode: null);

    public SalaryBandSpec SalaryBands => new(
        ByRankLevel: new Dictionary<int, (decimal Min, decimal Max)>
        {
            [5] = (6_500m, 14_000m),
            [4] = (4_000m,  9_500m),
            [3] = (3_000m,  9_000m),
            [2] = (2_000m,  4_500m),
            [1] = (1_500m,  3_000m)
        });

    private static readonly IReadOnlyList<string> AcademicJobs   = ["ACAD_DIR", "SENIOR_LECTURER", "HOD", "LECTURER", "TEACHER", "ASSIST_TEACHER", "TA"];
    private static readonly IReadOnlyList<string> AdminJobs      = ["ADMIN", "ADMIN_OFFICER", "ADMIN_ASSIST", "INTERN"];
    private static readonly IReadOnlyList<string> StudentJobs    = ["STUDENT_MGR", "STUDENT_OFFICER", "STUDENT_ASSIST"];
    private static readonly IReadOnlyList<string> SupportJobs    = ["LIBRARIAN", "LIBRARY_ASSIST"];
    private static readonly IReadOnlyList<string> ItJobs         = ["IT_OFFICER"];
    private static readonly IReadOnlyList<string> FinanceJobs    = [];
    private static readonly IReadOnlyList<string> HrJobs         = [];
    private static readonly IReadOnlyList<string> ExecJobs       = ["PRINCIPAL", "VP"];
    private static readonly IReadOnlyList<string> ProgramsJobs   = ["LECTURER", "TEACHER"];

    // Corporate-tier richer eligibility lists — group academic/admin codes by faculty
    // and central function so the org hierarchy emits believable rosters per unit.
    private static readonly IReadOnlyList<string> ExecCorpJobs        = ["VC-001", "PVC-001", "PVC-002", "PROVOST-001"];
    private static readonly IReadOnlyList<string> AcadAffairsJobs     = ["PROVOST-001", "CURR-001", "PROG-001", "PROF-001", "ASSOC-001"];
    private static readonly IReadOnlyList<string> FacEngineeringJobs  = ["DEAN-ENG", "HOD-001", "PROF-001", "ASSOC-001", "SLECT-001", "LECT-001", "ALECT-001", "TUTOR-001", "RA-001", "DEMO-001"];
    private static readonly IReadOnlyList<string> FacBusinessJobs     = ["DEAN-BUS", "HOD-001", "PROF-001", "ASSOC-001", "SLECT-001", "LECT-001", "ALECT-001", "TUTOR-001", "RA-001"];
    private static readonly IReadOnlyList<string> FacSciencesJobs     = ["DEAN-SCI", "HOD-001", "PROF-001", "ASSOC-001", "SLECT-001", "LECT-001", "ALECT-001", "TUTOR-001", "POSTDOC-001", "DEMO-001"];
    private static readonly IReadOnlyList<string> FacHumanitiesJobs   = ["DEAN-HUM", "DEAN-EDU", "DEAN-LAW", "HOD-001", "PROF-001", "ASSOC-001", "SLECT-001", "LECT-001", "ALECT-001", "TUTOR-001"];
    private static readonly IReadOnlyList<string> FacHealthJobs       = ["DEAN-HEA", "HOD-001", "PROF-001", "ASSOC-001", "SLECT-001", "LECT-001", "POSTDOC-001", "DEMO-001"];
    private static readonly IReadOnlyList<string> ResearchJobs        = ["RFEL-001", "POSTDOC-001", "RA-001", "ASSOC-001", "PROF-001"];
    private static readonly IReadOnlyList<string> RegistryJobs        = ["REG-001", "DREG-001", "SAR-ADM", "SAR-EXM", "SAR-AAR", "SAR-REC", "ADMOFF-001", "EXMOFF-001", "RECOFF-001"];
    private static readonly IReadOnlyList<string> StudAffJobs         = ["DSA-001", "STUOFF-001", "COUN-001", "HALLT-001", "HALLM-001", "SPORT-001", "HEALTH-001"];
    private static readonly IReadOnlyList<string> FinanceCorpJobs     = ["DFIN-001", "BURS-001", "SACC-001", "ACCT-001", "AUD-001"];
    private static readonly IReadOnlyList<string> HrCorpJobs          = ["DHR-001", "HRO-001"];
    private static readonly IReadOnlyList<string> IctCorpJobs         = ["DICT-001", "NETENG-001", "ICTSUP-001"];
    private static readonly IReadOnlyList<string> EstatesJobs         = ["DEST-001", "ESTOFF-001", "SECOFF-001", "DRV-001", "CLN-001", "CATER-001"];
    private static readonly IReadOnlyList<string> LibraryJobs         = ["LIBR-001", "LIBA-001", "ARCH-001"];
    private static readonly IReadOnlyList<string> ProcurementJobs     = ["PROC-001", "STOR-001", "PUB-001"];

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> StartupUnits =
    [
        new("FOUNDER",  "Founder/Director", null,      OrgUnitKind.Executive, ExecJobs),
        new("ACADEMIC", "Academic",         "FOUNDER", OrgUnitKind.Function,  AcademicJobs),
        new("ADMIN",    "Administration",   "FOUNDER", OrgUnitKind.Function,  AdminJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> StartupDistribution = new Dictionary<string, double>
    {
        ["FOUNDER"]  = 0.15,
        ["ACADEMIC"] = 0.60,
        ["ADMIN"]    = 0.25
    };

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> SmeUnits =
    [
        new("EXEC",     "Executive",       null,   OrgUnitKind.Executive, ExecJobs),
        new("ACADEMIC", "Academic",        "EXEC", OrgUnitKind.Function,  AcademicJobs),
        new("ADMIN",    "Administration",  "EXEC", OrgUnitKind.Function,  AdminJobs),
        new("SUPPORT",  "Support Services","EXEC", OrgUnitKind.Function,  SupportJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> SmeDistribution = new Dictionary<string, double>
    {
        ["EXEC"]     = 0.08,
        ["ACADEMIC"] = 0.55,
        ["ADMIN"]    = 0.22,
        ["SUPPORT"]  = 0.15
    };

    // Corporate-tier baseline OrgUnits — each carries rich Description / Budget /
    // CostCenter / Purpose / Phone / Email-local-part for a Ghana research-intensive
    // university (think University of Ghana / KNUST / Ashesi). The {Company}
    // placeholder gets substituted at row-emit time so the same catalogue reads
    // naturally for any tertiary tenant. Budgets are GHS-scaled for a public
    // university council with an annual NCTE-approved subvention.
    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> CorporateUnits =
    [
        new("EXEC", "Office of the Vice Chancellor", null, OrgUnitKind.Executive, ExecCorpJobs,
            Description: "Office of the Vice Chancellor and Provost — top executive leadership of {Company}",
            BudgetMin: 1_500_000m, BudgetMax: 4_500_000m,
            CostCenter: "CC-EXEC-001",
            Purpose: "Set and execute {Company} strategy; lead the academic board; manage NCTE, GTEC and University Council relationships",
            Phone: "+233 30 222 3000", Email: "vc"),
        new("ACADEMIC-AFFAIRS", "Academic Affairs", "EXEC", OrgUnitKind.Function, AcadAffairsJobs,
            Description: "Oversees teaching, learning, curriculum, and academic standards across all faculties of {Company}",
            BudgetMin: 1_500_000m, BudgetMax: 5_000_000m,
            CostCenter: "CC-ACAD-001",
            Purpose: "Sustain academic excellence, accreditation, and student outcomes at {Company}",
            Phone: "+233 30 222 3010", Email: "academic"),
        new("FACULTY-OF-ENGINEERING", "Faculty of Engineering", "EXEC", OrgUnitKind.Function, FacEngineeringJobs,
            Description: "Civil, Electrical, Mechanical, Computer and Biomedical Engineering programmes of {Company}",
            BudgetMin: 2_000_000m, BudgetMax: 5_000_000m,
            CostCenter: "CC-ENG-001",
            Purpose: "Train Ghana's next generation of engineers; deliver applied research with industry partners",
            Phone: "+233 30 222 3110", Email: "engineering"),
        new("FACULTY-OF-BUSINESS", "Faculty of Business & Management", "EXEC", OrgUnitKind.Function, FacBusinessJobs,
            Description: "Accounting, Finance, Marketing, Management, Entrepreneurship and MBA programmes of {Company}",
            BudgetMin: 1_500_000m, BudgetMax: 4_000_000m,
            CostCenter: "CC-BUS-001",
            Purpose: "Develop business leaders and entrepreneurs for the Ghanaian and African economy",
            Phone: "+233 30 222 3120", Email: "business"),
        new("FACULTY-OF-SCIENCES", "Faculty of Sciences", "EXEC", OrgUnitKind.Function, FacSciencesJobs,
            Description: "Mathematics, Physics, Chemistry, Biology, Computer Science and Earth Sciences programmes of {Company}",
            BudgetMin: 1_800_000m, BudgetMax: 4_500_000m,
            CostCenter: "CC-SCI-001",
            Purpose: "Advance fundamental and applied scientific knowledge; supply STEM graduates for industry and academia",
            Phone: "+233 30 222 3130", Email: "sciences"),
        new("FACULTY-OF-HUMANITIES", "Faculty of Arts, Humanities & Law", "EXEC", OrgUnitKind.Function, FacHumanitiesJobs,
            Description: "Languages, History, Philosophy, Social Sciences, Education and Law programmes of {Company}",
            BudgetMin: 1_200_000m, BudgetMax: 3_500_000m,
            CostCenter: "CC-HUM-001",
            Purpose: "Cultivate critical thinking, cultural literacy and legal scholarship across {Company}'s liberal arts programmes",
            Phone: "+233 30 222 3140", Email: "humanities"),
        new("RESEARCH-INNOVATION", "Research, Innovation & Postgraduate Studies", "EXEC", OrgUnitKind.Function, ResearchJobs,
            Description: "Research grants, postgraduate school, innovation hub and technology transfer arm of {Company}",
            BudgetMin: 1_000_000m, BudgetMax: 3_000_000m,
            CostCenter: "CC-RES-001",
            Purpose: "Grow {Company}'s research output, grant income, and pipeline of innovations from lab to market",
            Phone: "+233 30 222 3150", Email: "research"),
        new("REGISTRY", "Registry & Records", "EXEC", OrgUnitKind.Function, RegistryJobs,
            Description: "Admissions, examinations, academic records, and central registry administration for {Company}",
            BudgetMin: 600_000m, BudgetMax: 1_500_000m,
            CostCenter: "CC-REG-001",
            Purpose: "Maintain accurate student records and run efficient admissions and examinations cycles for {Company}",
            Phone: "+233 30 222 3200", Email: "registry"),
        new("STUDENT-AFFAIRS", "Dean of Students & Student Affairs", "EXEC", OrgUnitKind.Function, StudAffJobs,
            Description: "Halls of residence, counselling, sports, health services, and student welfare across {Company}",
            BudgetMin: 500_000m, BudgetMax: 1_200_000m,
            CostCenter: "CC-DSA-001",
            Purpose: "Support {Company} students' wellbeing, residential life, and extracurricular development",
            Phone: "+233 30 222 3300", Email: "studentaffairs"),
        new("FINANCE-BURSARY", "Finance & Bursary", "EXEC", OrgUnitKind.Function, FinanceCorpJobs,
            Description: "Treasury, fees collection, payroll, financial reporting, and internal audit for {Company}",
            BudgetMin: 600_000m, BudgetMax: 1_500_000m,
            CostCenter: "CC-FIN-001",
            Purpose: "Steward {Company} finances; deliver clean audit opinions; ensure timely fees collection and payroll",
            Phone: "+233 30 222 3400", Email: "finance"),
        new("HR", "Human Resources", "EXEC", OrgUnitKind.Function, HrCorpJobs,
            Description: "Faculty hiring, staff development, total rewards, and labour relations for {Company}",
            BudgetMin: 400_000m, BudgetMax: 1_000_000m,
            CostCenter: "CC-HR-001",
            Purpose: "Attract, develop and retain the academic and admin talent {Company} needs to deliver its strategy",
            Phone: "+233 30 222 3500", Email: "hr"),
        new("ICT", "ICT & Digital Services", "EXEC", OrgUnitKind.Function, IctCorpJobs,
            Description: "Campus network, learning management system, student portal and cybersecurity for {Company}",
            BudgetMin: 500_000m, BudgetMax: 1_200_000m,
            CostCenter: "CC-ICT-001",
            Purpose: "Run reliable digital infrastructure for teaching, learning and administration at {Company}",
            Phone: "+233 30 222 3600", Email: "ict"),
        new("ESTATES-FACILITIES", "Estates & Facilities", "EXEC", OrgUnitKind.Function, EstatesJobs,
            Description: "Buildings, grounds, transport, security, catering and maintenance across {Company} campuses",
            BudgetMin: 600_000m, BudgetMax: 1_400_000m,
            CostCenter: "CC-EST-001",
            Purpose: "Keep {Company} campuses safe, clean, well-maintained and ready for teaching and research",
            Phone: "+233 30 222 3700", Email: "estates"),
        new("LIBRARY", "University Library", "EXEC", OrgUnitKind.Function, LibraryJobs,
            Description: "Main library, faculty branch libraries, e-resources and archives of {Company}",
            BudgetMin: 300_000m, BudgetMax: 900_000m,
            CostCenter: "CC-LIB-001",
            Purpose: "Provide curated information resources and study spaces for {Company} students and researchers",
            Phone: "+233 30 222 3800", Email: "library"),
        new("PROCUREMENT", "Procurement & Stores", "EXEC", OrgUnitKind.Function, ProcurementJobs,
            Description: "Procurement planning, tender management, stores and public affairs for {Company}",
            BudgetMin: 250_000m, BudgetMax: 700_000m,
            CostCenter: "CC-PRO-001",
            Purpose: "Run compliant PPA-aligned procurement and reliable stores for {Company} operations",
            Phone: "+233 30 222 3900", Email: "procurement")
    ];

    private static readonly IReadOnlyDictionary<string, double> CorporateDistribution = new Dictionary<string, double>
    {
        ["EXEC"]                    = 0.02,
        ["ACADEMIC-AFFAIRS"]        = 0.04,
        ["FACULTY-OF-ENGINEERING"]  = 0.13,
        ["FACULTY-OF-BUSINESS"]     = 0.11,
        ["FACULTY-OF-SCIENCES"]     = 0.13,
        ["FACULTY-OF-HUMANITIES"]   = 0.10,
        ["RESEARCH-INNOVATION"]     = 0.06,
        ["REGISTRY"]                = 0.07,
        ["STUDENT-AFFAIRS"]         = 0.08,
        ["FINANCE-BURSARY"]         = 0.05,
        ["HR"]                      = 0.03,
        ["ICT"]                     = 0.05,
        ["ESTATES-FACILITIES"]      = 0.08,
        ["LIBRARY"]                 = 0.03,
        ["PROCUREMENT"]             = 0.02
    };

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> NonProfitUnits =
    [
        new("EXEC",     "Executive",       null,   OrgUnitKind.Executive, ExecJobs),
        new("ACADEMIC", "Academic",        "EXEC", OrgUnitKind.Function,  AcademicJobs),
        new("PROGRAMS", "Programs",        "EXEC", OrgUnitKind.Function,  ProgramsJobs),
        new("ADMIN",    "Administration",  "EXEC", OrgUnitKind.Function,  AdminJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> NonProfitDistribution = new Dictionary<string, double>
    {
        ["EXEC"]     = 0.10,
        ["ACADEMIC"] = 0.50,
        ["PROGRAMS"] = 0.25,
        ["ADMIN"]    = 0.15
    };

    // Curated 35-station catalogue for a Ghana research-intensive university:
    // 1 Main Campus (Legon HQ) + 6 Faculty Buildings + 5 Halls of Residence +
    // 2 Library complex + 1 Sports Complex + 6 Satellite/Distance Learning
    // Centres + 14 affiliated basic / SHS schools (multi-tier group). Codes,
    // names, addresses follow the Ghanaian higher-education vernacular.
    private static readonly IReadOnlyList<StationSpec> _educationStations =
    [
        new("HQ-001", "Main Campus", "Campus", "Greater Accra", "Accra", "University Avenue, Legon, Accra",
            CapacityMin: 600, CapacityMax: 4_500,
            Description: "Flagship campus of {Company} housing the Vice Chancellor's office, central administration and senior academic block",
            Phone: "+233 30 222 3000", Email: "info"),

        // ── Faculty Buildings (6) ────────────────────────────────────────────
        new("FB-ENG", "Faculty of Engineering Building", "Faculty Building", "Greater Accra", "Accra", "Engineering Block, Legon, Accra",
            CapacityMin: 80, CapacityMax: 350,
            Description: "Houses civil, electrical, mechanical and computer engineering departments of {Company}",
            Phone: "+233 30 222 3110", Email: "engineering"),
        new("FB-BUS", "Faculty of Business & Management Building", "Faculty Building", "Greater Accra", "Accra", "Business School Block, Legon, Accra",
            CapacityMin: 70, CapacityMax: 320,
            Description: "Houses the {Company} Business School, MBA programme and executive education suite",
            Phone: "+233 30 222 3120", Email: "business"),
        new("FB-SCI", "Faculty of Sciences Building", "Faculty Building", "Greater Accra", "Accra", "Science Block, Legon, Accra",
            CapacityMin: 90, CapacityMax: 380,
            Description: "Laboratories and lecture theatres for the basic and applied sciences departments of {Company}",
            Phone: "+233 30 222 3130", Email: "sciences"),
        new("FB-HUM", "Faculty of Humanities Building", "Faculty Building", "Greater Accra", "Accra", "Arts Block, Legon, Accra",
            CapacityMin: 60, CapacityMax: 260,
            Description: "Languages, history, philosophy and social sciences departments of {Company}",
            Phone: "+233 30 222 3140", Email: "humanities"),
        new("FB-HEA", "Faculty of Health Sciences Building", "Faculty Building", "Greater Accra", "Korle Bu, Accra", "Korle Bu Teaching Hospital Annex, Accra",
            CapacityMin: 70, CapacityMax: 300,
            Description: "Medicine, nursing, pharmacy and public health programmes of {Company}, co-located with teaching hospital",
            Phone: "+233 30 222 3160", Email: "health"),
        new("FB-LAW", "Faculty of Law Building", "Faculty Building", "Greater Accra", "Accra", "Law Block, Legon, Accra",
            CapacityMin: 40, CapacityMax: 180,
            Description: "Lecture rooms, moot court and law library for the {Company} School of Law",
            Phone: "+233 30 222 3170", Email: "law"),

        // ── Halls of Residence (5) ───────────────────────────────────────────
        new("HALL-001", "Achimota Hall", "Hostel", "Greater Accra", "Accra", "Achimota Hall Road, Legon, Accra",
            CapacityMin: 30, CapacityMax: 600,
            Description: "Traditional male hall of residence at {Company} known for academic and athletic excellence",
            Phone: "+233 30 222 3310", Email: "achimotahall"),
        new("HALL-002", "Volta Hall", "Hostel", "Greater Accra", "Accra", "Volta Hall Road, Legon, Accra",
            CapacityMin: 25, CapacityMax: 500,
            Description: "Female hall of residence at {Company} hosting undergraduate and postgraduate residents",
            Phone: "+233 30 222 3311", Email: "voltahall"),
        new("HALL-003", "Akuafo Hall", "Hall of Residence", "Greater Accra", "Accra", "Akuafo Hall Road, Legon, Accra",
            CapacityMin: 30, CapacityMax: 550,
            Description: "Mixed hall of residence at {Company} with strong sports and cultural traditions",
            Phone: "+233 30 222 3312", Email: "akuafohall"),
        new("HALL-004", "Commonwealth Hall", "Hall of Residence", "Greater Accra", "Accra", "Commonwealth Hall Road, Legon, Accra",
            CapacityMin: 30, CapacityMax: 520,
            Description: "Senior hall of residence at {Company} for postgraduate and final-year students",
            Phone: "+233 30 222 3313", Email: "commonwealthhall"),
        new("HALL-005", "Pent Hall (Pentagon)", "Hostel", "Greater Accra", "Accra", "Pentagon Hostel, East Legon, Accra",
            CapacityMin: 20, CapacityMax: 450,
            Description: "Off-campus hostel affiliated with {Company} for first-year students",
            Phone: "+233 30 222 3314", Email: "penthall"),

        // ── Library complex (2) ──────────────────────────────────────────────
        new("LIB-MAIN", "Balme Library", "Library", "Greater Accra", "Accra", "Balme Library Road, Legon, Accra",
            CapacityMin: 50, CapacityMax: 1_200,
            Description: "Main university library at {Company} housing 400,000+ volumes and digital research resources",
            Phone: "+233 30 222 3810", Email: "library"),
        new("LIB-MED", "Medical & Health Sciences Library", "Library", "Greater Accra", "Korle Bu, Accra", "Korle Bu Hospital Road, Accra",
            CapacityMin: 20, CapacityMax: 250,
            Description: "Specialised library for {Company} health sciences students and clinical staff",
            Phone: "+233 30 222 3811", Email: "medlibrary"),

        // ── Sports & Recreation (1) ──────────────────────────────────────────
        new("SPORTS-001", "University Sports Complex", "Sports Complex", "Greater Accra", "Accra", "Sports Stadium Road, Legon, Accra",
            CapacityMin: 15, CapacityMax: 200,
            Description: "Athletics stadium, gymnasium, swimming pool and ball courts for {Company} students and staff",
            Phone: "+233 30 222 3850", Email: "sports"),

        // ── Satellite Campuses (3) + Distance Learning Centres (3) ───────────
        new("SAT-KSI", "Kumasi Satellite Campus", "Satellite Campus", "Ashanti", "Kumasi", "KNUST Adum Road, Kumasi",
            CapacityMin: 30, CapacityMax: 250,
            Description: "{Company} satellite campus delivering undergraduate and graduate programmes in Kumasi",
            Phone: "+233 32 202 0100", Email: "kumasi"),
        new("SAT-TKD", "Takoradi Satellite Campus", "Satellite Campus", "Western", "Takoradi", "Harbour Road, Takoradi",
            CapacityMin: 25, CapacityMax: 200,
            Description: "{Company} western regional campus serving the Takoradi-Sekondi metro area",
            Phone: "+233 31 202 0100", Email: "takoradi"),
        new("SAT-TML", "Tamale Satellite Campus", "Satellite Campus", "Northern", "Tamale", "Education Ridge, Tamale",
            CapacityMin: 25, CapacityMax: 200,
            Description: "{Company} northern campus serving Tamale, Bolgatanga and Wa catchment areas",
            Phone: "+233 37 202 0100", Email: "tamale"),
        new("DLC-CC", "Cape Coast Distance Learning Centre", "Distance Learning Centre", "Central", "Cape Coast", "Castle Road, Cape Coast",
            CapacityMin: 5, CapacityMax: 30,
            Description: "Weekend distance-learning centre of {Company} for working professionals in the Central Region",
            Phone: "+233 33 213 2200", Email: "capecoast"),
        new("DLC-SUN", "Sunyani Distance Learning Centre", "Distance Learning Centre", "Bono", "Sunyani", "Penkwase Road, Sunyani",
            CapacityMin: 4, CapacityMax: 25,
            Description: "Distance-learning centre of {Company} serving Bono, Bono East and Ahafo regions",
            Phone: "+233 35 202 0200", Email: "sunyani"),
        new("DLC-HO", "Ho Distance Learning Centre", "Distance Learning Centre", "Volta", "Ho", "Ho Civic Centre Road, Ho",
            CapacityMin: 4, CapacityMax: 25,
            Description: "Distance-learning centre of {Company} serving the Volta and Oti regions",
            Phone: "+233 36 202 0200", Email: "ho"),

        // ── Affiliated Schools (basic / SHS) — 14 ────────────────────────────
        new("SCH-001", "University Basic School", "School", "Greater Accra", "Accra", "Legon Crescent, Accra",
            CapacityMin: 15, CapacityMax: 70,
            Description: "Affiliated KG/JHS basic school on the {Company} main campus serving staff and community children",
            Phone: "+233 30 222 3910", Email: "basicschool"),
        new("SCH-002", "University Senior High School", "School", "Greater Accra", "Accra", "University SHS Road, Legon, Accra",
            CapacityMin: 25, CapacityMax: 120,
            Description: "Affiliated senior high school of {Company} preparing students for WASSCE and direct university progression",
            Phone: "+233 30 222 3911", Email: "shs"),
        new("SCH-003", "Achimota Demonstration School", "School", "Greater Accra", "Accra", "Achimota School Road, Accra",
            CapacityMin: 20, CapacityMax: 90,
            Description: "Demonstration school used for teacher training practicum at {Company}",
            Phone: "+233 30 240 0100", Email: "achimota"),
        new("SCH-004", "Tema Affiliated SHS", "School", "Greater Accra", "Tema", "Community 4, Tema",
            CapacityMin: 18, CapacityMax: 80,
            Description: "Affiliated senior high school of {Company} in Tema community",
            Phone: "+233 30 320 0100", Email: "temashs"),
        new("SCH-005", "Madina Affiliated JHS", "School", "Greater Accra", "Madina", "Madina Estate Road, Accra",
            CapacityMin: 15, CapacityMax: 70,
            Description: "Affiliated junior high school of {Company} serving Madina catchment",
            Phone: "+233 30 250 0100", Email: "madinajhs"),
        new("SCH-006", "Kasoa Affiliated Basic School", "School", "Central", "Kasoa", "Kasoa Toll Booth Road, Kasoa",
            CapacityMin: 12, CapacityMax: 60,
            Description: "Affiliated basic school of {Company} in Kasoa, Central Region",
            Phone: "+233 24 200 0101", Email: "kasoabasic"),
        new("SCH-007", "Kumasi Affiliated SHS", "School", "Ashanti", "Kumasi", "Adum High Street, Kumasi",
            CapacityMin: 18, CapacityMax: 90,
            Description: "Affiliated senior high school of {Company} in Kumasi, Ashanti Region",
            Phone: "+233 32 203 0100", Email: "kumasishs"),
        new("SCH-008", "Tamale Affiliated SHS", "School", "Northern", "Tamale", "Tamale High School Road, Tamale",
            CapacityMin: 15, CapacityMax: 80,
            Description: "Affiliated senior high school of {Company} in Tamale, Northern Region",
            Phone: "+233 37 203 0100", Email: "tamaleshs"),
        new("SCH-009", "Cape Coast Affiliated SHS", "School", "Central", "Cape Coast", "Mfantsipim Road, Cape Coast",
            CapacityMin: 18, CapacityMax: 90,
            Description: "Affiliated senior high school of {Company} in Cape Coast, Central Region",
            Phone: "+233 33 213 0100", Email: "ccshs"),
        new("SCH-010", "Takoradi Affiliated SHS", "School", "Western", "Takoradi", "Sekondi-Takoradi High Road, Takoradi",
            CapacityMin: 15, CapacityMax: 80,
            Description: "Affiliated senior high school of {Company} in Takoradi, Western Region",
            Phone: "+233 31 203 0100", Email: "takoradishs"),
        new("SCH-011", "Sunyani Affiliated SHS", "School", "Bono", "Sunyani", "Sunyani Senior High Road, Sunyani",
            CapacityMin: 12, CapacityMax: 70,
            Description: "Affiliated senior high school of {Company} in Sunyani, Bono Region",
            Phone: "+233 35 203 0100", Email: "sunyanishs"),
        new("SCH-012", "Ho Affiliated SHS", "School", "Volta", "Ho", "Mawuli School Road, Ho",
            CapacityMin: 12, CapacityMax: 70,
            Description: "Affiliated senior high school of {Company} in Ho, Volta Region",
            Phone: "+233 36 203 0100", Email: "hoshs"),
        new("SCH-013", "Koforidua Affiliated JHS", "School", "Eastern", "Koforidua", "Effiduase Road, Koforidua",
            CapacityMin: 10, CapacityMax: 60,
            Description: "Affiliated junior high school of {Company} in Koforidua, Eastern Region",
            Phone: "+233 34 220 0100", Email: "koforidua"),
        new("SCH-014", "Bolgatanga Affiliated SHS", "School", "Upper East", "Bolgatanga", "Bolga High School Road, Bolgatanga",
            CapacityMin: 10, CapacityMax: 60,
            Description: "Affiliated senior high school of {Company} in Bolgatanga, Upper East Region",
            Phone: "+233 38 220 0100", Email: "bolgashs")
    ];

    // ── Job titles ───────────────────────────────────────────────────────────
    // Two parallel ladders:
    //  Academic (PayGrade AC-1..AC-9, Tutor → Vice Chancellor),
    //  Admin    (PayGrade AD-1..AD-7, Cleaner → Director).
    // Salaries align with the rank-band guidance:
    //  rank 1: 1,500–3,800 / rank 2: 3,500–9,000 / rank 3: 8,500–22,000 /
    //  rank 4: 20,000–42,000 / rank 5: 38,000–80,000.
    // AnnualLeave: rank 5/4 → 30, rank 3 → 27 (academic) / 21 (admin),
    // ranks 2/1 → 21. Codes use PROF-001, LECT-001, REG-001, ADM-001 etc.
    // The legacy short codes (PRINCIPAL, VP, ACAD_DIR, …) are retained so the
    // existing tier eligibility lists keep resolving.
    private static readonly IReadOnlyList<JobTitleSpec> _jobTitles =
    [
        // ═════════════════ Academic ladder (AC-1 … AC-9) ═════════════════════

        new("VC-001", "Vice Chancellor", 5, 60_000m, 80_000m, "EXEC", null, true,
            "PhD / Professorial Rank", 20,
            "Academic Leadership, University Governance, Strategic Planning, Stakeholder Engagement, Research Funding",
            "Chief executive and principal academic officer of {Company}, accountable to the University Council",
            "AC-9",
            "Set and execute {Company} strategy; chair the Academic Board; manage NCTE, GTEC and Council relationships; lead fundraising; safeguard academic freedom",
            "Research output, Graduate employability, Student satisfaction index, Subvention vs spend, Accreditation status",
            30),
        new("PVC-001", "Pro-Vice Chancellor (Academic)", 5, 50_000m, 70_000m, "EXEC", "VC-001", true,
            "PhD / Professorial Rank", 18,
            "Academic Strategy, Curriculum Oversight, Quality Assurance, Faculty Leadership",
            "Deputy to the Vice Chancellor with portfolio responsibility for teaching and learning at {Company}",
            "AC-9",
            "Lead academic policy; oversee deans and faculties; drive curriculum reform and quality assurance; chair academic standards board",
            "Programme accreditation rate, Graduation rate, Curriculum review cadence, Teaching quality scores",
            30),
        new("PVC-002", "Pro-Vice Chancellor (Research & Innovation)", 5, 50_000m, 70_000m, "EXEC", "VC-001", true,
            "PhD / Professorial Rank", 18,
            "Research Strategy, Grant Mobilisation, Innovation Management, Industry Partnerships, IP Policy",
            "Deputy to the Vice Chancellor with portfolio responsibility for research and innovation at {Company}",
            "AC-9",
            "Grow {Company} research income; oversee postgraduate school; lead innovation hub and tech transfer; manage industry partnerships",
            "Research grant income, Publications per faculty, Patents filed, PhD completion rate",
            30),
        new("PROVOST-001", "Provost", 5, 45_000m, 65_000m, "EXEC", "VC-001", true,
            "PhD", 17,
            "Academic Administration, Faculty Coordination, Resource Allocation, Academic Standards",
            "Senior academic officer overseeing all faculties and academic resource allocation at {Company}",
            "AC-9",
            "Coordinate deans of faculty; allocate teaching loads and academic budgets; chair appointments and promotions board",
            "Faculty performance balance, Academic budget variance, Promotions cycle quality",
            30),
        new("DEAN-ENG", "Dean of Faculty of Engineering", 4, 32_000m, 42_000m, "FACULTY-OF-ENGINEERING", "PROVOST-001", true,
            "PhD in Engineering", 15,
            "Engineering Education, ABET/NABPTEX Accreditation, Industry Liaison, Faculty Leadership",
            "Academic and administrative head of the Faculty of Engineering at {Company}",
            "AC-8",
            "Lead the engineering faculty strategy; secure programme accreditation; build industry partnerships; mentor heads of department",
            "Programme accreditation, Engineering graduate employability, Research grants won, Industry MOUs signed",
            30),
        new("DEAN-BUS", "Dean of Faculty of Business", 4, 32_000m, 42_000m, "FACULTY-OF-BUSINESS", "PROVOST-001", true,
            "PhD / DBA", 15,
            "Business Education, AACSB Standards, MBA Programme Leadership, Executive Education",
            "Academic and administrative head of the Faculty of Business & Management at {Company}",
            "AC-8",
            "Lead the business school strategy; grow MBA and executive education; secure international accreditation; raise corporate sponsorships",
            "AACSB progress, MBA enrolment, Corporate-funded chairs, Alumni giving",
            30),
        new("DEAN-SCI", "Dean of Faculty of Sciences", 4, 31_000m, 41_000m, "FACULTY-OF-SCIENCES", "PROVOST-001", true,
            "PhD", 15,
            "Scientific Research, Lab Management, STEM Education, Grant Strategy",
            "Academic head of the Faculty of Sciences at {Company}",
            "AC-8",
            "Lead sciences strategy; modernise teaching and research labs; secure grant income; supervise heads of department",
            "Research grant income, STEM enrolment growth, Lab utilisation, Publications per faculty",
            30),
        new("DEAN-HUM", "Dean of Faculty of Humanities", 4, 30_000m, 40_000m, "FACULTY-OF-HUMANITIES", "PROVOST-001", true,
            "PhD", 15,
            "Humanities Scholarship, Liberal Arts Curriculum, Cultural Studies",
            "Academic head of the Faculty of Arts and Humanities at {Company}",
            "AC-8",
            "Lead humanities strategy; champion liberal arts education; foster cultural and language scholarship",
            "Programme enrolment, Faculty publications, Public lectures hosted",
            30),
        new("DEAN-EDU", "Dean of Faculty of Education", 4, 30_000m, 40_000m, "FACULTY-OF-HUMANITIES", "PROVOST-001", true,
            "PhD in Education", 15,
            "Teacher Education, Curriculum Studies, Educational Policy",
            "Academic head of the Faculty of Education at {Company}, training the next generation of teachers",
            "AC-8",
            "Lead teacher education; oversee NTC accreditation; manage school placements; advise government on education policy",
            "Teacher licensure pass rate, NTC accreditation, Placements completed",
            30),
        new("DEAN-HEA", "Dean of Faculty of Health Sciences", 4, 33_000m, 42_000m, "FACULTY-OF-SCIENCES", "PROVOST-001", true,
            "MD / PhD", 16,
            "Medical Education, Clinical Training, Health Research, Hospital Liaison",
            "Academic head of the Faculty of Health Sciences at {Company}, working with the teaching hospital",
            "AC-8",
            "Lead health sciences strategy; manage clinical rotations; secure HEFRA accreditation; oversee residency programmes",
            "Licensure pass rate, Residency completion, Clinical research output",
            30),
        new("DEAN-LAW", "Dean of Faculty of Law", 4, 31_000m, 41_000m, "FACULTY-OF-HUMANITIES", "PROVOST-001", true,
            "LLD / PhD in Law", 15,
            "Legal Education, Bar Council Liaison, Moot Court, Legal Research",
            "Academic head of the School of Law at {Company}",
            "AC-8",
            "Lead law school strategy; coordinate Ghana School of Law progression; oversee moot court and legal aid clinic",
            "Bar exam pass rate, Moot court trophies, Legal aid cases handled",
            30),
        new("HOD-001", "Head of Department", 4, 22_000m, 32_000m, "ACADEMIC-AFFAIRS", null, true,
            "PhD", 10,
            "Departmental Leadership, Curriculum Management, Faculty Mentoring, Student Outcomes",
            "Academic head of a department reporting to the dean of faculty at {Company}",
            "AC-7",
            "Manage departmental staff and budget; coordinate teaching loads; champion programme review; mentor junior faculty",
            "Programme outcomes, Course evaluations, Staff publications, Student progression",
            30),
        new("PROF-001", "Professor", 4, 25_000m, 38_000m, "ACADEMIC-AFFAIRS", "HOD-001", false,
            "PhD + Professorial Rank", 15,
            "Research Leadership, Doctoral Supervision, Senior Teaching, Editorial Service",
            "Senior academic with full professorial rank, leading research and doctoral supervision at {Company}",
            "AC-8",
            "Lead research programmes; supervise PhD candidates; deliver advanced lectures; serve on university committees",
            "Citations, Doctoral graduations, Research grants secured, Editorial appointments",
            30),
        new("ASSOC-001", "Associate Professor", 3, 18_000m, 22_000m, "ACADEMIC-AFFAIRS", "HOD-001", false,
            "PhD", 10,
            "Research, Postgraduate Supervision, Curriculum Development",
            "Senior academic ranking between Senior Lecturer and Professor at {Company}",
            "AC-7",
            "Conduct funded research; supervise masters and PhD students; lead course development; mentor lecturers",
            "Research output, Postgraduate completions, Course quality scores",
            27),
        new("SLECT-001", "Senior Lecturer", 3, 14_000m, 20_000m, "ACADEMIC-AFFAIRS", "HOD-001", false,
            "PhD", 7,
            "Teaching, Research, Postgraduate Supervision, Course Coordination",
            "Senior teaching academic responsible for course coordination and research at {Company}",
            "AC-6",
            "Deliver undergraduate and graduate lectures; supervise dissertations; publish research; coordinate assigned courses",
            "Course evaluations, Publications per year, Postgraduate completions",
            27),
        new("LECT-001", "Lecturer", 3, 9_000m, 14_000m, "ACADEMIC-AFFAIRS", "SLECT-001", false,
            "Master's Degree (PhD preferred)", 3,
            "Teaching, Course Design, Assessment, Research",
            "Academic lecturer delivering undergraduate and selected graduate courses at {Company}",
            "AC-5",
            "Prepare and deliver lectures and tutorials; set and mark assessments; supervise undergraduate projects; pursue research",
            "Teaching quality, Research progress, Project supervision load",
            27),
        new("ALECT-001", "Assistant Lecturer", 2, 6_500m, 9_000m, "ACADEMIC-AFFAIRS", "LECT-001", false,
            "Master's Degree", 1,
            "Teaching, Tutorials, Marking, Junior Research",
            "Junior academic supporting lectures, tutorials and marking at {Company}",
            "AC-4",
            "Run tutorials and laboratory sessions; mark scripts; co-deliver lectures; pursue further qualification",
            "Tutorial attendance, Marking turnaround, Student feedback",
            21),
        new("TUTOR-001", "Tutor / Teaching Assistant", 1, 1_800m, 3_500m, "ACADEMIC-AFFAIRS", "ALECT-001", false,
            "Bachelor's Degree", 0,
            "Tutoring, Marking Support, Practical Sessions",
            "Graduate tutor supporting tutorials, practicals and marking at {Company}",
            "AC-1",
            "Run small-group tutorials; assist in lab sessions; mark first drafts under supervision",
            "Tutorial coverage, Mark turnaround, Student progression",
            21),
        new("DEMO-001", "Senior Demonstrator", 2, 4_000m, 6_500m, "FACULTY-OF-SCIENCES", "SLECT-001", false,
            "Master's Degree", 2,
            "Lab Demonstrations, Equipment Operation, Practical Coaching",
            "Senior demonstrator supporting laboratory practicals and student experiments at {Company}",
            "AC-3",
            "Set up experiments; demonstrate techniques; supervise lab safety; mentor junior demonstrators",
            "Lab utilisation, Safety incidents, Practical completion rate",
            21),
        new("RFEL-001", "Research Fellow", 3, 10_000m, 16_000m, "RESEARCH-INNOVATION", null, false,
            "PhD", 3,
            "Research, Grant Writing, Publications, Lab Management",
            "Postdoctoral research fellow contributing to funded research projects at {Company}",
            "AC-6",
            "Lead workstreams in funded research projects; publish results; co-supervise students; co-write grants",
            "Publications, Grant income share, Project milestones",
            27),
        new("RA-001", "Research Assistant", 2, 4_000m, 6_500m, "RESEARCH-INNOVATION", "RFEL-001", false,
            "Bachelor's / Master's Degree", 1,
            "Data Collection, Literature Review, Lab Work, Documentation",
            "Junior researcher supporting senior staff with data, lab work and literature reviews at {Company}",
            "AC-3",
            "Collect and analyse research data; conduct literature reviews; maintain lab notebooks; support publications",
            "Data quality, Tasks completed on time, Co-authored publications",
            21),
        new("POSTDOC-001", "Postdoctoral Researcher", 3, 9_000m, 13_000m, "RESEARCH-INNOVATION", "PROF-001", false,
            "PhD", 0,
            "Independent Research, Publications, Mentoring, Grant Writing",
            "Postdoctoral researcher building independent research portfolio under a {Company} senior PI",
            "AC-5",
            "Conduct independent research within host group; publish first-author papers; co-supervise students; pursue follow-on funding",
            "First-author publications, Conference talks, Follow-on funding",
            27),
        new("CURR-001", "Curriculum Coordinator", 3, 9_500m, 14_000m, "ACADEMIC-AFFAIRS", "PROVOST-001", false,
            "Master's Degree in Education", 5,
            "Curriculum Design, Quality Assurance, Programme Review",
            "Coordinator owning programme curriculum cycles and quality assurance at {Company}",
            "AC-5",
            "Run curriculum review cycles; align programmes with NCTE/GTEC standards; coordinate accreditation visits",
            "Programme review cadence, Accreditation outcomes, Curriculum currency",
            27),
        new("PROG-001", "Programme Director", 3, 12_000m, 18_000m, "ACADEMIC-AFFAIRS", "PROVOST-001", true,
            "PhD / Master's Degree", 7,
            "Programme Leadership, Stakeholder Management, Student Outcomes",
            "Director of a flagship academic programme reporting to Academic Affairs at {Company}",
            "AC-6",
            "Own programme outcomes end-to-end; manage faculty assignments and resources; engage external advisors; report to provost",
            "Enrolment, Graduation rate, Employer satisfaction, Programme NPS",
            27),

        // ═════════════════ Admin ladder (AD-1 … AD-7) ════════════════════════

        new("REG-001", "Registrar", 5, 38_000m, 55_000m, "REGISTRY", "VC-001", true,
            "Master's Degree", 15,
            "University Administration, Student Records, Examinations, Statutes & Bye-laws",
            "Chief administrative officer of {Company}, secretary to Council and Academic Board",
            "AD-7",
            "Administer central university affairs; secretary to Council; oversee admissions, exams, records; advise on statutes",
            "Council minutes accuracy, Records integrity, Statutes compliance, Admissions cycle delivery",
            30),
        new("DREG-001", "Deputy Registrar", 4, 22_000m, 32_000m, "REGISTRY", "REG-001", true,
            "Master's Degree", 10,
            "Deputy Administration, Faculty Liaison, Records, Policy Drafting",
            "Senior administrator deputising for the Registrar at {Company}",
            "AD-6",
            "Deputise for Registrar; oversee senior assistant registrars; draft policies; manage faculty board secretariats",
            "Policy turnaround, Faculty board minutes, SAR coverage",
            30),
        new("SAR-ADM", "Senior Assistant Registrar (Admissions)", 3, 12_000m, 18_000m, "REGISTRY", "DREG-001", true,
            "Master's Degree", 6,
            "Admissions Strategy, Student Recruitment, Application Processing",
            "Senior administrator in charge of the admissions cycle at {Company}",
            "AD-5",
            "Lead admissions cycle; manage application portal; coordinate selection panels; deliver matriculation",
            "Application volume, Conversion rate, Matriculation timeliness",
            21),
        new("SAR-EXM", "Senior Assistant Registrar (Examinations)", 3, 12_000m, 18_000m, "REGISTRY", "DREG-001", true,
            "Master's Degree", 6,
            "Examinations Logistics, Invigilation, Results Processing, Academic Integrity",
            "Senior administrator running the examinations function at {Company}",
            "AD-5",
            "Plan exam timetables; coordinate invigilation; oversee marking and moderation; publish results",
            "Exam delivery on time, Results turnaround, Malpractice rate",
            21),
        new("SAR-AAR", "Senior Assistant Registrar (Academic Affairs)", 3, 11_500m, 17_500m, "REGISTRY", "DREG-001", true,
            "Master's Degree", 6,
            "Academic Policy, Faculty Liaison, Programme Records",
            "Senior administrator handling academic affairs at {Company}",
            "AD-5",
            "Service academic boards; maintain programme registers; coordinate convocation; advise on academic policy",
            "Board minutes timeliness, Programme register accuracy, Convocation delivery",
            21),
        new("SAR-REC", "Senior Assistant Registrar (Student Records)", 3, 11_000m, 17_000m, "REGISTRY", "DREG-001", true,
            "Master's Degree", 6,
            "Student Records, Transcripts, Data Protection",
            "Senior administrator owning the student records function at {Company}",
            "AD-5",
            "Maintain academic records; issue transcripts and certificates; safeguard student data; respond to verification requests",
            "Transcript turnaround, Records accuracy, Data breach incidents",
            21),
        new("ADMOFF-001", "Admissions Officer", 2, 4_500m, 7_500m, "REGISTRY", "SAR-ADM", false,
            "Bachelor's Degree", 2,
            "Application Processing, Customer Service, Data Entry",
            "Admissions officer processing applications and supporting prospective students at {Company}",
            "AD-3",
            "Process applications; respond to prospective student queries; verify documents; support open days",
            "Applications processed, Response time, Data accuracy",
            21),
        new("EXMOFF-001", "Examinations Officer", 2, 4_500m, 7_500m, "REGISTRY", "SAR-EXM", false,
            "Bachelor's Degree", 2,
            "Exam Logistics, Invigilation, Script Handling",
            "Examinations officer coordinating exam venues, scripts and invigilators at {Company}",
            "AD-3",
            "Set up exam halls; brief invigilators; collect and dispatch scripts; record incidents",
            "Exam venue readiness, Script reconciliation, Incident reports",
            21),
        new("RECOFF-001", "Academic Records Officer", 2, 4_000m, 7_000m, "REGISTRY", "SAR-REC", false,
            "Bachelor's Degree", 2,
            "Records Management, Transcripts, Verification",
            "Records officer issuing transcripts and verifying academic credentials at {Company}",
            "AD-3",
            "Issue transcripts and certificates; verify credentials for employers; archive student files",
            "Transcript turnaround, Verification accuracy, Archive integrity",
            21),
        new("DSA-001", "Dean of Students", 4, 25_000m, 35_000m, "STUDENT-AFFAIRS", "VC-001", true,
            "Master's Degree", 12,
            "Student Welfare, Halls Administration, Counselling, Sports",
            "Senior officer responsible for student welfare and residential life at {Company}",
            "AD-7",
            "Lead student affairs; oversee halls of residence; manage counselling and sports services; chair disciplinary committee",
            "Hall occupancy, Counselling uptake, Discipline cases resolved",
            30),
        new("STUOFF-001", "Student Affairs Officer", 2, 4_500m, 7_500m, "STUDENT-AFFAIRS", "DSA-001", false,
            "Bachelor's Degree", 2,
            "Student Welfare, Event Coordination, Grievance Handling",
            "Officer supporting day-to-day student affairs and welfare programmes at {Company}",
            "AD-3",
            "Run welfare programmes; coordinate student events; handle first-line grievances; support SRC liaison",
            "Events delivered, Grievance resolution time, Student satisfaction",
            21),
        new("COUN-001", "Student Counsellor", 3, 9_000m, 14_000m, "STUDENT-AFFAIRS", "DSA-001", false,
            "Master's in Counselling/Psychology", 3,
            "Counselling, Mental Health, Career Guidance, Confidentiality",
            "Licensed counsellor providing psychological, academic and career counselling to {Company} students",
            "AD-5",
            "Run individual and group counselling; deliver mental-health programmes; refer complex cases; maintain confidentiality",
            "Counselling sessions, Crisis interventions, Student feedback",
            21),
        new("HALLT-001", "Hall Tutor", 2, 4_500m, 8_500m, "STUDENT-AFFAIRS", "HALLM-001", false,
            "Bachelor's / Master's Degree", 2,
            "Pastoral Care, Hall Discipline, Mentoring",
            "Resident tutor providing pastoral care in a hall of residence at {Company}",
            "AD-3",
            "Reside in hall; mentor undergraduates; enforce hall rules; report to hall master",
            "Hall climate, Discipline incidents, Mentoring engagement",
            21),
        new("HALLM-001", "Hall Master / Mistress", 3, 12_000m, 18_000m, "STUDENT-AFFAIRS", "DSA-001", true,
            "Master's Degree", 6,
            "Hall Leadership, Pastoral Care, Hall Administration",
            "Senior academic appointed to lead a hall of residence at {Company}",
            "AD-6",
            "Lead a hall of residence; chair junior common room committee; oversee hall finances and tutors",
            "Hall culture, Hall budget variance, Leadership engagement",
            27),
        new("SPORT-001", "Sports Director", 3, 9_500m, 14_500m, "STUDENT-AFFAIRS", "DSA-001", true,
            "Bachelor's in Sports Science", 5,
            "Athletics Programme, Coaching, Inter-University Games, Facilities",
            "Director leading sports, athletics and recreation at {Company}",
            "AD-5",
            "Manage sports complex and teams; coach for GUSA games; coordinate inter-university competitions",
            "GUSA medals, Team participation, Facility utilisation",
            27),
        new("HEALTH-001", "Health Services Officer", 3, 9_000m, 13_500m, "STUDENT-AFFAIRS", "DSA-001", false,
            "Medical / Nursing Degree", 4,
            "Primary Healthcare, Student Clinic, Public Health",
            "Clinical officer running the student clinic and health programmes at {Company}",
            "AD-5",
            "Run primary clinic; coordinate immunisation drives; refer complex cases; maintain medical records",
            "Patient throughput, Immunisation coverage, Referral quality",
            27),
        new("LIBR-001", "University Librarian", 4, 22_000m, 32_000m, "LIBRARY", "VC-001", true,
            "Master's in Library & Information Science", 12,
            "Library Strategy, E-Resources, Cataloguing, Reader Services",
            "Chief librarian responsible for the entire library system at {Company}",
            "AD-7",
            "Lead library strategy; negotiate e-resource subscriptions; oversee cataloguing and digitisation; mentor library staff",
            "Resource utilisation, E-journal subscriptions, Reader satisfaction",
            30),
        new("LIBA-001", "Library Assistant", 1, 2_200m, 3_500m, "LIBRARY", "LIBR-001", false,
            "Diploma in Library Studies", 0,
            "Shelving, Circulation, Reader Support",
            "Library assistant supporting shelving, circulation and reader queries at {Company}",
            "AD-1",
            "Shelve returned books; staff circulation desk; assist readers with catalogue searches",
            "Shelving accuracy, Circulation throughput, Reader feedback",
            21),
        new("ARCH-001", "Archives Officer", 2, 4_500m, 7_500m, "LIBRARY", "LIBR-001", false,
            "Bachelor's Degree", 2,
            "Archival Records, Preservation, Records Management",
            "Officer managing the {Company} archives, special collections and historical records",
            "AD-3",
            "Catalogue archival materials; oversee preservation; respond to research requests; digitise rare collections",
            "Catalogue completeness, Preservation incidents, Researcher service",
            21),
        new("DFIN-001", "Director of Finance", 5, 40_000m, 60_000m, "FINANCE-BURSARY", "VC-001", true,
            "Master's / ACCA / ICAG", 15,
            "Financial Strategy, Treasury, IFRS, Budgeting, Audit Liaison",
            "Executive leading finance, treasury and financial reporting at {Company}",
            "AD-7",
            "Set financial strategy; produce IFRS-compliant statements; manage Council finance committee; lead annual audit",
            "Audit opinion, Budget variance, Cash position, Fees collection rate",
            30),
        new("BURS-001", "Bursar", 4, 22_000m, 32_000m, "FINANCE-BURSARY", "DFIN-001", true,
            "Master's / Professional Accounting", 10,
            "Fees Collection, Payroll, Disbursement, Vendor Payments",
            "Senior officer running the bursary, fees and payroll functions of {Company}",
            "AD-6",
            "Operate the bursary; oversee fees collection; run payroll; pay vendors; manage student financial aid",
            "Fees collection rate, Payroll accuracy, Aid disbursement timeliness",
            27),
        new("SACC-001", "Senior Accountant", 3, 11_000m, 17_000m, "FINANCE-BURSARY", "DFIN-001", false,
            "Bachelor's + Part-Qualified Accountant", 5,
            "Financial Reporting, Reconciliations, Tax, IFRS",
            "Senior accountant supporting financial reporting and reconciliations at {Company}",
            "AD-5",
            "Prepare monthly management accounts; perform reconciliations; manage tax filings; support audit",
            "Reporting timeliness, Reconciliation completeness, Audit findings",
            21),
        new("ACCT-001", "Accountant", 2, 6_500m, 9_000m, "FINANCE-BURSARY", "SACC-001", false,
            "Bachelor's in Accounting", 2,
            "Bookkeeping, Bank Reconciliations, Vendor Payments",
            "Accountant handling day-to-day finance transactions at {Company}",
            "AD-3",
            "Post journals; reconcile bank accounts; process vendor payments; support month-end close",
            "Posting accuracy, Reconciliation cadence, Vendor TAT",
            21),
        new("AUD-001", "Internal Auditor", 3, 11_000m, 17_000m, "FINANCE-BURSARY", "VC-001", false,
            "Bachelor's / CIA / ACCA", 5,
            "Internal Audit, Risk-Based Auditing, Controls Testing",
            "Internal auditor reporting administratively to finance and functionally to Council audit committee at {Company}",
            "AD-5",
            "Plan and execute risk-based audits; test controls; report findings; track remediation",
            "Audit plan delivery, Findings closure rate, Audit committee reports",
            21),
        new("DHR-001", "Director of Human Resources", 5, 38_000m, 55_000m, "HR", "VC-001", true,
            "Master's in HR / OD", 15,
            "HR Strategy, Faculty Recruitment, Industrial Relations, Total Rewards",
            "Executive leading the people function at {Company}",
            "AD-7",
            "Set HR strategy; lead faculty and staff recruitment; manage union relations; oversee compensation and learning",
            "Time-to-hire, Engagement score, Industrial peace, Succession coverage",
            30),
        new("HRO-001", "HR Officer", 2, 4_500m, 7_500m, "HR", "DHR-001", false,
            "Bachelor's Degree", 2,
            "Recruitment Support, HR Operations, Employee Records",
            "HR officer handling day-to-day people operations at {Company}",
            "AD-3",
            "Process recruitment paperwork; maintain employee records; support onboarding and exit; respond to employee queries",
            "Onboarding TAT, Records accuracy, Query resolution time",
            21),
        new("DICT-001", "Director of ICT", 5, 38_000m, 55_000m, "ICT", "VC-001", true,
            "Master's in Computer Science / Information Systems", 15,
            "ICT Strategy, Network Design, LMS, Cybersecurity, Vendor Management",
            "Executive leading the campus ICT and digital services function at {Company}",
            "AD-7",
            "Define ICT roadmap; oversee network and LMS; lead cybersecurity; manage vendors; chair digital committee",
            "Uptime, Cyber incident rate, Project delivery, Service desk SLA",
            30),
        new("NETENG-001", "Network Engineer", 3, 9_500m, 14_500m, "ICT", "DICT-001", false,
            "Bachelor's + CCNA/CCNP", 4,
            "Routing & Switching, Wi-Fi, VPN, Network Security",
            "Senior engineer running campus network, Wi-Fi and security at {Company}",
            "AD-5",
            "Operate core and access networks; manage Wi-Fi; harden network security; respond to incidents",
            "Uptime, Mean time to repair, Wi-Fi coverage, Security incidents",
            27),
        new("ICTSUP-001", "ICT Support Officer", 2, 4_000m, 6_500m, "ICT", "NETENG-001", false,
            "Diploma / Bachelor's in IT", 1,
            "Service Desk, Hardware Support, Software Installation",
            "ICT support officer running the service desk and end-user support at {Company}",
            "AD-3",
            "Resolve service desk tickets; install and maintain end-user devices; support staff and student labs",
            "Ticket TAT, First-call resolution, User satisfaction",
            21),
        new("DEST-001", "Director of Estates & Facilities", 5, 38_000m, 52_000m, "ESTATES-FACILITIES", "VC-001", true,
            "Bachelor's / Master's in Estate Management", 15,
            "Estates Strategy, Capital Projects, Maintenance, Energy",
            "Executive leading buildings, grounds and facilities at {Company}",
            "AD-7",
            "Plan capital works; oversee maintenance; manage utilities; supervise security and transport contracts",
            "Capital project delivery, Maintenance backlog, Utility cost",
            30),
        new("ESTOFF-001", "Estate Officer", 2, 4_500m, 7_500m, "ESTATES-FACILITIES", "DEST-001", false,
            "Bachelor's Degree", 2,
            "Building Inspections, Maintenance Coordination, Vendor Liaison",
            "Estate officer coordinating maintenance and inspections of {Company} buildings",
            "AD-3",
            "Inspect buildings; raise maintenance work orders; supervise contractors; track defects",
            "Inspection coverage, Work order TAT, Defect closure",
            21),
        new("SECOFF-001", "Security Officer", 1, 1_800m, 3_500m, "ESTATES-FACILITIES", "DEST-001", false,
            "Senior High School", 1,
            "Patrol, Access Control, Incident Reporting",
            "Security officer maintaining campus safety at {Company}",
            "AD-1",
            "Patrol assigned beats; man access points; record visitors; report incidents",
            "Incident reports, Patrol coverage, Visitor compliance",
            21),
        new("DRV-001", "Driver", 1, 1_800m, 3_500m, "ESTATES-FACILITIES", "DEST-001", false,
            "Senior High School + Licence", 2,
            "Defensive Driving, Vehicle Maintenance, Logistics",
            "Driver operating staff and student transport for {Company}",
            "AD-1",
            "Drive assigned vehicles; maintain logbook; perform daily vehicle checks; ensure passenger safety",
            "Trips on time, Accident rate, Vehicle uptime",
            21),
        new("CLN-001", "Cleaner", 1, 1_500m, 2_500m, "ESTATES-FACILITIES", "DEST-001", false,
            "Basic Education", 0,
            "Cleaning, Sanitation, Waste Disposal",
            "Cleaning staff maintaining hygiene of {Company} buildings",
            "AD-1",
            "Clean assigned blocks; replenish washroom supplies; dispose of waste; report damage",
            "Cleanliness audits, Supply stockouts, Damage reports",
            21),
        new("CATER-001", "Catering Officer", 2, 4_000m, 7_000m, "ESTATES-FACILITIES", "DEST-001", false,
            "Diploma in Catering", 2,
            "Menu Planning, Food Safety, Kitchen Operations",
            "Officer running the {Company} dining halls and food safety programme",
            "AD-3",
            "Plan menus; oversee dining halls; ensure food safety compliance; manage kitchen staff",
            "Customer satisfaction, Food safety audits, Cost per cover",
            21),
        new("PROC-001", "Procurement Officer", 2, 5_000m, 8_500m, "PROCUREMENT", "VC-001", false,
            "Bachelor's + CIPS Part-Qualified", 3,
            "PPA Compliance, Tendering, Vendor Management",
            "Procurement officer running tenders and vendor contracts for {Company}",
            "AD-3",
            "Run PPA-compliant tenders; manage vendor contracts; maintain supplier register; support audit",
            "Tender cycle time, PPA compliance, Vendor performance",
            21),
        new("STOR-001", "Stores Officer", 1, 2_000m, 3_500m, "PROCUREMENT", "PROC-001", false,
            "Senior High School / Diploma", 1,
            "Stock Control, Receipts & Issues, Stock Counts",
            "Stores officer running the central stores at {Company}",
            "AD-1",
            "Receive deliveries; issue stock against requisitions; perform cycle counts; maintain bin cards",
            "Stock accuracy, Issue TAT, Stockout rate",
            21),
        new("PUB-001", "Public Affairs Officer", 2, 4_500m, 7_500m, "PROCUREMENT", "VC-001", false,
            "Bachelor's in Communications / Marketing", 2,
            "Media Relations, Internal Comms, Events",
            "Officer running public affairs, media and events for {Company}",
            "AD-3",
            "Draft press releases; manage social media; coordinate university events; service media queries",
            "Media coverage, Event delivery, Social engagement",
            21),

        // ─── Legacy short codes preserved so SME / NonProfit eligibility lists keep resolving ───
        new("PRINCIPAL",       "Principal/Head",          5, 38_000m, 55_000m, "EXEC",             null,        true,  "Master's Degree",   8,
            "Educational Leadership, Administration",
            "Head of a basic-education or SHS unit affiliated with {Company}",
            "AD-7",
            "Lead the school; manage staff; engage parents and PTA; uphold GES standards",
            "WASSCE/BECE pass rate, GES inspection score, Enrolment growth",
            30),
        new("VP",              "Vice Principal",          4, 22_000m, 32_000m, "EXEC",             "PRINCIPAL", true,  "Master's Degree",   6,
            "Academic Administration, Curriculum",
            "Deputy head supporting the Principal at a {Company}-affiliated school",
            "AD-6",
            "Coordinate timetables; supervise heads of department; deputise for Principal",
            "Timetable adherence, Internal exam delivery, Discipline",
            30),
        new("ACAD_DIR",        "Academic Director",       5, 40_000m, 60_000m, "ACADEMIC",         "PRINCIPAL", true,  "Master's Degree",   7,
            "Academic Leadership, Curriculum Development",
            "Academic director overseeing curriculum and quality at {Company}",
            "AC-9",
            "Direct curriculum strategy; mentor heads of department; chair academic committee",
            "Curriculum currency, Inspection score, Teacher development",
            30),
        new("SENIOR_LECTURER", "Senior Lecturer",         3, 14_000m, 20_000m, "ACADEMIC",         "ACAD_DIR",  true,  "Master's Degree",   6,
            "Teaching, Research, Course Development",
            "Senior lecturer at {Company} delivering teaching and research",
            "AC-6",
            "Lead course delivery; supervise dissertations; pursue research output",
            "Course evaluations, Publications, Postgraduate completions",
            27),
        new("HOD",             "Head of Department",      4, 22_000m, 32_000m, "ACADEMIC",         "ACAD_DIR",  true,  "Master's Degree",   5,
            "Department Management, Teaching",
            "Departmental head responsible for staff and teaching coverage at {Company}",
            "AC-7",
            "Manage department staff; allocate teaching loads; chair department meetings",
            "Course coverage, Staff development, Programme outcomes",
            30),
        new("ADMIN",           "Administrator",           3, 9_000m, 14_000m, "ADMIN",            null,        true,  "Bachelor's Degree", 5,
            "Administration, Office Management",
            "General administrator supporting a {Company} unit",
            "AD-5",
            "Manage office operations; coordinate logistics; maintain records",
            "Office uptime, Records accuracy, Stakeholder feedback",
            21),
        new("STUDENT_MGR",     "Student Services Manager",4, 22_000m, 32_000m, "STUDENT_SERVICES", null,        true,  "Bachelor's Degree", 5,
            "Student Support, Counseling",
            "Manager leading student services at {Company}",
            "AD-6",
            "Lead student services team; oversee counselling and welfare; coordinate orientation",
            "Service uptime, Student satisfaction, Crisis response",
            27),
        new("LECTURER",        "Lecturer",                3, 9_000m, 14_000m, "ACADEMIC",         "SENIOR_LECTURER", false, "Bachelor's Degree", 3,
            "Teaching, Course Delivery",
            "Lecturer delivering courses at {Company}",
            "AC-5",
            "Prepare lectures; mark assessments; supervise projects",
            "Course evaluations, Student outcomes, Assessment quality",
            27),
        new("TEACHER",         "Teacher",                 2, 3_500m, 6_500m, "ACADEMIC",         "HOD",       false, "Bachelor's Degree", 2,
            "Teaching, Lesson Planning",
            "Teacher delivering lessons at a {Company}-affiliated school",
            "AC-3",
            "Plan and deliver lessons; mark scripts; engage parents; supervise class",
            "Class results, Lesson observation scores, Parent feedback",
            21),
        new("ADMIN_OFFICER",   "Administrative Officer",  3, 9_000m, 13_000m, "ADMIN",            "ADMIN",     false, "Diploma",           2,
            "Administrative Support, Record Keeping",
            "Officer providing administrative support across {Company}",
            "AD-4",
            "Maintain registers; coordinate office logistics; support meetings",
            "Logistics on time, Record accuracy, Internal feedback",
            21),
        new("STUDENT_OFFICER", "Student Services Officer",2, 4_500m, 7_500m, "STUDENT_SERVICES", "STUDENT_MGR", false, "Bachelor's Degree", 2,
            "Student Support, Enrollment",
            "Officer running first-line student services for {Company}",
            "AD-3",
            "Run enrolment desk; resolve student queries; support orientation",
            "Query TAT, Enrolment delivery, Student NPS",
            21),
        new("LIBRARIAN",       "Librarian",               3, 9_000m, 13_000m, "SUPPORT",          null,        false, "Bachelor's Degree", 2,
            "Library Management, Research Support",
            "Librarian running a faculty or branch library at {Company}",
            "AD-4",
            "Catalogue acquisitions; assist researchers; manage circulation",
            "Acquisitions catalogued, Reader satisfaction, Circulation throughput",
            21),
        new("IT_OFFICER",      "IT Officer",              3, 9_000m, 13_000m, "IT",               null,        false, "Bachelor's Degree", 3,
            "IT Support, Systems Administration",
            "IT officer supporting computers, networks and labs at {Company}",
            "AD-4",
            "Maintain end-user devices; support computer labs; respond to tickets",
            "Ticket TAT, Lab uptime, User satisfaction",
            21),
        new("ASSIST_TEACHER",  "Assistant Teacher",       2, 3_500m, 5_500m, "ACADEMIC",         "TEACHER",   false, "Diploma",           1,
            "Teaching Support, Classroom Assistance",
            "Assistant teacher supporting classroom delivery at {Company}",
            "AC-2",
            "Support lead teacher; supervise practicals; mark formative work",
            "Class engagement, Marking timeliness, Mentor feedback",
            21),
        new("ADMIN_ASSIST",    "Administrative Assistant",2, 3_500m, 5_500m, "ADMIN",            "ADMIN_OFFICER", false, "High School",   1,
            "Administrative Support, Filing",
            "Administrative assistant supporting {Company} office operations",
            "AD-2",
            "Filing; reception; basic correspondence; meeting logistics",
            "Filing accuracy, Reception feedback, Logistics on time",
            21),
        new("STUDENT_ASSIST",  "Student Services Assistant",2,3_500m, 5_500m, "STUDENT_SERVICES", "STUDENT_OFFICER",false,"High School",  1,
            "Student Support, Reception",
            "Assistant providing front-line student support at {Company}",
            "AD-2",
            "Receive students; route queries; support orientation desk",
            "Query routing, Reception feedback, Desk uptime",
            21),
        new("LIBRARY_ASSIST",  "Library Assistant",       1, 2_000m, 3_500m, "SUPPORT",          "LIBRARIAN", false, "High School",       1,
            "Library Support, Shelving",
            "Library assistant at a {Company} library",
            "AD-1",
            "Shelve returns; staff issue desk; support readers",
            "Shelving accuracy, Reader feedback, Issue TAT",
            21),
        new("TA",              "Teaching Assistant",      1, 1_500m, 3_000m, "ACADEMIC",         "ASSIST_TEACHER", false, "Student",      0,
            "Learning, Teaching Support",
            "Graduate teaching assistant supporting tutorials at {Company}",
            "AC-1",
            "Support tutorials and labs; mark first drafts; mentor undergraduates",
            "Tutorial coverage, Marking turnaround, Student feedback",
            21),
        new("INTERN",          "Intern",                  1, 1_500m, 2_500m, "ADMIN",            "ADMIN_ASSIST",   false, "Student",      0,
            "Learning, Administrative Support",
            "Intern gaining experience across {Company} administrative functions",
            "AD-1",
            "Shadow senior staff; complete assigned tasks; submit weekly reports",
            "Tasks completed, Mentor feedback, Reflection quality",
            21)
    ];
}
