using QimErp.Shared.DemoData.Ghana;

namespace QimErp.Shared.DemoData.Industry.Profiles;

public sealed class HealthcareIndustryProfile : IIndustryProfile
{
    public string Code => "HEALTHCARE";
    public string DisplayName => "Healthcare & Medical Services";

    public IReadOnlyList<string> SampleCompanyNames =>
    [
        "37 Military Hospital", "Korle Bu Teaching Hospital", "Tema General Hospital",
        "Trust Hospital", "mPharma Group", "Ridge Hospital", "Nyaho Medical Centre",
        "Lister Hospital", "University of Ghana Medical Centre",
        "Komfo Anokye Teaching Hospital", "Ghana Health Service",
        "Holy Trinity Medical Centre"
    ];

    public OrgHierarchySpec BuildOrgHierarchy(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        var (units, distribution) = tier switch
        {
            CompanyTier.Startup    => (StartupUnits,    StartupDistribution),
            CompanyTier.SME        => (SmeUnits,        SmeDistribution),
            CompanyTier.Corporate  => (CorporateUnits,  CorporateDistribution),
            CompanyTier.NonProfit  => (NonProfitUnits,  NonProfitDistribution),
            _                      => (SmeUnits,        SmeDistribution)
        };
        return OrgHierarchyBuilder.Build(units, distribution, targetEmployees, randomSeed);
    }

    public IReadOnlyList<JobTitleSpec> JobTitles => _jobTitles;

    public StationLayout BuildStations(CompanyTier tier, int targetEmployees, int randomSeed)
    {
        // Corporate tier uses the curated tertiary-hospital station catalogue verbatim:
        // a flagship Main Hospital plus regional / district hospitals, polyclinics, health
        // centres and CHPS compounds spread across all 16 Ghana regions. Other tiers fall
        // back to procedural generation so smaller providers land with a reasonable shape.
        if (tier == CompanyTier.Corporate)
        {
            var hqRow = _healthcareStations[0];
            var rest = _healthcareStations.Skip(1).ToList();
            var branchTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                "Regional Hospital", "District Hospital", "Polyclinic"
            };
            return new StationLayout(
                Headquarters: hqRow,
                Branches: rest.Where(s => branchTypes.Contains(s.StationType)).ToList(),
                Satellites: rest.Where(s => !branchTypes.Contains(s.StationType)).ToList());
        }

        var rng = new Random(randomSeed);
        var hq = new StationSpec(
            Code: "HQ",
            Name: "Main Hospital",
            StationType: "Hospital",
            Region: "Greater Accra",
            City: "Accra",
            Address: "Liberation Road, Accra",
            CapacityMin: 80,
            CapacityMax: tier == CompanyTier.Corporate ? 1500 : 400);

        var hospitalCount = tier switch
        {
            CompanyTier.Startup   => 0,
            CompanyTier.SME       => Math.Max(1, targetEmployees / 250),
            CompanyTier.Corporate => Math.Max(2, Math.Min(15, targetEmployees / 200)),
            CompanyTier.NonProfit => Math.Max(1, targetEmployees / 200),
            _                     => 2
        };

        var hospitals = new List<StationSpec>(hospitalCount);
        for (var i = 0; i < hospitalCount; i++)
        {
            var region = GhanaGeography.Regions[rng.Next(GhanaGeography.Regions.Count)];
            var cities = GhanaGeography.CitiesByRegion[region];
            var city = cities[rng.Next(cities.Count)];
            hospitals.Add(new StationSpec(
                Code: $"HOSP{i + 1:D2}",
                Name: $"{city} Hospital",
                StationType: "Hospital",
                Region: region,
                City: city,
                Address: $"{GhanaGeography.Streets[rng.Next(GhanaGeography.Streets.Count)]}, {city}",
                CapacityMin: 40,
                CapacityMax: 400));
        }

        var clinicCount = hospitalCount * 2;
        var clinics = new List<StationSpec>(clinicCount);
        for (var i = 0; i < clinicCount; i++)
        {
            var region = GhanaGeography.Regions[rng.Next(GhanaGeography.Regions.Count)];
            var cities = GhanaGeography.CitiesByRegion[region];
            var city = cities[rng.Next(cities.Count)];
            clinics.Add(new StationSpec(
                Code: $"CLN{i + 1:D3}",
                Name: $"{city} Clinic",
                StationType: "Clinic",
                Region: region,
                City: city,
                Address: $"{GhanaGeography.Streets[rng.Next(GhanaGeography.Streets.Count)]}, {city}",
                CapacityMin: 5,
                CapacityMax: 30));
        }

        return new StationLayout(hq, hospitals, clinics);
    }

    public EmployeeDistributionSpec EmployeeDistribution => new(
        ByRankLevel: new Dictionary<int, double>
        {
            [5] = 0.005,
            [4] = 0.040,
            [3] = 0.250,
            [2] = 0.500,
            [1] = 0.205
        },
        ByOrgUnitCode: null);

    public SalaryBandSpec SalaryBands => new(
        ByRankLevel: new Dictionary<int, (decimal Min, decimal Max)>
        {
            [5] = (10_000m, 25_000m),
            [4] = (5_000m,  19_000m),
            [3] = (3_000m,  15_000m),
            [2] = (2_000m,   4_500m),
            [1] = (1_500m,   2_500m)
        });

    // Eligible-job lists per OU. Codes mirror the entries in `_jobTitles` below.
    private static readonly IReadOnlyList<string> ExecJobs            = ["CEO-001", "CMO-001", "CNO-001", "HOSP-ADMIN-001", "MED-DIR-001", "DON-001"];
    private static readonly IReadOnlyList<string> MedicalJobs         = ["MED-DIR-001", "HOD-SURG-001", "HOD-IM-001", "HOD-PAED-001", "HOD-OBG-001", "HOD-EM-001", "HOD-ICU-001", "HOD-ANAES-001", "CONS-SURG-001", "CONS-IM-001", "CONS-PAED-001", "CONS-OBG-001", "CONS-ANAES-001", "CONS-EM-001", "SMO-001", "MO-001", "HO-001"];
    private static readonly IReadOnlyList<string> NursingJobs         = ["DON-001", "ADON-001", "MATRON-001", "SPEC-NURSE-001", "ICU-NURSE-001", "THEATRE-NURSE-001", "SN-001", "STAFF-NURSE-001", "EN-001", "MIDWIFE-SR-001", "MIDWIFE-001", "NA-001"];
    private static readonly IReadOnlyList<string> ClinicalSupportJobs = ["HOD-PHARM-001", "HOD-LAB-001", "HOD-RAD-001", "HOD-PATH-001", "PHARM-SR-001", "PHARM-001", "PHARM-TECH-001", "LAB-SCI-SR-001", "LAB-SCI-001", "LAB-TECH-001", "RADIOG-SR-001", "RADIOG-001", "SONO-001", "PATH-001"];
    private static readonly IReadOnlyList<string> AlliedHealthJobs    = ["HOD-PHYSIO-001", "PHYSIO-SR-001", "PHYSIO-001", "DIET-001", "PSYCH-001", "OT-001", "SLT-001"];
    private static readonly IReadOnlyList<string> OutpatientJobs      = ["MO-OPD-001", "OPD-NURSE-001", "TRIAGE-NURSE-001", "PAO-001", "RECEP-001"];
    private static readonly IReadOnlyList<string> InpatientJobs       = ["WARD-MGR-001", "STAFF-NURSE-001", "EN-001", "WA-001"];
    private static readonly IReadOnlyList<string> EmergencyJobs       = ["HOD-EM-001", "CONS-EM-001", "MO-001", "ICU-NURSE-001", "TRIAGE-NURSE-001", "PORTER-001"];
    private static readonly IReadOnlyList<string> OperationsJobs      = ["FAC-MGR-001", "BIOMED-ENG-001", "PROC-001", "STORES-001", "PORTER-001", "SECURITY-001", "CLEANER-001", "DRIVER-001", "MORT-001"];
    private static readonly IReadOnlyList<string> QualityJobs         = ["QSO-001", "ICN-001", "ME-001", "HRO-001"];
    private static readonly IReadOnlyList<string> FinanceJobs         = ["HOSP-ACCT-001", "ACCT-001", "BILLING-001", "CASHIER-001"];
    private static readonly IReadOnlyList<string> HrJobs              = ["HR-MGR-001", "HRO-OFF-001", "TRAINING-001"];
    private static readonly IReadOnlyList<string> ItJobs              = ["IT-MGR-001", "IT-OFF-001", "EMR-001"];

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> StartupUnits =
    [
        new("FOUNDER",  "Founder/CEO", null,      OrgUnitKind.Executive, ExecJobs),
        new("CLINICAL", "Clinical",    "FOUNDER", OrgUnitKind.Function,  MedicalJobs),
        new("ENG",      "Engineering", "FOUNDER", OrgUnitKind.Function,  OperationsJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> StartupDistribution = new Dictionary<string, double>
    {
        ["FOUNDER"]  = 0.20,
        ["CLINICAL"] = 0.50,
        ["ENG"]      = 0.30
    };

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> SmeUnits =
    [
        new("EXEC",     "Executive", null,   OrgUnitKind.Executive, ExecJobs),
        new("CLINICAL", "Clinical",  "EXEC", OrgUnitKind.Function,  MedicalJobs),
        new("NURSING",  "Nursing",   "EXEC", OrgUnitKind.Function,  NursingJobs),
        new("PHARMACY", "Pharmacy",  "EXEC", OrgUnitKind.Function,  ClinicalSupportJobs),
        new("ADMIN",    "Admin & HR","EXEC", OrgUnitKind.Function,  HrJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> SmeDistribution = new Dictionary<string, double>
    {
        ["EXEC"]     = 0.08,
        ["CLINICAL"] = 0.35,
        ["NURSING"]  = 0.30,
        ["PHARMACY"] = 0.12,
        ["ADMIN"]    = 0.15
    };

    // Corporate-tier baseline OrgUnits — tertiary teaching-hospital archetype with
    // separate medical/nursing/clinical-support/allied-health divisions plus
    // outpatient/inpatient streams, emergency, operations, quality, finance, HR and IT.
    // Description / Budget / CostCenter / Purpose / Phone / Email mirror Banking's pattern.
    // The {Company} placeholder is substituted with the actual tenant name at row-emit time.
    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> CorporateUnits =
    [
        new("EXEC",             "Executive Office",         null,   OrgUnitKind.Executive, ExecJobs,
            Description: "Senior leadership of {Company} — Chief Executive, Chief Medical Officer, Chief Nursing Officer, Hospital Administrator, and Director of Nursing",
            BudgetMin: 1_000_000m, BudgetMax: 2_500_000m,
            CostCenter: "CC-EXEC-001",
            Purpose: "Set clinical strategy, regulatory compliance, financial sustainability, and patient-care standards across {Company}",
            Phone: "+233 30 222 4100", Email: "executive"),
        new("MEDICAL",          "Medical Affairs",          "EXEC", OrgUnitKind.Function,  MedicalJobs,
            Description: "All clinical departments at {Company} — Surgery, Internal Medicine, Paediatrics, O&G, Anaesthesia, Emergency, ICU and consultant teams",
            BudgetMin: 2_500_000m, BudgetMax: 5_500_000m,
            CostCenter: "CC-MED-001",
            Purpose: "Deliver evidence-based medical care across all specialties; supervise consultants, medical officers, and house officers; uphold {Company} clinical standards",
            Phone: "+233 30 222 4200", Email: "medical"),
        new("NURSING",          "Nursing Services",         "EXEC", OrgUnitKind.Function,  NursingJobs,
            Description: "Nursing operations across all {Company} wards, theatres, ICU, midwifery, and outpatient clinics",
            BudgetMin: 2_000_000m, BudgetMax: 4_500_000m,
            CostCenter: "CC-NUR-001",
            Purpose: "Provide round-the-clock nursing care; rostering across all wards and theatres; uphold infection prevention and patient-safety standards at {Company}",
            Phone: "+233 30 222 4300", Email: "nursing"),
        new("CLINICAL-SUPPORT", "Clinical Support Services","EXEC", OrgUnitKind.Function,  ClinicalSupportJobs,
            Description: "Pharmacy, laboratory, radiology, and pathology services that underpin all {Company} clinical care",
            BudgetMin: 1_200_000m, BudgetMax: 2_800_000m,
            CostCenter: "CC-CSS-001",
            Purpose: "Deliver timely, accurate diagnostics and medicines management for {Company} clinicians; manage formulary, lab quality, and imaging operations",
            Phone: "+233 30 222 4400", Email: "clinicalsupport"),
        new("ALLIED-HEALTH",    "Allied Health",            "EXEC", OrgUnitKind.Function,  AlliedHealthJobs,
            Description: "Physiotherapy, dietetics, clinical psychology, occupational therapy, and speech & language therapy services at {Company}",
            BudgetMin: 500_000m, BudgetMax: 1_200_000m,
            CostCenter: "CC-AH-001",
            Purpose: "Provide rehabilitation, nutrition, and psychosocial support to {Company} patients across inpatient and outpatient pathways",
            Phone: "+233 30 222 4500", Email: "alliedhealth"),
        new("OUTPATIENT",       "Outpatient Services",      "EXEC", OrgUnitKind.Function,  OutpatientJobs,
            Description: "All {Company} outpatient clinics, polyclinics, specialist OPD, and walk-in consultation services",
            BudgetMin: 800_000m, BudgetMax: 1_800_000m,
            CostCenter: "CC-OPD-001",
            Purpose: "Run the OPD throughput at {Company}; manage triage, consultation, NHIS claims, and patient flow across all clinics",
            Phone: "+233 30 222 4600", Email: "opd"),
        new("INPATIENT-WARDS",  "Inpatient Wards",          "EXEC", OrgUnitKind.Function,  InpatientJobs,
            Description: "All {Company} inpatient wards — male, female, paediatric, maternity, surgical, and private wards",
            BudgetMin: 1_500_000m, BudgetMax: 3_200_000m,
            CostCenter: "CC-IPD-001",
            Purpose: "Manage bed occupancy, ward rounds, discharge planning, and continuous nursing care across all {Company} inpatient units",
            Phone: "+233 30 222 4700", Email: "wards"),
        new("EMERGENCY",        "Emergency & Trauma",       "EXEC", OrgUnitKind.Function,  EmergencyJobs,
            Description: "24-hour Accident & Emergency department, trauma response, and acute resuscitation services at {Company}",
            BudgetMin: 900_000m, BudgetMax: 2_100_000m,
            CostCenter: "CC-EMG-001",
            Purpose: "Provide round-the-clock emergency, trauma, and resuscitation care; coordinate ambulance services and triage at {Company}",
            Phone: "+233 30 222 4800", Email: "emergency"),
        new("OPERATIONS",       "Operations & Facilities",  "EXEC", OrgUnitKind.Function,  OperationsJobs,
            Description: "Facilities management, biomedical engineering, procurement, stores, security, transport, and mortuary services at {Company}",
            BudgetMin: 700_000m, BudgetMax: 1_600_000m,
            CostCenter: "CC-OPS-001",
            Purpose: "Keep {Company} running — maintain medical equipment, clean wards, secure the premises, and supply consumables to every unit",
            Phone: "+233 30 222 4900", Email: "operations"),
        new("QUALITY-SAFETY",   "Quality & Patient Safety", "EXEC", OrgUnitKind.Function,  QualityJobs,
            Description: "Clinical governance, infection prevention, patient safety incident management, and HEFRA accreditation compliance at {Company}",
            BudgetMin: 250_000m, BudgetMax: 600_000m,
            CostCenter: "CC-QPS-001",
            Purpose: "Drive {Company} accreditation readiness, audit clinical standards, manage incidents, and embed continuous quality improvement",
            Phone: "+233 30 222 4950", Email: "quality"),
        new("FINANCE",          "Finance & Revenue Cycle",  "EXEC", OrgUnitKind.Function,  FinanceJobs,
            Description: "Financial reporting, NHIS claims processing, billing, cashiering, and revenue cycle management at {Company}",
            BudgetMin: 400_000m, BudgetMax: 900_000m,
            CostCenter: "CC-FIN-001",
            Purpose: "Produce {Company} financial statements; manage NHIS reimbursements; handle private billing and cash collections; safeguard hospital funds",
            Phone: "+233 30 222 4960", Email: "finance"),
        new("HR",               "Human Resources",          "EXEC", OrgUnitKind.Function,  HrJobs,
            Description: "Recruitment, training, payroll, GHS scheme management, and employee relations at {Company}",
            BudgetMin: 300_000m, BudgetMax: 700_000m,
            CostCenter: "CC-HR-001",
            Purpose: "Attract, develop, and retain clinical and non-clinical talent at {Company}; manage staff scheduling, training and welfare",
            Phone: "+233 30 222 4970", Email: "hr"),
        new("IT",               "Information Technology",   "EXEC", OrgUnitKind.Function,  ItJobs,
            Description: "EMR / hospital information systems, telemedicine, cybersecurity, and IT infrastructure at {Company}",
            BudgetMin: 350_000m, BudgetMax: 800_000m,
            CostCenter: "CC-IT-001",
            Purpose: "Run the {Company} EMR platform with high availability; secure patient data; deliver telemedicine and digital workflows to all units",
            Phone: "+233 30 222 4980", Email: "it")
    ];
    private static readonly IReadOnlyDictionary<string, double> CorporateDistribution = new Dictionary<string, double>
    {
        ["EXEC"]             = 0.03,
        ["MEDICAL"]          = 0.18,
        ["NURSING"]          = 0.32,
        ["CLINICAL-SUPPORT"] = 0.10,
        ["ALLIED-HEALTH"]    = 0.04,
        ["OUTPATIENT"]       = 0.07,
        ["INPATIENT-WARDS"]  = 0.10,
        ["EMERGENCY"]        = 0.05,
        ["OPERATIONS"]       = 0.05,
        ["QUALITY-SAFETY"]   = 0.01,
        ["FINANCE"]          = 0.02,
        ["HR"]               = 0.02,
        ["IT"]               = 0.01
    };

    private static readonly IReadOnlyList<OrgHierarchyBuilder.BaselineUnit> NonProfitUnits =
    [
        new("EXEC",     "Executive", null,   OrgUnitKind.Executive, ExecJobs),
        new("CLINICAL", "Clinical",  "EXEC", OrgUnitKind.Function,  MedicalJobs),
        new("NURSING",  "Nursing",   "EXEC", OrgUnitKind.Function,  NursingJobs),
        new("PROGRAMS", "Programs",  "EXEC", OrgUnitKind.Function,  AlliedHealthJobs),
        new("ADMIN",    "Admin & HR","EXEC", OrgUnitKind.Function,  HrJobs)
    ];
    private static readonly IReadOnlyDictionary<string, double> NonProfitDistribution = new Dictionary<string, double>
    {
        ["EXEC"]     = 0.10,
        ["CLINICAL"] = 0.40,
        ["NURSING"]  = 0.30,
        ["PROGRAMS"] = 0.15,
        ["ADMIN"]    = 0.05
    };

    // Curated job-title catalogue — ~55 roles covering executive, medical, nursing, clinical
    // support, allied health, allied admin, operations, finance, HR and IT functions in a
    // tertiary Ghana hospital. Codes are role-specific (no Cal Bank / "CB-" traces); pay
    // grades use MED-1..MED-10 for clinical and ADM-1..ADM-7 for non-clinical / admin
    // tracks. {Company} placeholder is substituted at row-emit time.
    private static readonly IReadOnlyList<JobTitleSpec> _jobTitles =
    [
        // ── Executive (Rank 5) ───────────────────────────────────────────────────
        new("CEO-001", "Chief Executive Officer", 5, 35_000m, 65_000m, "EXEC", null, true, "Master's Degree (MBA / MPH preferred)", 18,
            "Hospital Strategy, Healthcare Governance, Stakeholder Management, P&L Leadership, MoH Relations",
            "Chief executive accountable for the overall strategy, performance, regulatory standing, and stakeholder relationships of {Company}",
            "MED-10",
            "Set and execute the {Company} strategic plan; chair the executive management committee; manage Ministry of Health, HEFRA and NHIA relationships; drive financial sustainability",
            "Patient throughput, Operating margin, HEFRA accreditation rating, NHIS claims realisation rate, Staff engagement score",
            30),
        new("CMO-001", "Chief Medical Officer", 5, 32_000m, 60_000m, "EXEC", "CEO-001", true, "MD + Specialist Fellowship", 15,
            "Clinical Governance, Medical Strategy, GMDC Compliance, Multi-Specialty Leadership, Audit",
            "Senior clinical leader accountable for the quality and safety of all medical services delivered at {Company}",
            "MED-10",
            "Lead the {Company} medical workforce; chair the medical advisory committee; uphold GMDC and HEFRA standards; oversee clinical audit and credentialing",
            "Clinical mortality rate, Adverse event rate, Consultant productivity, Mortality & morbidity audit closure rate",
            30),
        new("CNO-001", "Chief Nursing Officer", 5, 28_000m, 52_000m, "EXEC", "CEO-001", true, "Master's in Nursing / Public Health", 15,
            "Nursing Strategy, Workforce Planning, Patient Safety, NMC Regulation, Quality Improvement",
            "Executive accountable for the nursing workforce strategy, patient safety, and standards of care at {Company}",
            "MED-10",
            "Lead {Company} nursing services; deliver workforce planning across wards and theatres; champion patient-safety culture; engage NMC on registration matters",
            "Nurse-to-patient ratio compliance, Pressure ulcer rate, Hand-hygiene audit score, Nurse turnover rate",
            30),
        new("HOSP-ADMIN-001", "Hospital Administrator", 5, 28_000m, 50_000m, "EXEC", "CEO-001", true, "Master's in Health Administration / MBA", 12,
            "Hospital Operations, Healthcare Finance, Facilities, Vendor Management, Performance Reporting",
            "Senior leader managing all non-clinical operations, facilities, and administrative services at {Company}",
            "ADM-7",
            "Oversee non-clinical operations across {Company}; manage facilities, security and procurement; deliver the operating budget; report performance to the board",
            "Operating cost per bed-day, Facility uptime, Procurement savings, Patient complaint resolution time",
            30),
        new("MED-DIR-001", "Medical Director", 5, 30_000m, 55_000m, "MEDICAL", "CMO-001", true, "MD + Specialist Fellowship", 12,
            "Multi-Specialty Coordination, Clinical Audit, Postgraduate Training, Theatre Scheduling",
            "Senior physician coordinating all medical departments and consultant rosters across {Company}",
            "MED-10",
            "Coordinate consultant rosters across departments; chair clinical governance meetings; supervise residents and house officers; manage referral pathways",
            "Theatre utilisation rate, Consultant clinic compliance, Resident exam pass rate, Audit recommendation closure",
            30),
        new("DON-001", "Director of Nursing", 5, 28_000m, 50_000m, "NURSING", "CNO-001", true, "Master's in Nursing", 12,
            "Nursing Operations, Rostering, Clinical Education, Performance Management",
            "Senior nursing leader running the day-to-day nursing operations across all wards and units of {Company}",
            "MED-10",
            "Run all {Company} nursing operations; manage matrons and ward managers; deliver continuing professional development; lead nursing audits",
            "Roster fill rate, Medication-error rate, Nursing CPD compliance, Ward audit score",
            30),

        // ── Heads of Department (Rank 4) ─────────────────────────────────────────
        new("HOD-SURG-001", "Head of Surgery", 4, 22_000m, 28_000m, "MEDICAL", "MED-DIR-001", true, "MD + Surgical Fellowship (FWACS / FGCS)", 12,
            "General Surgery, Sub-Specialty Coordination, Theatre Management, Surgical Audit, Trainee Supervision",
            "Consultant surgeon leading the Department of Surgery and all surgical sub-specialties at {Company}",
            "MED-9",
            "Lead Department of Surgery; chair theatre scheduling committee; supervise surgical residents; lead surgical audit; manage sub-specialty consultants",
            "Theatre utilisation, Surgical site infection rate, 30-day surgical mortality, Resident pass rate",
            27),
        new("HOD-IM-001", "Head of Internal Medicine", 4, 20_000m, 26_000m, "MEDICAL", "MED-DIR-001", true, "MD + Internal Medicine Fellowship", 12,
            "Internal Medicine, Cardiology, Nephrology, Clinical Audit, Postgraduate Training",
            "Consultant physician leading the Department of Internal Medicine and its sub-specialties at {Company}",
            "MED-9",
            "Lead Department of Internal Medicine; coordinate sub-specialty clinics; supervise residents; chair M&M meetings; oversee inpatient medical care",
            "Average length of stay (medical), Readmission rate, Resident exam pass rate, Clinic compliance",
            27),
        new("HOD-PAED-001", "Head of Paediatrics", 4, 20_000m, 26_000m, "MEDICAL", "MED-DIR-001", true, "MD + Paediatric Fellowship", 12,
            "Paediatrics, Neonatology, Child Health, Vaccination Programmes, Trainee Supervision",
            "Consultant paediatrician leading the Department of Paediatrics and Child Health at {Company}",
            "MED-9",
            "Lead Department of Paediatrics; oversee neonatal and paediatric wards; supervise trainees; coordinate immunisation services; lead child-protection cases",
            "Under-5 mortality rate, Neonatal mortality, EPI coverage, Child-protection case turnaround",
            27),
        new("HOD-OBG-001", "Head of Obstetrics & Gynaecology", 4, 21_000m, 27_000m, "MEDICAL", "MED-DIR-001", true, "MD + O&G Fellowship", 12,
            "Obstetrics, Gynaecology, Maternal Health, High-Risk Pregnancy, Surgical Skills",
            "Consultant obstetrician-gynaecologist leading the O&G department and labour ward at {Company}",
            "MED-9",
            "Lead the O&G department; oversee labour ward and gynae theatres; manage high-risk pregnancies; supervise registrars; lead maternal-mortality reviews",
            "Maternal mortality ratio, Caesarean section rate, Stillbirth rate, Labour ward acuity index",
            27),
        new("HOD-ANAES-001", "Head of Anaesthesia", 4, 21_000m, 27_000m, "MEDICAL", "MED-DIR-001", true, "MD + Anaesthesia Fellowship", 12,
            "General Anaesthesia, Regional Blocks, Peri-Operative Care, ICU Liaison, Pain Management",
            "Consultant anaesthesiologist leading the anaesthesia service and pain clinic at {Company}",
            "MED-9",
            "Lead anaesthesia coverage across all theatres; manage anaesthesia roster; oversee pre-op clinics; run the pain service; supervise anaesthesia residents",
            "Anaesthesia-related complication rate, Pre-op assessment compliance, Theatre on-time start, Pain-clinic satisfaction",
            27),
        new("HOD-EM-001", "Head of Emergency Medicine", 4, 20_000m, 26_000m, "EMERGENCY", "MED-DIR-001", true, "MD + Emergency Medicine Fellowship", 10,
            "Emergency Medicine, Trauma Care, Triage Systems, Resuscitation, Disaster Response",
            "Consultant leading the Accident & Emergency department and trauma response at {Company}",
            "MED-9",
            "Lead A&E operations; standardise triage; oversee resuscitation training; coordinate disaster response drills; chair emergency M&M reviews",
            "Door-to-doctor time, Emergency mortality rate, Triage accuracy, Sentinel-event closure rate",
            27),
        new("HOD-ICU-001", "Head of Intensive Care Unit", 4, 22_000m, 28_000m, "MEDICAL", "MED-DIR-001", true, "MD + Critical Care Fellowship", 12,
            "Critical Care, Ventilation Management, Sepsis Protocols, Multi-Organ Support",
            "Consultant intensivist leading the multi-disciplinary ICU at {Company}",
            "MED-9",
            "Lead ICU clinical operations; manage admission criteria; chair daily multi-disciplinary rounds; oversee ICU sepsis bundles; mentor ICU fellows",
            "ICU mortality rate, Ventilator-associated pneumonia rate, Bed turnover, Bundle compliance",
            27),
        new("HOD-PHARM-001", "Head of Pharmacy", 4, 18_000m, 24_000m, "CLINICAL-SUPPORT", "HOSP-ADMIN-001", true, "Doctor of Pharmacy (PharmD)", 10,
            "Hospital Pharmacy, Formulary Management, Antimicrobial Stewardship, Inventory, NHIS Drug List",
            "Senior pharmacist leading all pharmacy services at {Company} including dispensing, clinical pharmacy, and procurement",
            "MED-9",
            "Lead pharmacy operations; chair formulary committee; run antimicrobial stewardship; manage drug procurement; supervise hospital and OPD dispensaries",
            "Stock-out rate, Formulary compliance, Antimicrobial stewardship metric, Dispensing error rate",
            27),
        new("HOD-LAB-001", "Head of Laboratory", 4, 17_000m, 23_000m, "CLINICAL-SUPPORT", "HOSP-ADMIN-001", true, "MSc Medical Laboratory Sciences", 10,
            "Clinical Pathology, Lab Quality Systems, ISO 15189, Equipment Maintenance, Staff Training",
            "Senior laboratory scientist leading all in-house laboratory services and quality systems at {Company}",
            "MED-9",
            "Lead laboratory operations across all disciplines; maintain ISO 15189 quality system; manage reagent procurement; supervise lab scientists and technicians",
            "Lab turnaround time, External quality assessment score, Critical value notification rate, Equipment downtime",
            27),
        new("HOD-RAD-001", "Head of Radiology & Imaging", 4, 22_000m, 28_000m, "CLINICAL-SUPPORT", "MED-DIR-001", true, "MD + Radiology Fellowship", 10,
            "Diagnostic Radiology, Cross-Sectional Imaging, Interventional Procedures, Department Management",
            "Consultant radiologist leading diagnostic and interventional imaging services at {Company}",
            "MED-9",
            "Lead radiology services; manage CT, MRI and ultrasound rosters; oversee reporting standards; supervise radiographers and sonographers; chair imaging audits",
            "Imaging turnaround time, Report accuracy peer-review, Equipment uptime, Patient throughput",
            27),
        new("HOD-PATH-001", "Head of Pathology", 4, 21_000m, 27_000m, "CLINICAL-SUPPORT", "MED-DIR-001", true, "MD + Pathology Fellowship", 10,
            "Histopathology, Cytology, Autopsy, Tumour Board Coordination",
            "Consultant pathologist leading histology, cytology, and post-mortem services at {Company}",
            "MED-9",
            "Lead pathology operations; report histology and cytology specimens; perform autopsies; coordinate tumour board reviews; supervise lab scientists",
            "Histology turnaround time, Tumour-board attendance, Diagnostic concordance, Autopsy completion rate",
            27),
        new("HOD-PHYSIO-001", "Head of Physiotherapy", 4, 14_000m, 19_000m, "ALLIED-HEALTH", "HOSP-ADMIN-001", true, "MSc Physiotherapy", 10,
            "Musculoskeletal Therapy, Neuro-Rehab, Cardiopulmonary Rehab, Department Management",
            "Senior physiotherapist leading the rehabilitation department and outpatient physio services at {Company}",
            "ADM-7",
            "Lead physiotherapy department; coordinate inpatient rehab rounds; manage outpatient bookings; supervise junior therapists; develop care pathways",
            "Treatment session volume, Patient functional outcome score, OPD waiting time, Discharge readiness rate",
            27),

        // ── Senior Clinical (Rank 4) ─────────────────────────────────────────────
        new("CONS-SURG-001", "Consultant Surgeon", 4, 18_000m, 26_000m, "MEDICAL", "HOD-SURG-001", true, "MD + Surgical Fellowship", 8,
            "General Surgery, Sub-Specialty Procedures, Operating Theatre, Trainee Teaching",
            "Specialist surgeon performing complex surgical procedures and supervising trainees at {Company}",
            "MED-8",
            "Run consultant clinics and theatre lists; perform complex elective and emergency surgery; supervise residents; participate in M&M reviews",
            "Theatre case volume, Surgical complication rate, Length of stay (surgical), Trainee feedback score",
            27),
        new("CONS-IM-001", "Consultant Physician", 4, 17_000m, 25_000m, "MEDICAL", "HOD-IM-001", true, "MD + Internal Medicine Fellowship", 8,
            "Internal Medicine, Sub-Specialty Clinics, Inpatient Management, Teaching",
            "Specialist physician managing complex internal medicine cases and supervising trainees at {Company}",
            "MED-8",
            "Run consultant clinics and ward rounds; manage complex medical admissions; supervise residents and HOs; lead disease-specific protocols",
            "Length of stay, Readmission rate, Mortality index, Clinic completion rate",
            27),
        new("CONS-PAED-001", "Consultant Paediatrician", 4, 17_000m, 25_000m, "MEDICAL", "HOD-PAED-001", true, "MD + Paediatric Fellowship", 8,
            "General Paediatrics, Neonatology, Outpatient Clinics, Vaccinations",
            "Specialist paediatrician managing inpatient and outpatient paediatric services at {Company}",
            "MED-8",
            "Run paediatric clinics and ward rounds; manage neonatal cases; supervise residents; coordinate child-protection assessments",
            "Paediatric mortality, Immunisation coverage, Clinic compliance, Resident teaching feedback",
            27),
        new("CONS-OBG-001", "Consultant Obstetrician-Gynaecologist", 4, 18_000m, 26_000m, "MEDICAL", "HOD-OBG-001", true, "MD + O&G Fellowship", 8,
            "Obstetrics, Gynae Surgery, Antenatal Care, Family Planning",
            "Specialist obstetrician-gynaecologist managing pregnancies, deliveries, and gynae surgery at {Company}",
            "MED-8",
            "Run antenatal and gynae clinics; perform caesarean sections and gynae surgery; manage high-risk pregnancies; supervise midwives and registrars",
            "Caesarean rate, Maternal complication rate, Stillbirth rate, Antenatal coverage",
            27),
        new("CONS-ANAES-001", "Consultant Anaesthesiologist", 4, 18_000m, 26_000m, "MEDICAL", "HOD-ANAES-001", true, "MD + Anaesthesia Fellowship", 8,
            "Anaesthesia, ICU Coverage, Pre-Op Clinics, Pain Management",
            "Specialist anaesthesiologist providing peri-operative anaesthesia and ICU support at {Company}",
            "MED-8",
            "Provide anaesthesia for major surgery; cover ICU on-call; run pre-op assessment clinic; manage pain service; supervise anaesthesia residents",
            "Anaesthesia complication rate, Pre-op assessment compliance, On-call response time",
            27),
        new("CONS-EM-001", "Consultant in Emergency Medicine", 4, 16_000m, 24_000m, "EMERGENCY", "HOD-EM-001", true, "MD + Emergency Medicine Fellowship", 8,
            "Emergency Care, Trauma, Resuscitation, Toxicology",
            "Specialist emergency physician leading shift teams in the A&E department at {Company}",
            "MED-8",
            "Lead A&E shifts; run resuscitation cases; coordinate inter-hospital transfers; supervise emergency residents; debrief on critical incidents",
            "Door-to-decision time, Resuscitation outcome, Sentinel events, Shift incident rate",
            27),

        new("WARD-MGR-001", "Ward Manager", 4, 14_000m, 18_000m, "INPATIENT-WARDS", "DON-001", true, "BSc Nursing + Management Course", 8,
            "Ward Operations, Rostering, Clinical Audit, Infection Prevention, Patient Flow",
            "Senior nurse managing all clinical and administrative operations of an inpatient ward at {Company}",
            "MED-7",
            "Manage ward roster and bed allocation; lead daily ward rounds with consultants; oversee infection prevention; report ward KPIs to matron",
            "Bed-occupancy rate, Length of stay, Pressure-ulcer rate, Patient-satisfaction score",
            27),
        new("MATRON-001", "Matron", 4, 16_000m, 22_000m, "NURSING", "DON-001", true, "BSc Nursing + Master's Preferred", 10,
            "Nursing Leadership, Quality Audit, Mentorship, Compliance, Discipline",
            "Senior nurse manager overseeing several wards or a clinical division at {Company}",
            "MED-8",
            "Supervise multiple ward managers; lead nursing audits; chair disciplinary panels; coach senior nurses; report to the Director of Nursing",
            "Ward-audit pass rate, Staff-grievance closure time, Mentee retention, Nursing CPD attendance",
            27),
        new("ADON-001", "Assistant Director of Nursing", 4, 18_000m, 24_000m, "NURSING", "DON-001", true, "Master's in Nursing", 10,
            "Workforce Planning, Policy Development, Quality Assurance, Stakeholder Engagement",
            "Deputy nursing leader supporting the DON in workforce, policy and quality oversight at {Company}",
            "MED-9",
            "Deputise for DON; lead workforce-planning cycle; develop nursing policies; chair quality-assurance meetings; manage NMC registration tracking",
            "Vacancy fill time, Policy refresh rate, NMC registration compliance, Audit closure",
            27),
        new("FAC-MGR-001", "Facilities Manager", 4, 14_000m, 19_000m, "OPERATIONS", "HOSP-ADMIN-001", true, "BSc Engineering / Facilities Management", 8,
            "Hospital Facilities, Utilities, HVAC, Medical Gas, Generator Management, Vendor Coordination",
            "Senior manager responsible for hospital buildings, utilities, and engineering services at {Company}",
            "ADM-7",
            "Run hospital facilities including HVAC, medical gas and power; manage maintenance contracts; coordinate building projects; respond to engineering incidents",
            "Facility uptime, Generator availability, Medical-gas continuity, Maintenance backlog",
            27),
        new("HR-MGR-001", "HR Manager", 4, 14_000m, 19_000m, "HR", "HOSP-ADMIN-001", true, "Master's HR / Bachelor's + IHRMP", 8,
            "Healthcare HR, GHS Scheme, Recruitment, Industrial Relations, Performance Management",
            "Senior HR leader managing the people function across {Company}",
            "ADM-7",
            "Run end-to-end HR cycle; manage GHS conditions of service; lead recruitment for clinical and non-clinical roles; handle industrial relations",
            "Time-to-hire, Staff turnover, Engagement score, Grievance closure rate",
            27),
        new("IT-MGR-001", "IT Manager", 4, 15_000m, 20_000m, "IT", "HOSP-ADMIN-001", true, "BSc Computer Science / IT", 8,
            "Hospital Information Systems, EMR, Networking, Cybersecurity, Vendor Management",
            "Senior IT leader running the EMR platform, network, and digital services at {Company}",
            "ADM-7",
            "Operate the {Company} EMR platform; manage IT vendors and SLAs; secure patient data; deliver digital projects; support clinical IT users",
            "EMR uptime, Incident MTTR, Cybersecurity audit score, Project delivery rate",
            27),
        new("HOSP-ACCT-001", "Hospital Accountant", 4, 12_000m, 17_000m, "FINANCE", "HOSP-ADMIN-001", true, "ACCA / CA Ghana / ICAG", 8,
            "Hospital Finance, IFRS, NHIS Claims, Budgeting, Audit",
            "Senior accountant overseeing the financial function and revenue cycle at {Company}",
            "ADM-7",
            "Produce monthly financial reports; manage NHIS claims reconciliation; lead budget cycle; coordinate external audit; maintain fixed-asset register",
            "Budget variance, NHIS realisation rate, Audit findings, Report timeliness",
            27),

        // ── Mid-level Clinical (Rank 3) ──────────────────────────────────────────
        new("SMO-001", "Senior Medical Officer", 3, 12_000m, 15_000m, "MEDICAL", "MED-DIR-001", false, "MD + 5 yrs experience", 5,
            "General Medicine, Outpatient Care, Inpatient Coverage, Trainee Supervision",
            "Senior non-specialist physician supporting consultants across departments at {Company}",
            "MED-5",
            "Cover OPD and inpatient duties; supervise medical officers and house officers; assist in theatres; participate in audit",
            "Patient throughput, Documentation compliance, Audit findings, Trainee feedback",
            24),
        new("MO-001", "Medical Officer", 3, 8_000m, 13_000m, "MEDICAL", "SMO-001", false, "MD + Housemanship Completed", 2,
            "General Medicine, Ward Rounds, Procedures, Documentation",
            "General duty medical officer providing front-line care across departments at {Company}",
            "MED-4",
            "Conduct ward rounds; perform admissions and reviews; carry out minor procedures; participate in on-call rota; document care in the EMR",
            "Ward review timeliness, On-call coverage, Documentation accuracy, Notifiable-disease reporting",
            24),
        new("MO-OPD-001", "Medical Officer, Outpatient", 3, 8_000m, 12_000m, "OUTPATIENT", "SMO-001", false, "MD + Housemanship Completed", 2,
            "Outpatient Care, NHIS Documentation, Triage, Referral Management",
            "Medical officer based in the outpatient department managing walk-in and appointment cases at {Company}",
            "MED-4",
            "See OPD patients across morning and afternoon clinics; document NHIS encounters; refer complex cases; supervise OPD nurses",
            "OPD patients per session, NHIS encounter capture, Referral quality, Patient satisfaction",
            24),
        new("PHARM-SR-001", "Senior Pharmacist", 3, 9_000m, 13_000m, "CLINICAL-SUPPORT", "HOD-PHARM-001", true, "BPharm / PharmD + 5 yrs", 5,
            "Clinical Pharmacy, Antimicrobial Stewardship, Ward Rounds, Counselling",
            "Senior pharmacist leading clinical pharmacy services and ward-based medication review at {Company}",
            "MED-6",
            "Conduct ward-based medication review; supervise interns; lead AMS rounds; manage formulary additions; counsel complex patients",
            "Medication-error rate, Intervention acceptance, AMS adherence, Counselling sessions",
            24),
        new("PHARM-001", "Pharmacist", 3, 6_500m, 10_000m, "CLINICAL-SUPPORT", "PHARM-SR-001", false, "BPharm / PharmD", 2,
            "Dispensing, Patient Counselling, Drug Information, Inventory",
            "Registered pharmacist dispensing medications and counselling patients at {Company}",
            "MED-4",
            "Dispense outpatient and inpatient prescriptions; counsel patients on adherence; check stock levels; document interventions",
            "Dispensing accuracy, Counselling rate, Stock-out incidents, Prescription turnaround",
            24),
        new("LAB-SCI-SR-001", "Senior Medical Laboratory Scientist", 3, 8_500m, 12_000m, "CLINICAL-SUPPORT", "HOD-LAB-001", true, "BSc Med Lab Sciences + 5 yrs", 5,
            "Clinical Chemistry, Haematology, Microbiology, ISO 15189, Internal QC",
            "Senior lab scientist leading a discipline (chem / haem / micro) within the {Company} laboratory",
            "MED-6",
            "Run a lab discipline; validate results; manage QC; troubleshoot equipment; mentor junior scientists",
            "QC pass rate, EQA performance, Result turnaround, Equipment downtime",
            24),
        new("LAB-SCI-001", "Medical Laboratory Scientist", 3, 6_000m, 9_500m, "CLINICAL-SUPPORT", "LAB-SCI-SR-001", false, "BSc Med Lab Sciences", 2,
            "Lab Diagnostics, Specimen Analysis, Quality Control, Equipment Operation",
            "Registered lab scientist running diagnostic tests across multiple disciplines at {Company}",
            "MED-4",
            "Process and analyse clinical specimens; perform daily QC; flag critical values; maintain equipment logs",
            "Result turnaround, Critical-value reporting, QC compliance, Sample-rejection rate",
            24),
        new("RADIOG-SR-001", "Senior Radiographer", 3, 8_500m, 12_000m, "CLINICAL-SUPPORT", "HOD-RAD-001", true, "BSc Radiography + 5 yrs", 5,
            "Cross-Sectional Imaging, CT, MRI, Quality Assurance, Trainee Supervision",
            "Senior radiographer running advanced imaging modalities (CT / MRI) and supervising junior staff at {Company}",
            "MED-6",
            "Operate CT and MRI scanners; lead radiation-safety audits; mentor junior radiographers; participate in modality QC",
            "Image-quality audit, Throughput, Radiation-dose compliance, Equipment uptime",
            24),
        new("RADIOG-001", "Radiographer", 3, 6_000m, 9_500m, "CLINICAL-SUPPORT", "RADIOG-SR-001", false, "BSc Radiography", 2,
            "X-Ray, Fluoroscopy, Ultrasound Support, Patient Positioning",
            "Registered radiographer performing diagnostic imaging examinations at {Company}",
            "MED-4",
            "Carry out X-ray and fluoroscopy studies; position patients; protect against radiation exposure; support reporting workflow",
            "Examinations per shift, Reject rate, Radiation safety compliance, Patient feedback",
            24),
        new("SONO-001", "Sonographer", 3, 6_500m, 10_000m, "CLINICAL-SUPPORT", "HOD-RAD-001", false, "BSc Sonography / Radiography + Ultrasound Cert", 3,
            "Obstetric Ultrasound, Abdominal, Vascular, Echocardiography",
            "Sonographer performing diagnostic ultrasound examinations across specialties at {Company}",
            "MED-4",
            "Perform obstetric, abdominal and vascular ultrasounds; produce structured reports; manage scan bookings; train assistants",
            "Studies per session, Report concordance, Booking-to-scan time, Patient feedback",
            24),
        new("PATH-001", "Pathologist Assistant / Mortuary Officer", 3, 4_500m, 7_500m, "CLINICAL-SUPPORT", "HOD-PATH-001", false, "BSc Med Lab Sciences / Anatomic Path", 3,
            "Specimen Handling, Histology Prep, Mortuary Procedures, Documentation",
            "Pathology assistant supporting histology preparation and mortuary services at {Company}",
            "MED-3",
            "Receive and prepare specimens for histology; assist at autopsy; manage mortuary register; release bodies to families",
            "Specimen integrity, Histology TAT, Mortuary turnaround, Documentation accuracy",
            24),
        new("SPEC-NURSE-001", "Specialist Nurse", 3, 7_000m, 11_000m, "NURSING", "MATRON-001", false, "BSc Nursing + Specialty Cert (ICU/ED/Theatre)", 5,
            "Specialty Nursing, Advanced Procedures, Mentorship, Protocol Development",
            "Senior nurse with advanced post-graduate certification practising in a specialty area at {Company}",
            "MED-5",
            "Deliver specialty nursing care; mentor junior nurses; develop specialty protocols; participate in audit; support trainees",
            "Specialty audit score, Protocol compliance, Mentee progression, CPD hours",
            24),
        new("ICU-NURSE-001", "ICU Nurse", 3, 6_500m, 10_000m, "NURSING", "WARD-MGR-001", false, "BSc Nursing + ICU Course", 3,
            "Critical Care, Ventilator Management, Inotrope Titration, Sepsis Bundle",
            "Critical-care nurse caring for ventilated and high-dependency patients in the ICU at {Company}",
            "MED-4",
            "Monitor critically ill patients on ventilators; titrate vasoactive drugs; deliver bundle care; document hourly observations",
            "Bundle compliance, Pressure-ulcer rate, Medication-error rate, Documentation accuracy",
            24),
        new("THEATRE-NURSE-001", "Theatre Nurse / Scrub Nurse", 3, 5_500m, 9_000m, "NURSING", "WARD-MGR-001", false, "BSc Nursing + Theatre Course", 3,
            "Surgical Scrub, Instrument Management, Sterile Technique, WHO Surgical Checklist",
            "Operating-theatre nurse supporting surgeons and anaesthetists during surgical procedures at {Company}",
            "MED-4",
            "Scrub for surgical cases; manage instrument trays; uphold sterile technique; complete WHO checklist; restock theatre",
            "Surgical-checklist compliance, Instrument-count accuracy, Theatre turnover time, Sterility audits",
            24),
        new("NA-001", "Nurse Anaesthetist", 3, 7_000m, 11_000m, "NURSING", "HOD-ANAES-001", false, "BSc Nursing + Nurse Anaesthesia Programme", 4,
            "Anaesthesia, Airway Management, Drug Calculations, Peri-Op Monitoring",
            "Specialist nurse anaesthetist delivering anaesthesia under consultant supervision at {Company}",
            "MED-5",
            "Administer general and regional anaesthesia under supervision; monitor peri-op patients; manage airways; support theatre throughput",
            "Anaesthesia complications, Pre-op compliance, Theatre turnover, Documentation rate",
            24),
        new("MIDWIFE-SR-001", "Senior Midwife", 3, 6_500m, 10_000m, "NURSING", "MATRON-001", false, "Diploma / BSc Midwifery + 5 yrs", 5,
            "Antenatal, Labour, Postnatal, Neonatal Resuscitation, Family Planning",
            "Senior midwife leading labour-ward shifts and antenatal clinics at {Company}",
            "MED-5",
            "Lead labour-ward shifts; conduct antenatal and family-planning clinics; mentor junior midwives; perform neonatal resuscitation",
            "Stillbirth rate, Maternal complications, Neonatal resuscitation success, Antenatal coverage",
            24),
        new("MIDWIFE-001", "Midwife", 3, 4_500m, 8_000m, "NURSING", "MIDWIFE-SR-001", false, "Diploma / BSc Midwifery", 2,
            "Antenatal Care, Delivery, Postnatal Care, Newborn Care",
            "Registered midwife conducting deliveries and providing antenatal and postnatal care at {Company}",
            "MED-3",
            "Conduct normal deliveries; provide antenatal and postnatal care; counsel mothers; document maternity records",
            "Deliveries conducted, Documentation accuracy, Antenatal coverage, Postnatal follow-up",
            24),
        new("PHYSIO-SR-001", "Senior Physiotherapist", 3, 7_000m, 11_000m, "ALLIED-HEALTH", "HOD-PHYSIO-001", false, "BSc Physiotherapy + 5 yrs", 5,
            "Neuro-Rehab, MSK, Manual Therapy, Cardiopulmonary Rehab",
            "Senior physiotherapist leading complex rehabilitation cases and supervising juniors at {Company}",
            "MED-5",
            "Manage complex inpatient and outpatient cases; lead rehab MDT meetings; supervise juniors; develop care pathways",
            "Functional outcome score, Caseload throughput, Patient satisfaction, Mentee progression",
            24),
        new("PHYSIO-001", "Physiotherapist", 3, 5_000m, 8_500m, "ALLIED-HEALTH", "PHYSIO-SR-001", false, "BSc Physiotherapy", 2,
            "Musculoskeletal Therapy, Exercise Prescription, Manual Therapy, Patient Education",
            "Registered physiotherapist treating inpatient and outpatient cases at {Company}",
            "MED-3",
            "Assess and treat MSK / neuro / cardiopulmonary patients; prescribe home exercise programmes; document interventions; refer back to clinicians",
            "Treatment sessions, Patient outcome, Documentation, OPD waiting time",
            24),
        new("DIET-001", "Dietitian", 3, 4_500m, 7_500m, "ALLIED-HEALTH", "HOD-PHYSIO-001", false, "BSc Nutrition & Dietetics", 2,
            "Clinical Nutrition, Diabetes Counselling, Enteral Feeding, Therapeutic Diets",
            "Registered dietitian providing clinical nutrition assessment and counselling at {Company}",
            "MED-3",
            "Assess nutritional status of inpatients; design therapeutic diets; counsel diabetes and renal patients; support enteral feeding plans",
            "Assessment timeliness, Therapeutic-diet compliance, Counselling sessions, Outcome tracking",
            24),
        new("PSYCH-001", "Clinical Psychologist", 3, 6_000m, 10_000m, "ALLIED-HEALTH", "HOD-PHYSIO-001", false, "MPhil Clinical Psychology", 3,
            "Mental Health Assessment, CBT, Psychometric Testing, Crisis Intervention",
            "Clinical psychologist providing assessment and therapy across inpatient and outpatient services at {Company}",
            "MED-4",
            "Conduct psychological assessments; deliver CBT and other therapies; provide crisis support; collaborate with psychiatry team",
            "Therapy completion rate, Outcome measure improvement, Referral turnaround, Crisis response",
            24),
        new("OT-001", "Occupational Therapist", 3, 5_000m, 8_500m, "ALLIED-HEALTH", "HOD-PHYSIO-001", false, "BSc Occupational Therapy", 2,
            "Activities of Daily Living, Splinting, Cognitive Rehab, Discharge Planning",
            "Occupational therapist enabling functional independence for {Company} patients post-illness or injury",
            "MED-3",
            "Assess ADL performance; provide splinting and adaptive devices; deliver cognitive rehab; support discharge planning",
            "Functional outcome, Discharge readiness, Equipment provision time, Patient satisfaction",
            24),
        new("SLT-001", "Speech & Language Therapist", 3, 5_000m, 8_500m, "ALLIED-HEALTH", "HOD-PHYSIO-001", false, "BSc Speech & Language Therapy", 2,
            "Dysphagia, Aphasia, Paediatric Communication, Voice Therapy",
            "Registered SLT supporting communication and swallowing rehabilitation at {Company}",
            "MED-3",
            "Assess and treat dysphagia and communication disorders; advise on safe-feeding plans; deliver paediatric language interventions; train families",
            "Dysphagia screening rate, Outcome score, Aspiration-pneumonia rate, Caseload throughput",
            24),
        new("EMR-001", "Health Informatics / EMR Officer", 3, 5_500m, 9_500m, "IT", "IT-MGR-001", false, "BSc Health Informatics / IT", 3,
            "EMR Configuration, Health Data, Reporting, Clinical Workflow Mapping",
            "Specialist managing the {Company} EMR platform configuration, training, and reporting",
            "ADM-5",
            "Configure EMR templates; train clinical users; build operational reports; troubleshoot EMR incidents; coordinate vendor patches",
            "EMR adoption rate, Training coverage, Incident MTTR, Report-delivery SLA",
            24),
        new("IT-OFF-001", "IT Officer", 3, 4_500m, 7_500m, "IT", "IT-MGR-001", false, "BSc Computer Science / Diploma", 2,
            "Helpdesk, Networking, Hardware Support, Active Directory",
            "Front-line IT officer supporting end-users and infrastructure across {Company}",
            "ADM-4",
            "Resolve helpdesk tickets; maintain printers and PCs; support network endpoints; manage user accounts; assist with EMR issues",
            "First-call resolution, Incident MTTR, Ticket backlog, User-satisfaction score",
            24),
        new("PROC-001", "Procurement Officer", 3, 4_500m, 8_000m, "OPERATIONS", "FAC-MGR-001", false, "Bachelor's + CIPS Foundation", 3,
            "Procurement, PPA Compliance, Vendor Management, Tender Process",
            "Procurement officer running tendering, contract awards, and supplier management for {Company}",
            "ADM-5",
            "Run RFQs and tenders per PPA Act; evaluate bids; issue purchase orders; manage supplier performance; report savings",
            "Procurement-cycle time, PPA compliance, Cost savings, Vendor performance",
            24),
        new("STORES-001", "Stores / Inventory Officer", 3, 3_500m, 6_000m, "OPERATIONS", "PROC-001", false, "HND / Bachelor's + Stores Cert", 2,
            "Medical Stores, Cold-Chain, Stock Reconciliation, FEFO",
            "Stores officer managing medical and non-medical inventory across {Company}",
            "ADM-3",
            "Receive and issue stock; maintain cold-chain integrity; reconcile inventory; manage FEFO; raise replenishment requests",
            "Stock-out rate, Stock variance, Cold-chain compliance, Issue turnaround",
            24),
        new("HRO-OFF-001", "HR Officer", 3, 4_500m, 7_500m, "HR", "HR-MGR-001", false, "Bachelor's + HR Course", 2,
            "Recruitment, Records, Onboarding, Leave Management, GHS Scheme",
            "HR officer running day-to-day people operations across {Company}",
            "ADM-4",
            "Coordinate recruitment campaigns; onboard new staff; maintain personnel files; manage leave records; respond to staff queries",
            "Time-to-hire, Records accuracy, Onboarding satisfaction, Leave-balance accuracy",
            24),
        new("TRAINING-001", "Training & Development Officer", 3, 5_000m, 8_000m, "HR", "HR-MGR-001", false, "Bachelor's + L&D Cert", 3,
            "Continuing Professional Development, Training Design, Adult Learning, Evaluation",
            "L&D specialist designing and delivering training for clinical and non-clinical staff at {Company}",
            "ADM-5",
            "Run training-needs analysis; design CPD programmes; deliver workshops; evaluate impact; manage external trainer contracts",
            "CPD coverage, Training-evaluation score, Skill uplift, Cost per learner",
            24),
        new("ACCT-001", "Accountant", 3, 5_500m, 9_000m, "FINANCE", "HOSP-ACCT-001", false, "ACCA part-qual / BCom Accounting", 3,
            "Financial Reporting, Reconciliations, IFRS, Audit Support",
            "Qualified accountant preparing financial reports and reconciliations for {Company}",
            "ADM-5",
            "Prepare monthly trial balance; reconcile bank and supplier accounts; maintain fixed-asset register; support external audit",
            "Closing-cycle days, Reconciliation accuracy, Audit findings, Report timeliness",
            24),
        new("QSO-001", "Quality & Safety Officer", 3, 5_500m, 9_500m, "QUALITY-SAFETY", "HOSP-ADMIN-001", false, "BSc Healthcare + QI / Safety Cert", 3,
            "Clinical Audit, Patient Safety, Incident Investigation, HEFRA Standards",
            "Specialist driving the patient-safety and quality programme across {Company}",
            "ADM-5",
            "Run clinical audits; investigate incidents; coordinate HEFRA accreditation; coach teams on QI; chair patient-safety meetings",
            "Audit-cycle closure, Sentinel-event closure, Accreditation readiness, QI projects completed",
            24),
        new("ICN-001", "Infection Prevention & Control Nurse", 3, 5_500m, 9_500m, "QUALITY-SAFETY", "QSO-001", false, "BSc Nursing + IPC Cert", 4,
            "Infection Control, Hand Hygiene, Outbreak Response, Surveillance",
            "Specialist nurse leading infection prevention and control across {Company}",
            "MED-4",
            "Conduct hand-hygiene audits; investigate HAI clusters; train staff on PPE; lead outbreak response; report surveillance metrics",
            "Hand-hygiene compliance, HAI rate, Outbreak response time, Training coverage",
            24),
        new("ME-001", "Monitoring & Evaluation Officer", 3, 5_000m, 8_500m, "QUALITY-SAFETY", "QSO-001", false, "Bachelor's + M&E / Public Health", 3,
            "Health Indicators, Data Quality, Reporting Frameworks, DHIMS-2",
            "M&E specialist tracking performance against MoH and donor indicators at {Company}",
            "ADM-5",
            "Build performance dashboards; submit DHIMS-2 returns; support donor reporting; lead data-quality audits",
            "Indicator completeness, Report-submission timeliness, Data-quality score, Dashboard adoption",
            24),
        new("PAO-001", "Patient Affairs Officer", 3, 4_000m, 6_500m, "OUTPATIENT", "HOSP-ADMIN-001", false, "Bachelor's + Customer-Service Cert", 2,
            "Patient Liaison, Complaints Handling, NHIS Eligibility, Multi-Lingual Communication",
            "Front-of-house officer supporting patients with non-clinical concerns and NHIS issues at {Company}",
            "ADM-4",
            "Liaise with patients and families; resolve complaints; assist with NHIS eligibility; coordinate translations; escalate as needed",
            "Complaint-resolution time, Patient-satisfaction score, NHIS query closure, Escalation rate",
            24),
        new("HRO-001", "Health Records Officer", 3, 3_500m, 6_000m, "QUALITY-SAFETY", "QSO-001", false, "Diploma / Bachelor's Health Records", 2,
            "Coding (ICD-10), Records Management, Confidentiality, EMR Documentation",
            "Health-records professional managing the integrity, coding, and retrieval of {Company} clinical records",
            "ADM-3",
            "Code diagnoses to ICD-10; file and retrieve records; safeguard confidentiality; audit documentation completeness",
            "Coding accuracy, Records-retrieval time, Audit completeness, Confidentiality breaches",
            24),
        new("BIOMED-ENG-001", "Biomedical Engineer", 3, 6_000m, 10_000m, "OPERATIONS", "FAC-MGR-001", false, "BSc Biomedical Engineering", 3,
            "Medical Equipment Maintenance, Calibration, Equipment Specification, Vendor Liaison",
            "Engineer maintaining and managing the medical-equipment fleet across {Company}",
            "ADM-5",
            "Service and calibrate medical equipment; specify new equipment; manage AMC contracts; train clinical users on safe use",
            "Equipment uptime, PPM compliance, Calibration coverage, MTTR",
            24),

        // ── Junior Clinical & Support (Rank 2) ───────────────────────────────────
        new("HO-001", "House Officer", 2, 3_500m, 5_500m, "MEDICAL", "MO-001", false, "MD (in housemanship)", 0,
            "Clerking, Procedures, Documentation, Resuscitation",
            "Newly-qualified medical doctor undertaking the mandatory housemanship rotation at {Company}",
            "MED-2",
            "Clerk admissions; carry out scheduled procedures; document patient records; participate in calls under supervision",
            "Documentation rate, Procedure logbook, On-call coverage, Supervisor evaluation",
            21),
        new("SN-001", "Senior Staff Nurse", 2, 4_000m, 6_500m, "NURSING", "WARD-MGR-001", false, "Diploma Nursing + 4 yrs", 4,
            "Patient Care, Medication Administration, Mentorship, Documentation",
            "Senior staff nurse leading shifts and mentoring junior nurses at {Company}",
            "MED-3",
            "Lead nursing shifts; administer medications; supervise EN and HCAs; document care; manage minor procedures",
            "Medication-error rate, Shift incidents, Documentation accuracy, Mentee feedback",
            21),
        new("STAFF-NURSE-001", "Staff Nurse", 2, 3_000m, 5_500m, "NURSING", "SN-001", false, "Diploma / BSc Nursing", 1,
            "Patient Care, Medication, Vital Signs, Wound Care, Documentation",
            "Registered staff nurse delivering bedside care across {Company} wards",
            "MED-2",
            "Take vital signs; administer medications; perform wound care; bathe and feed patients; document interventions",
            "Medication-error rate, Pressure-ulcer rate, Documentation rate, Patient feedback",
            21),
        new("EN-001", "Enrolled Nurse", 2, 2_500m, 4_200m, "NURSING", "STAFF-NURSE-001", false, "Enrolled Nursing Certificate", 1,
            "Bedside Care, Bathing, Vital Signs, Specimen Collection",
            "Enrolled nurse providing bedside support to staff nurses at {Company}",
            "MED-2",
            "Support staff nurses on the ward; bathe patients; record vitals; collect specimens; assist with mobility",
            "Documentation rate, Care-bundle compliance, Patient feedback, Shift coverage",
            21),
        new("OPD-NURSE-001", "OPD Nurse", 2, 3_000m, 5_500m, "OUTPATIENT", "STAFF-NURSE-001", false, "Diploma / BSc Nursing", 1,
            "Triage Support, Patient Education, Vital Signs, Procedures",
            "Outpatient nurse supporting clinics and walk-in services at {Company}",
            "MED-2",
            "Take vitals and triage data; support clinic flow; deliver minor procedures; educate patients; manage clinic stocks",
            "Patient-throughput per clinic, Triage accuracy, Documentation rate, Patient feedback",
            21),
        new("TRIAGE-NURSE-001", "Triage Nurse", 2, 3_500m, 6_000m, "EMERGENCY", "STAFF-NURSE-001", false, "Diploma Nursing + Triage Cert", 2,
            "Emergency Triage, ESI / SATS, First Aid, Documentation",
            "Specialist nurse running first-line emergency triage at the {Company} A&E department",
            "MED-3",
            "Assess incoming patients; assign triage categories; record vitals; escalate red cases immediately; document triage decisions",
            "Triage accuracy, Time-to-triage, Escalation appropriateness, Documentation",
            21),
        new("PHARM-TECH-001", "Pharmacy Technician", 2, 2_800m, 4_800m, "CLINICAL-SUPPORT", "PHARM-001", false, "Pharmacy Technician Diploma", 1,
            "Dispensing Support, Pre-Packing, Inventory, Patient Counselling",
            "Pharmacy technician supporting dispensing operations at {Company}",
            "MED-2",
            "Pre-pack medications; support dispensing; reconcile stock; refer patients to pharmacists for counselling; clean dispensing area",
            "Dispensing accuracy, Stock reconciliation, Speed of service, Patient feedback",
            21),
        new("LAB-TECH-001", "Medical Laboratory Technician", 2, 2_800m, 4_800m, "CLINICAL-SUPPORT", "LAB-SCI-001", false, "Lab Technician Diploma", 1,
            "Phlebotomy, Sample Reception, Basic Tests, Specimen Transport",
            "Lab technician supporting sample reception, phlebotomy, and basic testing at {Company}",
            "MED-2",
            "Collect and receive specimens; perform basic tests; transport samples; maintain clean work areas; support QC tasks",
            "Sample integrity, Result turnaround, Phlebotomy success, QC compliance",
            21),
        new("RECEP-001", "Receptionist / Front Desk Officer", 2, 2_500m, 3_800m, "OUTPATIENT", "PAO-001", false, "SHS / HND", 1,
            "Front Desk, Appointments, NHIS Verification, Telephone Etiquette",
            "Front-desk officer welcoming patients and managing appointments at {Company}",
            "ADM-2",
            "Greet patients; verify NHIS / private status; book appointments; answer phones; route enquiries to clinicians",
            "Appointment-booking accuracy, Wait-time at reception, Patient feedback, Call response",
            21),
        new("BILLING-001", "Billing Officer", 2, 2_500m, 4_500m, "FINANCE", "ACCT-001", false, "HND / Bachelor's Accounting", 1,
            "Hospital Billing, NHIS Claims, Private Insurance, Cash Reconciliation",
            "Billing officer raising invoices and processing NHIS claims at {Company}",
            "ADM-3",
            "Raise itemised bills; process NHIS claim batches; reconcile insurance schedules; resolve billing queries; submit daily reconciliation",
            "Claim-rejection rate, Bill-raising timeliness, Reconciliation accuracy, Patient billing complaints",
            21),
        new("CASHIER-001", "Cashier", 2, 2_500m, 3_800m, "FINANCE", "ACCT-001", false, "SHS / HND", 0,
            "Cash Handling, POS Operation, End-of-Day Reconciliation, Customer Service",
            "Cashier collecting payments at {Company} OPD, pharmacy, and inpatient billing points",
            "ADM-2",
            "Receive cash, card and mobile-money payments; issue receipts; reconcile end-of-shift; deposit takings; resolve simple billing queries",
            "Cash-balancing accuracy, Patient feedback, Speed of service, Variance incidents",
            21),
        new("WA-001", "Ward Assistant / Health Care Assistant", 2, 2_500m, 3_500m, "INPATIENT-WARDS", "STAFF-NURSE-001", false, "JHS / Cert in HCA", 0,
            "Patient Hygiene, Bed Making, Mobility Support, Linen Management",
            "Ward assistant supporting nurses with non-clinical patient care tasks at {Company}",
            "ADM-2",
            "Bathe and feed patients; change linen; assist with mobility; transport specimens; clean ward equipment",
            "Linen turnover, Hygiene-audit score, Incident reports, Patient feedback",
            21),
        new("DRIVER-001", "Hospital Driver / Ambulance Driver", 2, 2_500m, 4_200m, "OPERATIONS", "FAC-MGR-001", false, "Class C Licence + Defensive Driving", 2,
            "Defensive Driving, Ambulance Operation, Logbook, Patient Transport",
            "Hospital driver running ambulance and logistics fleet for {Company}",
            "ADM-3",
            "Drive ambulances and pool vehicles; maintain logbooks; perform daily vehicle checks; respond to emergency calls; transport staff and patients",
            "Trip-completion rate, Vehicle-incident rate, Logbook accuracy, Response time",
            21),
        new("SECURITY-001", "Security Officer", 2, 2_500m, 3_500m, "OPERATIONS", "FAC-MGR-001", false, "SHS / Trained Security Guard", 1,
            "Premises Security, Access Control, CCTV, Crowd Management",
            "Security officer protecting {Company} premises, staff, patients and visitors",
            "ADM-2",
            "Patrol premises; manage gate access; monitor CCTV; control crowds at OPD and pharmacy; report incidents",
            "Incidents per shift, Patrol coverage, Response time, Visitor-feedback score",
            21),
        new("MORT-001", "Mortuary Attendant", 2, 2_500m, 4_000m, "OPERATIONS", "PATH-001", false, "JHS / Mortuary Cert", 1,
            "Body Handling, Refrigeration, Documentation, Family Liaison",
            "Mortuary attendant managing body reception, storage and release at {Company}",
            "ADM-2",
            "Receive bodies; tag and document; manage refrigeration; assist at autopsy; release bodies to families with paperwork",
            "Documentation accuracy, Refrigeration uptime, Family-feedback score, Release turnaround",
            21),

        // ── Entry-level (Rank 1) ─────────────────────────────────────────────────
        new("CLEANER-001", "Cleaner / Sanitation Attendant", 1, 1_300m, 2_200m, "OPERATIONS", "FAC-MGR-001", false, "JHS", 0,
            "Cleaning, Waste Segregation, Disinfection, Confidentiality",
            "Cleaner maintaining hygiene across wards, theatres, and public areas at {Company}",
            "ADM-1",
            "Clean and disinfect assigned areas; segregate clinical and general waste; restock toiletries; report hazards",
            "Cleaning-audit score, Waste-segregation compliance, Hazard reports, Patient feedback",
            21),
        new("PORTER-001", "Hospital Porter", 1, 1_400m, 2_400m, "EMERGENCY", "FAC-MGR-001", false, "JHS", 0,
            "Patient Transport, Equipment Movement, Specimen Transport, Communication",
            "Porter moving patients, equipment and specimens across {Company} departments",
            "ADM-1",
            "Transport patients between wards and imaging; move equipment safely; deliver specimens; respond to porter calls",
            "Response time, Trip-completion rate, Equipment-handling incidents, Patient feedback",
            21),
        new("MED-INTERN-001", "Medical Intern / Student Doctor", 1, 1_500m, 2_500m, "MEDICAL", "HO-001", false, "MD Student / Clinical Year", 0,
            "Clinical Skills, Clerking, Procedures (Supervised), Communication",
            "Final-year medical student rotating across departments at {Company} as part of clinical training",
            "MED-1",
            "Clerk patients under supervision; observe procedures; participate in ward rounds; complete logbook; attend teaching sessions",
            "Logbook completion, Supervisor evaluation, Attendance, Skill checklist",
            21),
        new("NURSE-INTERN-001", "Nursing Intern", 1, 1_500m, 2_500m, "NURSING", "STAFF-NURSE-001", false, "Nursing Student", 0,
            "Bedside Care (Supervised), Vital Signs, Documentation, Learning",
            "Student nurse undertaking supervised clinical rotations at {Company}",
            "MED-1",
            "Provide supervised bedside care; record vitals; document under guidance; attend teaching ward rounds; complete competency book",
            "Competency completion, Attendance, Mentor evaluation, Patient feedback",
            21),
        new("LAB-INTERN-001", "Laboratory Intern", 1, 1_500m, 2_500m, "CLINICAL-SUPPORT", "LAB-TECH-001", false, "Lab Sciences Student", 0,
            "Specimen Handling, Basic Tests, QC Awareness, Documentation",
            "Student lab scientist on practical attachment at the {Company} laboratory",
            "MED-1",
            "Support specimen reception and processing under supervision; observe analytical workflows; complete competency logbook",
            "Logbook completion, Attendance, Supervisor evaluation, QC awareness",
            21),
        new("PHARM-INTERN-001", "Pharmacy Intern", 1, 1_800m, 3_000m, "CLINICAL-SUPPORT", "PHARM-001", false, "PharmD Intern (registered)", 0,
            "Dispensing (Supervised), Counselling, Inventory, Compounding",
            "Pharmacy intern undertaking the registered post-graduate internship year at {Company}",
            "MED-1",
            "Dispense under supervision; counsel patients; rotate through clinical pharmacy; maintain logbook; pass internship assessments",
            "Logbook completion, Dispensing accuracy, Attendance, Preceptor evaluation",
            21)
    ];

    // Curated corporate-tier station catalogue — flagship Main Hospital plus regional and
    // district hospitals, polyclinics, health centres, and CHPS compounds spread across all
    // 16 Ghana regions. Phones use the Ghana national format; emails store ONLY the local
    // part (before @) so the row factory appends the actual company TLD at runtime.
    private static readonly StationSpec[] _healthcareStations =
    [
        // ── Main Hospital (HQ) ───────────────────────────────────────────────────
        new("HQ-001", "Main Hospital - Accra", "Main Hospital", "Greater Accra", "Accra", "23 Liberation Road, Ridge", 800, 2500, "{Company} flagship tertiary hospital housing executive offices, all clinical specialties, theatres, ICU and teaching facilities", "+233 30 222 4100", "headoffice"),

        // ── Regional Hospitals ───────────────────────────────────────────────────
        new("RH-ASH-001", "Ashanti Regional Hospital - Kumasi", "Regional Hospital", "Ashanti", "Kumasi", "Bantama High Street, Kumasi", 250, 600, "{Company} regional referral hospital serving the Ashanti Region with full specialty services", "+233 32 202 4100", "ashanti.regional"),
        new("RH-WES-001", "Western Regional Hospital - Takoradi", "Regional Hospital", "Western", "Takoradi", "Effia Nkwanta Road, Takoradi", 220, 550, "{Company} regional referral facility supporting Western and Western North Regions with surgical, medical and maternity care", "+233 31 202 4100", "western.regional"),
        new("RH-NOR-001", "Northern Regional Hospital - Tamale", "Regional Hospital", "Northern", "Tamale", "Hospital Road, Central Tamale", 200, 500, "{Company} regional facility for the Northern, North East and Savannah Regions providing tertiary-level care", "+233 37 202 4100", "northern.regional"),
        new("RH-VOL-001", "Volta Regional Hospital - Ho", "Regional Hospital", "Volta", "Ho", "Ho-Aflao Road, Ho Central", 180, 480, "{Company} regional facility serving Volta and Oti Regions with full specialty and referral services", "+233 36 202 4100", "volta.regional"),
        new("RH-CEN-001", "Central Regional Hospital - Cape Coast", "Regional Hospital", "Central", "Cape Coast", "Cape Coast - Elmina Road, Cape Coast", 200, 520, "{Company} regional referral hospital serving Central Region with surgical, paediatric and maternal services", "+233 33 202 4100", "central.regional"),
        new("RH-EAS-001", "Eastern Regional Hospital - Koforidua", "Regional Hospital", "Eastern", "Koforidua", "Hospital Road, Koforidua", 180, 480, "{Company} regional referral hospital for Eastern Region providing emergency, surgical and obstetric services", "+233 34 202 4100", "eastern.regional"),

        // ── District Hospitals ───────────────────────────────────────────────────
        new("DH-TEM-001", "Tema District Hospital", "District Hospital", "Greater Accra", "Tema", "Hospital Road, Community 9, Tema", 150, 350, "{Company} district hospital serving Tema metropolis with surgical, medical, paediatric and emergency services", "+233 30 322 4100", "tema.district"),
        new("DH-KAS-001", "Kasoa District Hospital", "District Hospital", "Central", "Kasoa", "Kasoa - Winneba Road, Kasoa", 120, 280, "{Company} district hospital meeting the demand of the rapidly-growing Kasoa community", "+233 33 202 4101", "kasoa.district"),
        new("DH-OBU-001", "Obuasi District Hospital", "District Hospital", "Ashanti", "Obuasi", "AngloGold Mine Road, Obuasi", 120, 280, "{Company} district hospital serving Obuasi mining community and surrounding villages", "+233 32 209 4100", "obuasi.district"),
        new("DH-KFO-001", "Koforidua District Hospital", "District Hospital", "Eastern", "Koforidua", "Effiduase Road, Koforidua", 120, 260, "{Company} district hospital providing maternal, surgical and outpatient services in Koforidua", "+233 34 202 4101", "koforidua.district"),
        new("DH-NKW-001", "Nkawkaw District Hospital", "District Hospital", "Eastern", "Nkawkaw", "Accra-Kumasi Highway, Nkawkaw", 100, 220, "{Company} district hospital on the busy Accra-Kumasi highway with trauma capability", "+233 34 202 4102", "nkawkaw.district"),
        new("DH-SUN-001", "Sunyani District Hospital", "District Hospital", "Bono", "Sunyani", "Fiapre Road, Sunyani", 110, 260, "{Company} district hospital for the Bono Region capital with surgical and obstetric services", "+233 35 202 4100", "sunyani.district"),
        new("DH-TCH-001", "Techiman District Hospital", "District Hospital", "Bono East", "Techiman", "Techiman Market Road, Techiman", 100, 240, "{Company} district hospital serving Techiman, a major commercial and transit hub in the Bono East Region", "+233 35 209 4100", "techiman.district"),
        new("DH-WA-001", "Wa District Hospital", "District Hospital", "Upper West", "Wa", "Wa Main Road, Wa Central", 90, 220, "{Company} district hospital serving the Upper West Region capital and surrounding rural communities", "+233 39 202 4100", "wa.district"),
        new("DH-BOL-001", "Bolgatanga District Hospital", "District Hospital", "Upper East", "Bolgatanga", "Zuarungu Road, Bolgatanga", 90, 220, "{Company} district hospital for the Upper East Region capital, supported by satellite health centres", "+233 37 202 4101", "bolgatanga.district"),
        new("DH-HOH-001", "Hohoe District Hospital", "District Hospital", "Volta", "Hohoe", "Hohoe Market Road, Hohoe", 100, 220, "{Company} district hospital serving the Hohoe traditional area in the Volta Region", "+233 36 202 4101", "hohoe.district"),

        // ── Polyclinics ──────────────────────────────────────────────────────────
        new("PC-MAD-001", "Madina Polyclinic", "Polyclinic", "Greater Accra", "Accra", "Madina Market Road, Madina", 60, 140, "{Company} polyclinic serving Madina and surrounding peri-urban communities with OPD and maternity", "+233 30 222 4501", "madina.polyclinic"),
        new("PC-DAN-001", "Dansoman Polyclinic", "Polyclinic", "Greater Accra", "Accra", "Dansoman Last Stop, Dansoman", 60, 140, "{Company} polyclinic for the Dansoman residential corridor providing OPD, child welfare and minor procedures", "+233 30 222 4502", "dansoman.polyclinic"),
        new("PC-LAP-001", "Lapaz Polyclinic", "Polyclinic", "Greater Accra", "Accra", "Lapaz Main Road, Lapaz", 50, 130, "{Company} polyclinic at Lapaz serving the dense northern Accra commercial belt", "+233 30 222 4503", "lapaz.polyclinic"),
        new("PC-ASH-001", "Ashaiman Polyclinic", "Polyclinic", "Greater Accra", "Ashaiman", "Ashaiman Market Road, Ashaiman", 60, 140, "{Company} polyclinic offering general OPD, maternity and laboratory services to Ashaiman residents", "+233 30 322 4501", "ashaiman.polyclinic"),
        new("PC-KSI-001", "Kumasi South Polyclinic", "Polyclinic", "Ashanti", "Kumasi", "Asokwa Industrial Area, Kumasi", 60, 140, "{Company} polyclinic in southern Kumasi serving Asokwa industrial and residential communities", "+233 32 202 4500", "kumasisouth.polyclinic"),
        new("PC-SUA-001", "Suame Polyclinic", "Polyclinic", "Ashanti", "Kumasi", "Suame Magazine Road, Suame", 50, 130, "{Company} polyclinic at Suame providing OPD and minor procedures to artisans and residents", "+233 32 202 4501", "suame.polyclinic"),
        new("PC-SEK-001", "Sekondi Polyclinic", "Polyclinic", "Western", "Sekondi", "Railway Line Road, Sekondi", 50, 130, "{Company} polyclinic for Sekondi fishing and naval communities", "+233 31 202 4501", "sekondi.polyclinic"),
        new("PC-CCD-001", "Cape Coast Polyclinic", "Polyclinic", "Central", "Cape Coast", "Commercial Street, Cape Coast", 50, 130, "{Company} polyclinic in Cape Coast supporting the regional hospital with primary-care services", "+233 33 202 4501", "capecoast.polyclinic"),
        new("PC-BER-001", "Berekum Polyclinic", "Polyclinic", "Bono", "Berekum", "Senase Road, Berekum", 50, 130, "{Company} polyclinic for Berekum providing OPD, maternal and child health services", "+233 35 202 4501", "berekum.polyclinic"),
        new("PC-WIN-001", "Winneba Polyclinic", "Polyclinic", "Central", "Winneba", "Winneba Junction Road, Winneba", 50, 120, "{Company} polyclinic in Winneba serving university students and surrounding communities", "+233 33 202 4502", "winneba.polyclinic"),

        // ── Health Centres ───────────────────────────────────────────────────────
        new("HC-AMA-001", "Amasaman Health Centre", "Health Centre", "Greater Accra", "Amasaman", "Nsawam-Accra Road, Amasaman", 25, 60, "{Company} health centre serving Amasaman and the Ga West district with OPD and maternal services", "+233 30 222 4801", "amasaman.hc"),
        new("HC-DOM-001", "Dome Health Centre", "Health Centre", "Greater Accra", "Accra", "Dome Faase Road, Dome", 20, 50, "{Company} health centre providing primary care to Dome and surrounding communities", "+233 30 222 4802", "dome.hc"),
        new("HC-EJI-001", "Ejisu Health Centre", "Health Centre", "Ashanti", "Ejisu", "Kumasi-Accra Road, Ejisu", 25, 60, "{Company} health centre serving Ejisu municipality with primary care and immunisation services", "+233 32 202 4801", "ejisu.hc"),
        new("HC-MAM-001", "Mampong Health Centre", "Health Centre", "Ashanti", "Mampong", "Mampong-Ejura Road, Mampong", 20, 50, "{Company} health centre supporting Mampong and the Sekyere Central district", "+233 32 202 4802", "mampong.hc"),
        new("HC-TAR-001", "Tarkwa Health Centre", "Health Centre", "Western", "Tarkwa", "Tarkwa Town Road, Tarkwa", 25, 60, "{Company} health centre serving Tarkwa mining community with OPD and occupational health support", "+233 31 202 4801", "tarkwa.hc"),
        new("HC-BAW-001", "Bawku Health Centre", "Health Centre", "Upper East", "Bawku", "Bawku Main Road, Bawku Central", 20, 55, "{Company} health centre extending primary-care reach in the Upper East Region", "+233 37 202 4801", "bawku.hc"),
        new("HC-GOA-001", "Goaso Health Centre", "Health Centre", "Ahafo", "Goaso", "Goaso Town Road, Goaso", 20, 50, "{Company} health centre for Goaso, the Ahafo Regional capital, providing OPD and maternity", "+233 35 202 4801", "goaso.hc"),
        new("HC-DAM-001", "Damongo Health Centre", "Health Centre", "Savannah", "Damongo", "Damongo Town Road, Damongo", 20, 50, "{Company} health centre in Damongo, the Savannah Region capital, supporting rural primary care", "+233 37 202 4802", "damongo.hc"),

        // ── CHPS Compounds ───────────────────────────────────────────────────────
        new("CHPS-NAN-001", "Nandom CHPS Compound", "CHPS Compound", "Upper West", "Nandom", "Nandom Town, Lawra District", 5, 12, "{Company} CHPS compound providing community-based primary care to the Nandom traditional area", "+233 39 209 4901", "nandom.chps"),
        new("CHPS-WUL-001", "Wulensi CHPS Compound", "CHPS Compound", "North East", "Wulensi", "Wulensi Town, Nanumba South", 5, 10, "{Company} CHPS compound serving Wulensi rural community with antenatal and child welfare services", "+233 37 209 4901", "wulensi.chps"),
        new("CHPS-NKR-001", "Nkoranza CHPS Compound", "CHPS Compound", "Bono East", "Nkoranza", "Nkoranza Town Road, Nkoranza", 5, 12, "{Company} CHPS compound supporting the Nkoranza farming community with primary-care outreach", "+233 35 219 4901", "nkoranza.chps"),
        new("CHPS-DZO-001", "Dzodze CHPS Compound", "CHPS Compound", "Volta", "Dzodze", "Dzodze Town Road, Ketu North", 5, 10, "{Company} CHPS compound for Dzodze cross-border community with malaria and maternal-health focus", "+233 36 209 4901", "dzodze.chps"),
        new("CHPS-ENC-001", "Enchi CHPS Compound", "CHPS Compound", "Western North", "Enchi", "Enchi Town Road, Aowin Suaman", 5, 10, "{Company} CHPS compound serving Enchi and surrounding cocoa-farming communities", "+233 31 219 4901", "enchi.chps")
    ];
}
