namespace QimErp.Shared.Common.Services;

/// <summary>
/// Helpers for working with entity codes generated by <see cref="IEntityCodeService"/>.
/// </summary>
public static class EntityCodeHelper
{
    /// <summary>
    /// Extracts the trailing numeric sequence from a formatted entity code.
    /// Used to populate legacy <c>No</c> fields when codes come from <see cref="IEntityCodeService"/>.
    /// </summary>
    public static int ExtractSequenceNo(string code)
    {
        if (string.IsNullOrWhiteSpace(code))
            return 0;

        var digits = new string(code.Reverse().TakeWhile(char.IsDigit).Reverse().ToArray());
        return int.TryParse(digits, out var n) ? n : 0;
    }
}
