using Temporalio.Workflows;

namespace QimErp.Shared.Common.Activities.DemoSeed;

/// <summary>
/// Parent workflow that orchestrates the end-to-end demo-tenant seed:
///   Phase 1  CreateAndActivateDemoTenantActivity (IAM)        — calls existing TenantRegistrationService + AccountActivationService
///   Phase 2  WaitForTenantOnboardingActivity (Platform)        — awaits tenant-onboarding-{tenantId} via Temporal handle
///   Phase 3  SeedDemoEmployeesWorkflow (CoreHr) child          — scaffolds org + bulk-inserts employees + assigns supervisors
///   Phase 4  SeedDemoLeaveWorkflow (Leave) child               — fills leave history
///   Phase 5  EmployeeBulkSyncWorkflow (CoreHr)                 — fans out new employees to other modules
///   Phase 6  FinalizeDemoSeedActivity (Platform)               — terminal state, notifications
///
/// Hosted on qimerp-platform-demo-seed task queue.
/// </summary>
[Workflow("DemoTenantSeedWorkflow")]
public interface IDemoTenantSeedWorkflow
{
    [WorkflowRun]
    Task<DemoTenantSeedResult> RunAsync(DemoTenantSeedRequest request);

    /// <summary>Aggregate state for the polling endpoint and progress UI.</summary>
    [WorkflowQuery]
    DemoSeedState GetState();

    /// <summary>Fired by child workflows on each batch boundary.</summary>
    [WorkflowSignal]
    Task OnEmployeeBatchCompletedAsync(BatchProgress batch);

    [WorkflowSignal]
    Task OnPhaseStatusAsync(PhaseUpdate update);
}

public sealed class DemoTenantSeedRequest
{
    public required string Industry { get; set; } = "Banking";
    public required string CompanyType { get; set; } = "Corporate";
    public required int EmployeeCount { get; set; }
    public string Country { get; set; } = "Ghana";

    /// <summary>Caller-supplied or auto-generated by IAM endpoint.</summary>
    public string? Company { get; set; }
    public string? Domain { get; set; }
    public string? AdminEmail { get; set; }
    public string? AdminFirstName { get; set; }
    public string? AdminLastName { get; set; }
    public string PlanType { get; set; } = "Pro";
    public string BillingCycle { get; set; } = "Monthly";
    public List<string>? SelectedModules { get; set; }

    public bool DryRun { get; set; }
    public int? RandomSeed { get; set; }
    public bool AllowInProduction { get; set; }

    /// <summary>Job id surfaced to the UI for polling — synthesised by the IAM endpoint.</summary>
    public required string JobId { get; set; }
    public required string TriggeredByEmail { get; set; }
}

public sealed class DemoTenantSeedResult
{
    public bool Success { get; set; }
    public Guid? TenantId { get; set; }
    public string? Domain { get; set; }
    public string? SuperAdminEmail { get; set; }
    public string? GeneratedPassword { get; set; }
    public DemoSeedState State { get; set; } = new();
    public List<StepFailureInfo> Failures { get; } = new();
    public TimeSpan TotalElapsed { get; set; }
}

public sealed class DemoSeedState
{
    public string JobId { get; set; } = "";
    public Guid? TenantId { get; set; }
    public string? Domain { get; set; }
    public string CurrentPhase { get; set; } = "Pending";
    public DateTime? StartedAtUtc { get; set; }
    public DateTime? CompletedAtUtc { get; set; }
    public PhaseStatus TenantCreation { get; set; } = new();
    public PhaseStatus TenantOnboarding { get; set; } = new();
    public PhaseStatus EmployeeSeed { get; set; } = new();
    public PhaseStatus LeaveSeed { get; set; } = new();
    public PhaseStatus PayrollSeed { get; set; } = new();
    public PhaseStatus BenefitSeed { get; set; } = new();
    public PhaseStatus EmployeeEngagementSeed { get; set; } = new();
    public PhaseStatus LearningSeed { get; set; } = new();
    public PhaseStatus NotificationsSeed { get; set; } = new();
    public PhaseStatus PerformanceSeed { get; set; } = new();
    public PhaseStatus PlatformWorkflowSeed { get; set; } = new();
    public PhaseStatus RecruitmentSeed { get; set; } = new();
    public PhaseStatus SurveySeed { get; set; } = new();
    public PhaseStatus TalentSeed { get; set; } = new();
    public PhaseStatus TenantBillingSeed { get; set; } = new();
    public PhaseStatus WorkforcePlanningSeed { get; set; } = new();
    public PhaseStatus EmployeeSync { get; set; } = new();
    public PhaseStatus Finalisation { get; set; } = new();
    public List<StepFailureInfo> Failures { get; } = new();
    public bool IsTerminal { get; set; }
}

public sealed class PhaseStatus
{
    public string Phase { get; set; } = "Pending"; // Pending | Running | Completed | Failed | Skipped
    public string? SubPhase { get; set; }           // e.g. "Importing employees (1/2)" | "Seeding profiles (2/2)"
    public int? Total { get; set; }
    public int? Completed { get; set; }
    public DateTime? StartedAtUtc { get; set; }
    public DateTime? CompletedAtUtc { get; set; }
    public string? Error { get; set; }
}

public sealed record BatchProgress(int Completed, int Total, string? CurrentBatchInfo);

public sealed record PhaseUpdate(string Phase, string Status, string? Detail);

public sealed class StepFailureInfo
{
    public string Step { get; set; } = "";
    public string Error { get; set; } = "";
    public DateTime AtUtc { get; set; } = DateTime.UtcNow;
}
